const fs = require('fs');
const src = fs.readFileSync('tools/compile-units.js', 'utf8');
const start = src.indexOf('const ARABIC =');
const end = src.indexOf('function lessonOfVocab');
const helpers = src.slice(start, end);
const AR = /[\u0600-\u06FF]/;
const F = new Function(helpers + `
  return { fold, materialHas };
`)();
const { fold, materialHas } = F;
const texts = [];
const row = require('./tools/vocab-b2-w01')['b2-w01'];
row.items.forEach(it => texts.push(it[3], it[4]));
const spec = require('./tools/specs-b2').find(s => s.id === 'b2-w01');
texts.push(spec.model || '', spec.say || '', spec.hwDe || '');
spec.lex.forEach(l => texts.push(l[0], l[2], l[3]));
const folded = texts.filter(t => t && !AR.test(t)).map(fold);
const core = w => w.replace(/^(der|die|das)\s+/i,'').split(/\s+/).pop();
const missing = row.material.filter(w => !materialHas(core(w), folded));
console.log('material words:', row.material.length, '| missing:', missing.length);
missing.forEach(m => console.log('  ✗', m));
