/* Deutschweg — B1 lexical layer, unit 3 (part b): b1-u3-l4 … b1-u3-l6.
   40 items per lesson, the count the B1 rows declare (amendment B1-L1).
   Not wired yet — see the header of vocab-b1-u1a.js for why and how. */

module.exports = {

  'b1-u3-l4': {
    items: [
      ['die Medien', '—', 'وسائل الإعلام', 'Die Medien berichten täglich darüber.', 'Die Medien berichten täglich für das.', 'über لا für.', 'präposition', 'Medien'],
      ['die Presse', '—', 'الصحافة', 'Die Presse kritisiert den Plan.', 'Die Presse kritisiert über den Plan.', 'بلا حرف جر.', 'kasus', 'Presse'],
      ['die Zeitung', 'die Zeitungen', 'الجريدة', 'Die Zeitung erscheint täglich.', 'Die Zeitung erscheint in täglich.', 'بلا حرف جر.', 'präposition', 'Zeitung'],
      ['die Zeitschrift', 'die Zeitschriften', 'المجلة', 'Die Zeitschrift kommt monatlich.', 'Die Zeitschrift kommt in monatlich.', 'بلا حرف جر.', 'präposition', 'Zeitschrift'],
      ['die Nachrichten', '—', 'الأخبار', 'Ich sehe abends die Nachrichten.', 'Ich sehe abends die Nachricht.', 'الجمع: Nachrichten.', 'plural', 'Nachrichten'],
      ['die Meldung', 'die Meldungen', 'الخبر العاجل', 'Die Meldung kam zuerst im Radio.', 'Die Meldung kam zuerst in Radio.', 'im Radio.', 'präposition', 'Meldung'],
      ['der Bericht', 'die Berichte', 'التقرير', 'Der Bericht ist sachlich.', 'Der Bericht ist sachlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Bericht'],
      ['der Artikel', 'die Artikel', 'المقال', 'Der Artikel hat mich überzeugt.', 'Der Artikel hat mich überzeugen.', 'الماضي المركّب: überzeugt.', 'konjugation', 'Artikel'],
      ['die Schlagzeile', 'die Schlagzeilen', 'العنوان الرئيسي', 'Die Schlagzeile war reißerisch.', 'Die Schlagzeile war reißerisch gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Schlagzeile'],
      ['die Überschrift', 'die Überschriften', 'العنوان', 'Die Überschrift passt nicht zum Text.', 'Die Überschrift passt nicht zu dem Text.', 'الصيغة: zum جائزة أيضًا؛ الأجمل zum.', 'präposition', 'Überschrift'],
      ['die Quelle', 'die Quellen', 'المصدر', 'Man muss die Quelle prüfen.', 'Man muss die Quelle prüfen es.', 'لا ضمير زائد.', 'wortstellung', 'Quelle'],
      ['der Journalist', 'die Journalisten', 'الصحفي', 'Der Journalist stellt kritische Fragen.', 'Der Journalist stellt kritisch Fragen.', 'الصفة: kritische.', 'deklination', 'Journalist'],
      ['der Reporter', 'die Reporter', 'المراسل', 'Der Reporter war vor Ort.', 'Der Reporter war in Ort.', 'vor Ort ثابتة.', 'präposition', 'Reporter'],
      ['der Leser', 'die Leser', 'القارئ', 'Die Leser schreiben viele Briefe.', 'Die Leser schreiben viele Briefe es.', 'لا ضمير زائد.', 'wortstellung', 'Leser'],
      ['die Auflage', 'die Auflagen', 'النسخ المطبوعة', 'Die Auflage sinkt seit Jahren.', 'Die Auflage sinkt von Jahren.', 'منذ: seit.', 'präposition', 'Auflage'],
      ['die Reichweite', 'die Reichweiten', 'المدى الجماهيري', 'Die Reichweite des Senders ist groß.', 'Die Reichweite von dem Sender ist groß.', 'Genitiv أفضل.', 'kasus', 'Reichweite'],
      ['der Sender', 'die Sender', 'القناة', 'Der Sender zeigt den Film heute.', 'Der Sender zeigt den Film heute es.', 'لا ضمير زائد.', 'wortstellung', 'Sender'],
      ['das Fernsehen', '—', 'التلفاز', 'Im Fernsehen läuft nichts Gutes.', 'In Fernsehen läuft nichts Gutes.', 'im.', 'präposition', 'Fernsehen'],
      ['das Radio', 'die Radios', 'المذياع', 'Im Radio kam die Meldung zuerst.', 'In Radio kam die Meldung zuerst.', 'im.', 'präposition', 'Radio'],
      ['das Internet', '—', 'الإنترنت', 'Im Internet findet man alles.', 'In Internet findet man alles.', 'im.', 'präposition', 'Internet'],
      ['die Webseite', 'die Webseiten', 'الموقع الإلكتروني', 'Die Webseite lädt langsam.', 'Die Webseite lädt langsam es.', 'لا ضمير زائد.', 'wortstellung', 'Webseite'],
      ['der Beitrag', 'die Beiträge', 'المساهمة/المادة', 'Der Beitrag war gut recherchiert.', 'Der Beitrag war gut recherchieren.', 'الصفة + Partizip II.', 'konjugation', 'Beitrag'],
      ['die Sendung', 'die Sendungen', 'البرنامج', 'Die Sendung läuft um acht.', 'Die Sendung läuft in acht.', 'الساعة: um.', 'präposition', 'Sendung'],
      ['das Interview', 'die Interviews', 'المقابلة', 'Das Interview dauerte eine Stunde.', 'Das Interview dauerte für eine Stunde.', 'بلا حرف جر.', 'präposition', 'Interview'],
      ['die Werbung', 'die Werbungen', 'الإعلانات', 'Die Werbung nervt viele.', 'Die Werbung nervt viele es.', 'لا ضمير زائد.', 'wortstellung', 'Werbung'],
      ['die Meinungsfreiheit', '—', 'حرية الرأي', 'Die Meinungsfreiheit ist geschützt.', 'Die Meinungsfreiheit ist schützen.', 'المجهول: geschützt.', 'konjugation', 'Meinungsfreiheit'],
      ['die Zensur', 'die Zensuren', 'الرقابة', 'Zensur ist in vielen Ländern verboten.', 'Zensur ist in vielen Länder verboten.', 'الجمع داتيف: Ländern.', 'deklination', 'Zensur'],
      ['die Information', 'die Informationen', 'المعلومة', 'Die Informationen muss man prüfen.', 'Die Informationen muss man prüfen es.', 'لا ضمير زائد.', 'wortstellung', 'Informationen'],
      ['die Falschmeldung', 'die Falschmeldungen', 'الخبر الكاذب', 'Die Falschmeldung verbreitete sich schnell.', 'Die Falschmeldung hat sich schnell verbreitet gehabt.', 'السرد: verbreitete sich.', 'konjugation', 'Falschmeldung'],
      ['die Manipulation', 'die Manipulationen', 'التلاعب', 'Manipulation erkennt man nicht sofort.', 'Manipulation erkennt man nicht sofort es.', 'لا ضمير زائد.', 'wortstellung', 'Manipulation'],
      ['die Kritik', 'die Kritikpunkte', 'النقد', 'Die Kritik war berechtigt.', 'Die Kritik war berechtigt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Kritik'],
      ['der Einfluss', 'die Einflüsse', 'التأثير', 'Der Einfluss der Medien wächst.', 'Der Einfluss von den Medien wächst.', 'Genitiv أفضل.', 'kasus', 'Einfluss'],
      ['beeinflussen', 'beeinflusst · beeinflusste · hat beeinflusst', 'يؤثّر في', 'Werbung beeinflusst unsere Entscheidungen.', 'Werbung beeinflusst auf unsere Entscheidungen.', 'بلا حرف جر.', 'kasus', 'beeinflusst'],
      ['informieren', 'informiert · informierte · hat informiert', 'يُخبر', 'Die Zeitung informiert über den Unfall.', 'Die Zeitung informiert den Unfall.', 'über + نصب.', 'präposition', 'informiert'],
      ['berichten', 'berichtet · berichtete · hat berichtet', 'يخبر', 'Der Sender berichtet über die Wahlen.', 'Der Sender berichtet die Wahlen.', 'über + نصب.', 'präposition', 'berichtet'],
      ['veröffentlichen', 'veröffentlicht · veröffentlichte · hat veröffentlicht', 'ينشر', 'Der Autor veröffentlicht einen Roman.', 'Der Autor veröffentlicht für einen Roman.', 'بلا حرف جر.', 'kasus', 'veröffentlicht'],
      ['recherchieren', 'recherchiert · recherchierte · hat recherchiert', 'يتحقّق من المصادر', 'Der Journalist recherchiert gründlich.', 'Der Journalist recherchiert gründlich es.', 'لا ضمير زائد.', 'wortstellung', 'recherchiert'],
      ['kommentieren', 'kommentiert · kommentierte · hat kommentiert', 'يعلّق على', 'Viele kommentieren den Artikel online.', 'Viele kommentieren über den Artikel.', 'بلا حرف جر.', 'kasus', 'kommentieren'],
      ['die Diskussion', 'die Diskussionen', 'النقاش', 'Die Diskussion läuft sachlich.', 'Die Diskussion läuft sachlich es.', 'لا ضمير زائد.', 'wortstellung', 'Diskussion'],
      ['der Kommentar', 'die Kommentare', 'التعليق', 'Sein Kommentar war unfair.', 'Sein Kommentar war unfair gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Kommentar']
    ],
    tricks: [
      { trick: 'أفعال الإعلام بحروفها: berichten über · informieren über · kommentieren (بلا حرف)', wie: 'Der Sender berichtet über die Wahlen. · Viele kommentieren den Artikel.', warum: 'العربية تقول «تحدّث عن/علّق على» بحرف واحد، والألمانية تفرّق بين الفعلين.', anchor: 'berichten' },
      { trick: 'المصدر يُذكر: die Quelle · die Meldung · die Falschmeldung', wie: 'Man muss die Quelle prüfen. · Die Falschmeldung verbreitete sich schnell.', warum: 'الخبر في العربية يُصدَّق بلا مصدر مذكور، والنقد الألماني يبدأ بسؤال المصدر.', anchor: 'die Quelle' },
      { trick: 'im Fernsehen · im Radio · im Internet — دائمًا im', wie: 'Im Radio kam die Meldung zuerst. · Im Internet findet man alles.', warum: 'العربية تقول «على التلفاز/في الإنترنت»، والألمانية تثبّت im للتلفاز والمذياع.', anchor: 'das Fernsehen' }
    ]
  },

  'b1-u3-l5': {
    items: [
      ['die Bildung', '—', 'التعليم', 'Bildung ist der Schlüssel zum Erfolg.', 'Bildung ist der Schlüssel für den Erfolg.', 'zu لا für.', 'präposition', 'Bildung'],
      ['die Ausbildung', 'die Ausbildungen', 'التكوين المهني', 'Die Ausbildung dauert drei Jahre.', 'Die Ausbildung dauert für drei Jahre.', 'بلا حرف جر.', 'präposition', 'Ausbildung'],
      ['die Weiterbildung', 'die Weiterbildungen', 'التكوين المستمر', 'Die Firma zahlt die Weiterbildung.', 'Die Firma zahlt für die Weiterbildung.', 'بلا حرف جر.', 'kasus', 'Weiterbildung'],
      ['die Fortbildung', 'die Fortbildungen', 'الدورة التدريبية', 'Die Fortbildung findet online statt.', 'Die Fortbildung findet online.', 'stattfinden يحتاج statt.', 'wortstellung', 'statt'],
      ['das Studium', 'die Studien', 'الدراسة الجامعية', 'Das Studium beginnt im Oktober.', 'Das Studium beginnt in Oktober.', 'im.', 'präposition', 'Studium'],
      ['die Universität', 'die Universitäten', 'الجامعة', 'Die Universität liegt am Stadtrand.', 'Die Universität liegt in Stadtrand.', 'am Stadtrand.', 'präposition', 'Universität'],
      ['die Hochschule', 'die Hochschulen', 'المعهد العالي', 'Die Hochschule ist bekannt.', 'Die Hochschule ist bekannt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Hochschule'],
      ['die Fachhochschule', 'die Fachhochschulen', 'المعهد التقني', 'Die Fachhochschule ist praxisnah.', 'Die Fachhochschule ist praxisnah gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Fachhochschule'],
      ['der Studiengang', 'die Studiengänge', 'التخصص', 'Der Studiengang ist zulassungsbeschränkt.', 'Der Studiengang ist zulassungsbeschränkt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Studiengang'],
      ['das Fach', 'die Fächer', 'المادة', 'Mein bestes Fach ist Mathematik.', 'Mein bestes Fach ist Mathematik es.', 'لا ضمير زائد.', 'wortstellung', 'Fach'],
      ['das Seminar', 'die Seminare', 'الحلقة الدراسية', 'Das Seminar ist freiwillig.', 'Das Seminar ist freiwillig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Seminar'],
      ['die Vorlesung', 'die Vorlesungen', 'المحاضرة', 'Die Vorlesung beginnt um acht.', 'Die Vorlesung beginnt in acht.', 'الساعة: um.', 'präposition', 'Vorlesung'],
      ['der Dozent', 'die Dozenten', 'المحاضر', 'Der Dozent erklärt sehr klar.', 'Der Dozent erklärt sehr klar es.', 'لا ضمير زائد.', 'wortstellung', 'Dozent'],
      ['der Professor', 'die Professoren', 'الأستاذ الجامعي', 'Der Professor forscht in Berlin.', 'Der Professor forscht in Berlin es.', 'لا ضمير زائد.', 'wortstellung', 'Professor'],
      ['der Student', 'die Studenten', 'الطالب', 'Die Studenten lernen für die Prüfung.', 'Die Studenten lernen für die Prüfung es.', 'لا ضمير زائد.', 'wortstellung', 'Studenten'],
      ['der Auszubildende', 'die Auszubildenden', 'المتدرّب', 'Der Auszubildende verdient wenig.', 'Der Auszubildende verdient wenig es.', 'لا ضمير زائد.', 'wortstellung', 'Auszubildende'],
      ['die Prüfung', 'die Prüfungen', 'الامتحان', 'Die Prüfung wird schriftlich gemacht.', 'Die Prüfung wird schriftlich machen.', 'المجهول: gemacht.', 'konjugation', 'Prüfung'],
      ['die Note', 'die Noten', 'العلامة', 'Gute Noten öffnen Türen.', 'Gute Noten öffnen Türen es.', 'لا ضمير زائد.', 'wortstellung', 'Noten'],
      ['das Zeugnis', 'die Zeugnisse', 'الشهادة', 'Das Zeugnis bekommt man im Juli.', 'Das Zeugnis bekommt man in Juli.', 'im.', 'präposition', 'Zeugnis'],
      ['der Abschluss', 'die Abschlüsse', 'الشهادة النهائية', 'Der Abschluss ist anerkannt.', 'Der Abschluss ist anerkennen.', 'المجهول: anerkannt.', 'konjugation', 'Abschluss'],
      ['die Note verbessern', 'verbessert · verbesserte · hat verbessert', 'يحسّن العلامة', 'Er will seine Note verbessern.', 'Er will seine Note besser machen.', 'الفعل: verbessern.', 'lexik-kollokation', 'verbessern'],
      ['bestehen', 'besteht · bestand · hat bestanden', 'ينجح', 'Ich habe die Prüfung bestanden.', 'Ich habe die Prüfung bestehen.', 'الماضي المركّب: bestanden.', 'konjugation', 'bestanden'],
      ['durchfallen', 'fällt durch · fiel durch · ist durchgefallen', 'يرسب', 'Er ist zweimal durchgefallen.', 'Er hat zweimal durchgefallen.', 'durchfallen مع sein.', 'konjugation', 'durchgefallen'],
      ['wiederholen', 'wiederholt · wiederholte · hat wiederholt', 'يعيد', 'Ich muss die Prüfung wiederholen.', 'Ich muss die Prüfung wiederholen es.', 'لا ضمير زائد.', 'wortstellung', 'wiederholen'],
      ['lernen', 'lernt · lernte · hat gelernt', 'يتعلّم', 'Man lernt nie aus.', 'Man lernt nie aus es.', 'لا ضمير زائد.', 'wortstellung', 'lernt'],
      ['lehren', 'lehrt · lehrte · hat gelehrt', 'يدرّس', 'Sie lehrt Deutsch an der Hochschule.', 'Sie lehrt Deutsch in der Hochschule.', 'an لا in.', 'präposition', 'lehrt'],
      ['unterrichten', 'unterrichtet · unterrichtete · hat unterrichtet', 'يدرّس', 'Er unterrichtet Mathematik.', 'Er unterrichtet in Mathematik.', 'بلا حرف جر.', 'kasus', 'unterrichtet'],
      ['die Kenntnis', 'die Kenntnisse', 'المعرفة', 'Seine Kenntnisse sind erstaunlich.', 'Seine Kenntnisse sind erstaunlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Kenntnisse'],
      ['die Fähigkeit', 'die Fähigkeiten', 'القدرة', 'Diese Fähigkeit lernt man früh.', 'Diese Fähigkeit lernt man in früh.', 'بلا حرف جر.', 'präposition', 'Fähigkeit'],
      ['die Begabung', 'die Begabungen', 'الموهبة', 'Sie hat eine Begabung für Sprachen.', 'Sie hat eine Begabung in Sprachen.', 'für لا in.', 'präposition', 'Begabung'],
      ['die Motivation', 'die Motivationen', 'الحافز', 'Motivation ist wichtiger als Talent.', 'Motivation ist wichtiger wie Talent.', 'أفعل: als لا wie.', 'kasus', 'Motivation'],
      ['das Stipendium', 'die Stipendien', 'المنحة الدراسية', 'Er bekommt ein Stipendium.', 'Er bekommt ein Stipendium es.', 'لا ضمير زائد.', 'wortstellung', 'Stipendium'],
      ['die Zulassung', 'die Zulassungen', 'القبول', 'Die Zulassung kam per Post.', 'Die Zulassung kam mit Post.', 'per Post.', 'präposition', 'Zulassung'],
      ['die Anmeldung', 'die Anmeldungen', 'التسجيل', 'Die Anmeldung ist bis Freitag möglich.', 'Die Anmeldung ist bis Freitag möglich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Anmeldung'],
      ['das Semester', 'die Semester', 'الفصل الدراسي', 'Das Semester endet im Februar.', 'Das Semester endet in Februar.', 'im.', 'präposition', 'Semester'],
      ['die Voraussetzung', 'die Voraussetzungen', 'الشرط المسبق', 'Die Voraussetzung ist ein Abschluss.', 'Die Voraussetzung ist ein Abschluss gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Voraussetzung'],
      ['die Bildungspolitik', '—', 'سياسة التعليم', 'Die Bildungspolitik wird diskutiert.', 'Die Bildungspolitik wird diskutieren.', 'المجهول: diskutiert.', 'konjugation', 'Bildungspolitik'],
      ['das Bildungssystem', 'die Bildungssysteme', 'النظام التعليمي', 'Das Bildungssystem ist unterschiedlich.', 'Das Bildungssystem ist unterschiedlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Bildungssystem'],
      ['der Unterricht', '—', 'الدرس', 'Der Unterricht beginnt pünktlich.', 'Der Unterricht beginnt pünktlich es.', 'لا ضمير زائد.', 'wortstellung', 'Unterricht'],
      ['die Hausaufgabe', 'die Hausaufgaben', 'الواجب المنزلي', 'Die Hausaufgaben sind freiwillig.', 'Die Hausaufgaben sind freiwillig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Hausaufgaben']
    ],
    tricks: [
      { trick: 'drei Bildungswege: die Ausbildung · das Studium · die Weiterbildung', wie: 'Die Ausbildung dauert drei Jahre. · Das Studium beginnt im Oktober. · Die Firma zahlt die Weiterbildung.', warum: 'العربية تستعمل «التكوين/الدراسة» بتبادل، والألمانية تفرّق بين المسارات الثلاثة بدقة.', anchor: 'die Ausbildung' },
      { trick: 'النجاح والرسوب: bestehen · durchfallen · wiederholen', wie: 'Ich habe die Prüfung bestanden. · Er ist durchgefallen.', warum: 'بestehen مع haben وdurchfallen مع sein، والعربية لا فرق عندها.', anchor: 'bestehen' },
      { trick: 'أفعال التدريس بلا حرف جر: unterrichten · lehren (an) · lernen', wie: 'Er unterrichtet Mathematik. · Sie lehrt an der Hochschule.', warum: 'العربية تقول «يدرّس في/المادة»، والألمانية تصل الفعل بالمفعول مباشرة.', anchor: 'unterrichten' }
    ]
  },

  'b1-u3-l6': {
    items: [
      ['die Stadt', 'die Städte', 'المدينة', 'Die Stadt wächst schnell.', 'Die Stadt wächst schnell es.', 'لا ضمير زائد.', 'wortstellung', 'Stadt'],
      ['das Dorf', 'die Dörfer', 'القرية', 'Das Dorf liegt im Norden.', 'Das Dorf liegt in Norden.', 'im.', 'präposition', 'Dorf'],
      ['die Gegend', 'die Gegenden', 'المنطقة', 'Die Gegend ist sehr ruhig.', 'Die Gegend ist sehr ruhig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Gegend'],
      ['das Viertel', 'die Viertel', 'الحي', 'Das Viertel ist multikulturell.', 'Das Viertel ist multikulturell gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Viertel'],
      ['der Stadtteil', 'die Stadtteile', 'القسم البلدي', 'Der Stadtteil hat einen Park.', 'Der Stadtteil hat ein Park.', 'مذكر نصب: einen.', 'kasus', 'Stadtteil'],
      ['das Zentrum', 'die Zentren', 'المركز', 'Das Zentrum ist teuer.', 'Das Zentrum ist teuer gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Zentrum'],
      ['der Stadtrand', 'die Stadtränder', 'ضواحي المدينة', 'Am Stadtrand wohnen viele Familien.', 'In Stadtrand wohnen viele Familien.', 'am Stadtrand.', 'präposition', 'Stadtrand'],
      ['die Vorstadt', 'die Vorstädte', 'الضاحية', 'Die Vorstadt wächst rasant.', 'Die Vorstadt wächst rasant es.', 'لا ضمير زائد.', 'wortstellung', 'Vorstadt'],
      ['das Rathaus', 'die Rathäuser', 'البلدية', 'Das Rathaus ist am Marktplatz.', 'Das Rathaus ist in Marktplatz.', 'am.', 'präposition', 'Rathaus'],
      ['die Verwaltung', 'die Verwaltungen', 'الإدارة', 'Die Verwaltung ist umgezogen.', 'Die Verwaltung ist umziehen.', 'الماضي المركّب: umgezogen.', 'konjugation', 'Verwaltung'],
      ['die Infrastruktur', 'die Infrastrukturen', 'البنية التحتية', 'Die Infrastruktur ist gut ausgebaut.', 'Die Infrastruktur ist gut ausbauen.', 'الصفة + Partizip II.', 'konjugation', 'Infrastruktur'],
      ['der Verkehr', '—', 'المرور', 'Der Verkehr ist am Morgen dicht.', 'Der Verkehr ist am Morgen dicht gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Verkehr'],
      ['die Verkehrsmittel', '—', 'وسائل النقل', 'Die Verkehrsmittel sind günstig.', 'Die Verkehrsmittel sind günstig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Verkehrsmittel'],
      ['der Bus', 'die Busse', 'الحافلة', 'Der Bus fährt alle zehn Minuten.', 'Der Bus fährt in alle zehn Minuten.', 'بلا حرف جر.', 'präposition', 'Bus'],
      ['die Straßenbahn', 'die Straßenbahnen', 'الترامواي', 'Die Straßenbahn hält hier nicht.', 'Die Straßenbahn hält hier nicht es.', 'لا ضمير زائد.', 'wortstellung', 'Straßenbahn'],
      ['die U-Bahn', 'die U-Bahnen', 'مترو الأنفاق', 'Die U-Bahn ist schneller.', 'Die U-Bahn ist schneller es.', 'لا ضمير زائد.', 'wortstellung', 'U-Bahn'],
      ['der Bahnhof', 'die Bahnhöfe', 'محطة القطار', 'Der Bahnhof wird modernisiert.', 'Der Bahnhof wird modernisieren.', 'المجهول: modernisiert.', 'konjugation', 'Bahnhof'],
      ['der Flughafen', 'die Flughäfen', 'المطار', 'Der Flughafen liegt weit weg.', 'Der Flughafen liegt weit es.', 'الصفة تكفي.', 'lexik-kollokation', 'Flughafen'],
      ['die Haltestelle', 'die Haltestellen', 'الموقف', 'Die Haltestelle ist gleich dort.', 'Die Haltestelle ist gleich dort es.', 'لا ضمير زائد.', 'wortstellung', 'Haltestelle'],
      ['der Fahrplan', 'die Fahrpläne', 'جدول المواعيد', 'Der Fahrplan hat sich geändert.', 'Der Fahrplan hat geändert.', 'الانعكاس: sich geändert.', 'konjugation', 'Fahrplan'],
      ['die Fahrkarte', 'die Fahrkarten', 'تذكرة السفر', 'Die Fahrkarte gilt zwei Stunden.', 'Die Fahrkarte gilt für zwei Stunden.', 'بلا حرف جر.', 'präposition', 'Fahrkarte'],
      ['der Mietpreis', 'die Mietpreise', 'سعر الإيجار', 'Die Mietpreise steigen stark.', 'Die Mietpreise steigen stark es.', 'لا ضمير زائد.', 'wortstellung', 'Mietpreise'],
      ['die Miete', 'die Mieten', 'الإيجار', 'Die Miete frisst mein Gehalt.', 'Die Miete frisst mein Gehalt es.', 'لا ضمير زائد.', 'wortstellung', 'Miete'],
      ['der Wohnraum', '—', 'المسكن', 'Wohnraum ist knapp.', 'Wohnraum ist knapp gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Wohnraum'],
      ['die Wohnung', 'die Wohnungen', 'الشقة', 'Die Wohnung ist zu teuer.', 'Die Wohnung ist zu teuer gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Wohnung'],
      ['der Vermieter', 'die Vermieter', 'المالك المؤجّر', 'Der Vermieter erhöht die Miete.', 'Der Vermieter erhöht die Miete es.', 'لا ضمير زائد.', 'wortstellung', 'Vermieter'],
      ['der Mieter', 'die Mieter', 'المستأجر', 'Die Mieter protestieren.', 'Die Mieter protestieren es.', 'لا ضمير زائد.', 'wortstellung', 'Mieter'],
      ['der Platz', 'die Plätze', 'الساحة/المكان', 'Der Platz ist voll.', 'Der Platz ist voll gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Platz'],
      ['die Grünfläche', 'die Grünflächen', 'المساحة الخضراء', 'Die Grünflächen sind wichtig.', 'Die Grünflächen sind wichtig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Grünflächen'],
      ['der Park', 'die Parks', 'الحديقة العامة', 'Der Park ist abends belebt.', 'Der Park ist abends belebt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Park'],
      ['der Spielplatz', 'die Spielplätze', 'ملعب الأطفال', 'Der Spielplatz braucht Reparaturen.', 'Der Spielplatz braucht Reparaturen es.', 'لا ضمير زائد.', 'wortstellung', 'Spielplatz'],
      ['die Nachbarschaft', 'die Nachbarschaften', 'الحي والجوار', 'Die Nachbarschaft hilft einander.', 'Die Nachbarschaft hilft einander es.', 'لا ضمير زائد.', 'wortstellung', 'Nachbarschaft'],
      ['die Sicherheit', '—', 'الأمن', 'Die Sicherheit ist nachts ein Thema.', 'Die Sicherheit ist nachts ein Thema gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Sicherheit'],
      ['die Kriminalität', '—', 'الجريمة', 'Die Kriminalität ist gesunken.', 'Die Kriminalität ist sinken.', 'الماضي المركّب: gesunken.', 'konjugation', 'Kriminalität'],
      ['die Umwelt', '—', 'البيئة', 'Die Umwelt leidet unter dem Verkehr.', 'Die Umwelt leidet für den Verkehr.', 'leiden unter.', 'präposition', 'Umwelt'],
      ['die Lebensqualität', '—', 'جودة الحياة', 'Die Lebensqualität ist gestiegen.', 'Die Lebensqualität ist steigen.', 'الماضي المركّب: gestiegen.', 'konjugation', 'Lebensqualität'],
      ['die Einwohner', '—', 'السكان', 'Die Einwohner der Stadt wachsen langsam.', 'Die Einwohner der Stadt wachsen langsam es.', 'لا ضمير زائد.', 'wortstellung', 'Einwohner'],
      ['umziehen', 'zieht um · zog um · ist umgezogen', 'ينتقل للسكن', 'Wir sind letztes Jahr umgezogen.', 'Wir haben letztes Jahr umgezogen.', 'umziehen مع sein.', 'konjugation', 'umgezogen'],
      ['sich anpassen', 'passt sich an · passte sich an · hat sich angepasst', 'يتكيّف', 'Ich habe mich schnell angepasst.', 'Ich habe mich schnell angepasst an.', 'الضمير sich أمر لازم.', 'konjugation', 'angepasst'],
      ['die Miete erhöhen', 'erhöht · erhöhte · hat erhöht', 'يرفع الإيجار', 'Der Vermieter will die Miete erhöhen.', 'Der Vermieter will die Miete erhöhen es.', 'لا ضمير زائد.', 'wortstellung', 'erhöhen']
    ],
    tricks: [
      { trick: 'المدينة تنقسم إلى: das Zentrum · der Stadtteil · das Viertel · der Stadtrand · die Vorstadt', wie: 'Im Zentrum ist es teuer, am Stadtrand ruhiger.', warum: 'العربية تقول «الوسط/الضاحية» بلا تمييز دقيق، والألمانية تعطي كل طبقة اسمها.', anchor: 'das Zentrum' },
      { trick: 'النقل: die Verkehrsmittel · der Fahrplan · die Haltestelle — وتُختصر: U-Bahn · S-Bahn', wie: 'Die U-Bahn ist schneller als der Bus. · Der Fahrplan hat sich geändert.', warum: 'الاختصارات والشرطة (-) جزء من الاسم وتُنسى في الكتابة العربية.', anchor: 'die U-Bahn' },
      { trick: 'الشكوى الحضرية: die Miete · der Wohnraum · die Grünfläche · die Lebensqualität', wie: 'Die Mietpreise steigen, aber die Lebensqualität sinkt.', warum: 'نصوص B1 عن السكن تُبنى على هذه الأسماء، والعربية تسرد السعر لا المصطلح.', anchor: 'der Mietpreis' }
    ]
  }

};
