/* Deutschweg — B1 lexical layer, unit 2 (part a): b1-u2-l1 … b1-u2-l3.
   40 items per lesson, the count the B1 rows declare (amendment B1-L1).
   Not wired yet — see the header of vocab-b1-u1a.js for why and how. */

module.exports = {

  'b1-u2-l1': {
    items: [
      ['werden', 'wird · wurde · ist geworden', 'سوف (المستقبل)', 'Morgen wird es regnen.', 'Morgen es wird regnen.', 'الفعل ثانٍ بعد الظرف.', 'wortstellung', 'wird'],
      ['die Zukunft', 'die Zukünfte', 'المستقبل', 'In der Zukunft arbeiten wir anders.', 'In die Zukunft arbeiten wir anders.', 'in + داتيف: der.', 'kasus', 'Zukunft'],
      ['die Prognose', 'die Prognosen', 'التوقّع', 'Die Prognose ist unsicher.', 'Die Prognose ist unsicher gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Prognose'],
      ['die Vorhersage', 'die Vorhersagen', 'التنبؤ', 'Die Vorhersage für morgen ist gut.', 'Die Vorhersage zu morgen ist gut.', 'für لا zu.', 'präposition', 'Vorhersage'],
      ['der Fortschritt', 'die Fortschritte', 'التقدّم', 'Der Fortschritt ist deutlich.', 'Der Fortschritt ist deutlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Fortschritt'],
      ['die Technik', 'die Techniken', 'التقنية', 'Die Technik hilft uns täglich.', 'Die Technik hilft uns täglich es.', 'لا ضمير زائد.', 'wortstellung', 'Technik'],
      ['die Technologie', 'die Technologien', 'التكنولوجيا', 'Neue Technologien verändern die Arbeit.', 'Neue Technologien verändern die Arbeit es.', 'لا ضمير زائد.', 'wortstellung', 'Technologien'],
      ['die Wissenschaft', 'die Wissenschaften', 'العلم', 'Die Wissenschaft sucht Antworten.', 'Die Wissenschaft sucht für Antworten.', 'بلا حرف جر.', 'kasus', 'Wissenschaft'],
      ['die Forschung', 'die Forschungen', 'البحث العلمي', 'Die Forschung kostet viel Geld.', 'Die Forschung kostet viel Gelder.', 'Geld بلا جمع.', 'plural', 'Forschung'],
      ['der Trend', 'die Trends', 'الاتجاه العام', 'Der Trend geht nach oben.', 'Der Trend geht zu oben.', 'nach oben.', 'präposition', 'Trend'],
      ['die Tendenz', 'die Tendenzen', 'النزعة', 'Die Tendenz ist steigend.', 'Die Tendenz ist steigend gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Tendenz'],
      ['die Statistik', 'die Statistiken', 'الإحصاء', 'Die Statistik zeigt einen Anstieg.', 'Die Statistik zeigt ein Anstieg.', 'مذكر نصب: einen.', 'kasus', 'Statistik'],
      ['die Zahl', 'die Zahlen', 'الرقم', 'Die Zahlen steigen jedes Jahr.', 'Die Zahlen steigen in jedes Jahr.', 'بلا حرف جر.', 'präposition', 'Zahlen'],
      ['der Anteil', 'die Anteile', 'النصيب', 'Der Anteil der Frauen steigt.', 'Der Anteil von den Frauen steigt.', 'Genitiv أفضل: der Frauen.', 'kasus', 'Anteil'],
      ['das Wachstum', '—', 'النمو', 'Das Wachstum ist langsam.', 'Das Wachstum ist langsam gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Wachstum'],
      ['der Rückgang', 'die Rückgänge', 'التراجع', 'Der Rückgang betrifft alle Branchen.', 'Der Rückgang betrifft alle Branche.', 'الجمع: Branchen.', 'plural', 'Rückgang'],
      ['der Anstieg', 'die Anstiege', 'الارتفاع', 'Der Anstieg der Preise ist deutlich.', 'Der Anstieg von den Preisen ist deutlich.', 'Genitiv أفضل.', 'kasus', 'Anstieg'],
      ['die Bevölkerung', 'die Bevölkerungen', 'السكان', 'Die Bevölkerung wächst langsam.', 'Die Bevölkerung wächst langsam es.', 'لا ضمير زائد.', 'wortstellung', 'Bevölkerung'],
      ['die Generation', 'die Generationen', 'الجيل', 'Diese Generation denkt anders.', 'Diese Generation denkt anders es.', 'لا ضمير زائد.', 'wortstellung', 'Generation'],
      ['die Rente', 'die Renten', 'المعاش', 'Er bekommt später eine kleine Rente.', 'Er bekommt später ein kleine Rente.', 'مؤنث: eine.', 'genus', 'Rente'],
      ['das Einkommen', 'die Einkommen', 'الدخل', 'Das Einkommen der Familie sinkt.', 'Das Einkommen von der Familie sinkt.', 'Genitiv أفضل.', 'kasus', 'Einkommen'],
      ['der Arbeitsplatz', 'die Arbeitsplätze', 'مكان العمل', 'Viele Arbeitsplätze werden verschwinden.', 'Viele Arbeitsplätze werden verschwinden es.', 'لا ضمير زائد.', 'wortstellung', 'Arbeitsplätze'],
      ['die Digitalisierung', '—', 'الرقمنة', 'Die Digitalisierung verändert alles.', 'Die Digitalisierung verändert alles es.', 'لا ضمير زائد.', 'wortstellung', 'Digitalisierung'],
      ['die Automatisierung', '—', 'الأتمتة', 'Die Automatisierung nimmt zu.', 'Die Automatisierung nimmt zu es.', 'لا ضمير زائد.', 'wortstellung', 'Automatisierung'],
      ['der Roboter', 'die Roboter', 'الروبوت', 'Der Roboter erledigt die Arbeit.', 'Der Roboter erledigt die Arbeit es.', 'لا ضمير زائد.', 'wortstellung', 'Roboter'],
      ['die Maschine', 'die Maschinen', 'الآلة', 'Die Maschine läuft die ganze Nacht.', 'Die Maschine läuft die ganze Nacht es.', 'لا ضمير زائد.', 'wortstellung', 'Maschine'],
      ['der Klimawandel', '—', 'تغيّر المناخ', 'Der Klimawandel betrifft alle Länder.', 'Der Klimawandel betrifft alle Länder es.', 'لا ضمير زائد.', 'wortstellung', 'Klimawandel'],
      ['die Energie', 'die Energien', 'الطاقة', 'Wir brauchen saubere Energie.', 'Wir brauchen sauber Energie.', 'الصفة: saubere.', 'deklination', 'Energie'],
      ['die Solarenergie', '—', 'الطاقة الشمسية', 'Die Solarenergie ist billiger geworden.', 'Die Solarenergie ist billiger geworden es.', 'لا ضمير زائد.', 'wortstellung', 'Solarenergie'],
      ['das Elektroauto', 'die Elektroautos', 'السيارة الكهربائية', 'Das Elektroauto fährt leise.', 'Das Elektroauto fährt leise es.', 'لا ضمير زائد.', 'wortstellung', 'Elektroauto'],
      ['die Batterie', 'die Batterien', 'البطارية', 'Die Batterie hält lange.', 'Die Batterie hält lange es.', 'لا ضمير زائد.', 'wortstellung', 'Batterie'],
      ['die Erfindung', 'die Erfindungen', 'الاختراع', 'Diese Erfindung veränderte die Welt.', 'Diese Erfindung hat die Welt verändert gehabt.', 'الماضي البسيط: veränderte.', 'konjugation', 'Erfindung'],
      ['der Erfinder', 'die Erfinder', 'المخترع', 'Der Erfinder wurde berühmt.', 'Der Erfinder wurde berühmt gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Erfinder'],
      ['die Erwartung', 'die Erwartungen', 'التوقع', 'Die Erwartungen sind hoch.', 'Die Erwartungen sind hoch gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Erwartungen'],
      ['die Aussicht', 'die Aussichten', 'الاحتمال/المنظر', 'Die Aussichten sind gut.', 'Die Aussichten sind gut gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Aussichten'],
      ['die Unsicherheit', 'die Unsicherheiten', 'اللايقين', 'Die Unsicherheit bleibt groß.', 'Die Unsicherheit bleibt groß gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Unsicherheit'],
      ['die Sicherheit', 'die Sicherheiten', 'الأمان', 'Die Sicherheit hat Priorität.', 'Die Sicherheit hat Priorität es.', 'لا ضمير زائد.', 'wortstellung', 'Sicherheit'],
      ['der Wandel', '—', 'التحوّل', 'Der Wandel braucht Zeit.', 'Der Wandel braucht eine Zeit.', 'Zeit بلا أداة هنا.', 'lexik-kollokation', 'Wandel'],
      ['die Welt', 'die Welten', 'العالم', 'Die Welt wird digitaler.', 'Die Welt wird digitaler es.', 'لا ضمير زائد.', 'wortstellung', 'Welt'],
      ['die Natur', 'die Naturen', 'الطبيعة', 'Die Natur braucht Schutz.', 'Die Natur braucht ein Schutz.', 'Schutz بلا أداة.', 'lexik-kollokation', 'Natur']
    ],
    tricks: [
      { trick: 'المستقبل: werden + مصدر، والحاضر يكفي مع ظرف زمني', wie: 'Morgen wird es regnen. · Morgen regnet es.', warum: 'العربية تفرّق بـ«سوف»، والألمانية تقبل المضارع مع «غدًا» فتصير werden زائدة.', anchor: 'werden' },
      { trick: 'الإحصاء يقرأ بالأسماء: der Anstieg · der Rückgang · der Anteil', wie: 'Der Anteil der Frauen steigt. · Der Rückgang betrifft alle.', warum: 'نصوص B1 الرقمية تُبنى على هذه الأسماء، والعربية تشرح بالفعل.', anchor: 'der Anteil' },
      { trick: 'التوقع حذرًا: dürfte · wahrscheinlich · vermutlich', wie: 'Es dürfte morgen regnen. · Vermutlich kommt er später.', warum: 'العربية تقول «قد» أو «ربما»، والألمانية تستعمل dürfte للترجيح الرصين.', anchor: 'dürfte' }
    ]
  },

  'b1-u2-l2': {
    items: [
      ['gab', 'geben · gibt', 'أعطى (ماضٍ بسيط)', 'Er gab mir das Buch zurück.', 'Er hat mir das Buch zurückgegeben gestern.', 'في السرد: gab لا hat gegeben.', 'konjugation', 'gab'],
      ['ging', 'gehen · geht', 'ذهب', 'Sie ging langsam nach Hause.', 'Sie hat langsam nach Hause gegangen.', 'السرد: ging.', 'konjugation', 'ging'],
      ['kam', 'kommen · kommt', 'جاء', 'Er kam zu spät zur Arbeit.', 'Er hat zu spät zur Arbeit gekommen.', 'السرد: kam.', 'konjugation', 'kam'],
      ['sah', 'sehen · sieht', 'رأى', 'Ich sah ihn am Bahnhof.', 'Ich habe ihn am Bahnhof gesehen damals.', 'السرد: sah.', 'konjugation', 'sah'],
      ['nahm', 'nehmen · nimmt', 'أخذ', 'Sie nahm den Zug nach Berlin.', 'Sie hat den Zug nach Berlin genommen.', 'السرد: nahm.', 'konjugation', 'nahm'],
      ['sprach', 'sprechen · spricht', 'تحدّث', 'Er sprach leise mit dem Arzt.', 'Er hat leise mit dem Arzt gesprochen.', 'السرد: sprach.', 'konjugation', 'sprach'],
      ['fand', 'finden · findet', 'وجد', 'Ich fand die Lösung schnell.', 'Ich habe die Lösung schnell gefunden gehabt.', 'السرد: fand.', 'konjugation', 'fand'],
      ['blieb', 'bleiben · bleibt', 'بقي', 'Sie blieb drei Wochen in Tunis.', 'Sie hat drei Wochen in Tunis geblieben.', 'السرد: blieb.', 'konjugation', 'blieb'],
      ['hieß', 'heißen · heißt', 'كان اسمه', 'Der Ort hieß früher anders.', 'Der Ort hat früher anders geheißen.', 'السرد: hieß.', 'konjugation', 'hieß'],
      ['bat', 'bitten · bittet', 'طلب', 'Er bat mich um Hilfe.', 'Er hat mich um Hilfe gebeten gehabt.', 'السرد: bat.', 'konjugation', 'bat'],
      ['rief', 'rufen · ruft', 'نادى', 'Sie rief ihren Bruder an.', 'Sie hat ihren Bruder angerufen gehabt.', 'السرد: rief an.', 'konjugation', 'rief'],
      ['hielt', 'halten · hält', 'أمسك/توقّف', 'Der Zug hielt an jeder Station.', 'Der Zug hat an jeder Station gehalten.', 'السرد: hielt.', 'konjugation', 'hielt'],
      ['lag', 'liegen · liegt', 'كان ملقًى/واقعًا', 'Das Dorf lag am Meer.', 'Das Dorf hat am Meer gelegen.', 'السرد: lag.', 'konjugation', 'lag'],
      ['stand', 'stehen · steht', 'كان واقفًا', 'Vor der Tür stand ein Mann.', 'Vor der Tür hat ein Mann gestanden.', 'السرد: stand.', 'konjugation', 'stand'],
      ['trat', 'treten · tritt', 'خطا/دخل', 'Er trat leise ins Zimmer.', 'Er hat leise ins Zimmer getreten.', 'السرد: trat.', 'konjugation', 'trat'],
      ['trug', 'tragen · trägt', 'حمل', 'Sie trug einen roten Mantel.', 'Sie hat einen roten Mantel getragen.', 'السرد: trug.', 'konjugation', 'trug'],
      ['wusste', 'wissen · weiß', 'عرف', 'Niemand wusste die Antwort.', 'Niemand hat die Antwort gewusst.', 'السرد: wusste.', 'konjugation', 'wusste'],
      ['konnte', 'können · kann', 'استطاع', 'Er konnte nicht schlafen.', 'Er hat nicht schlafen gekonnt.', 'السرد: konnte.', 'konjugation', 'konnte'],
      ['musste', 'müssen · muss', 'اضطرّ', 'Ich musste lange warten.', 'Ich habe lange warten gemusst.', 'السرد: musste.', 'konjugation', 'musste'],
      ['durfte', 'dürfen · darf', 'سُمح له', 'Sie durfte mitkommen.', 'Sie hat mitkommen gedurft.', 'السرد: durfte.', 'konjugation', 'durfte'],
      ['begann', 'beginnen · beginnt', 'بدأ', 'Der Film begann um acht.', 'Der Film hat um acht begonnen.', 'السرد: begann.', 'konjugation', 'begann'],
      ['endete', 'enden · endet', 'انتهى', 'Die Reise endete in Sfax.', 'Die Reise hat in Sfax geendet.', 'السرد: endete.', 'konjugation', 'endete'],
      ['dauerte', 'dauern · dauert', 'استمر', 'Der Sturm dauerte zwei Tage.', 'Der Sturm hat zwei Tage gedauert.', 'السرد: dauerte.', 'konjugation', 'dauerte'],
      ['geschah', 'geschehen · geschieht', 'حدث', 'Was geschah danach?', 'Was hat danach geschehen?', 'السرد: geschah.', 'konjugation', 'geschah'],
      ['ereignete sich', 'ereignet sich · ereignete sich · hat sich ereignet', 'وقع', 'Der Unfall ereignete sich am Abend.', 'Der Unfall hat sich am Abend ereignet gehabt.', 'السرد: ereignete sich.', 'konjugation', 'ereignete'],
      ['der Anfang', 'die Anfänge', 'البداية', 'Am Anfang war alles neu.', 'In Anfang war alles neu.', 'في البداية: am Anfang.', 'präposition', 'Anfang'],
      ['das Ende', 'die Enden', 'النهاية', 'Am Ende siegte die Vernunft.', 'In Ende siegte die Vernunft.', 'في النهاية: am Ende.', 'präposition', 'Ende'],
      ['der Höhepunkt', 'die Höhepunkte', 'الذروة', 'Der Höhepunkt der Geschichte kommt spät.', 'Der Höhepunkt von der Geschichte kommt spät.', 'Genitiv أفضل.', 'kasus', 'Höhepunkt'],
      ['die Handlung', 'die Handlungen', 'الحبكة', 'Die Handlung spielt in Berlin.', 'Die Handlung spielt in Berlin es.', 'لا ضمير زائد.', 'wortstellung', 'Handlung'],
      ['die Figur', 'die Figuren', 'الشخصية', 'Die Figuren wirken lebendig.', 'Die Figuren wirken lebendig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Figuren'],
      ['der Held', 'die Helden', 'البطل', 'Der Held der Geschichte ist ein Kind.', 'Der Held von der Geschichte ist ein Kind.', 'Genitiv أفضل.', 'kasus', 'Held'],
      ['die Erzählung', 'die Erzählungen', 'الحكاية', 'Die Erzählung beginnt mit einem Brief.', 'Die Erzählung beginnt mit ein Brief.', 'mit + داتيف: einem.', 'kasus', 'Erzählung'],
      ['der Roman', 'die Romane', 'الرواية', 'Der Roman wurde schnell bekannt.', 'Der Roman wurde schnell bekannt gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Roman'],
      ['der Autor', 'die Autoren', 'المؤلف', 'Der Autor lebt in Hamburg.', 'Der Autor lebt in Hamburg es.', 'لا ضمير زائد.', 'wortstellung', 'Autor'],
      ['die Szene', 'die Szenen', 'المشهد', 'Diese Szene ist besonders stark.', 'Diese Szene ist besonders stark gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Szene'],
      ['die Spannung', 'die Spannungen', 'التشويق', 'Die Spannung steigt bis zum Ende.', 'Die Spannung steigt bis zu das Ende.', 'bis zum.', 'präposition', 'Spannung'],
      ['der Konflikt', 'die Konflikte', 'الصراع', 'Der Konflikt löst sich am Ende.', 'Der Konflikt löst sich in Ende.', 'am Ende.', 'präposition', 'Konflikt'],
      ['die Moral', '—', 'العبرة', 'Die Moral der Geschichte ist klar.', 'Die Moral von der Geschichte ist klar.', 'Genitiv أفضل.', 'kasus', 'Moral'],
      ['der Erzähler', 'die Erzähler', 'الراوي', 'Der Erzähler bleibt unsichtbar.', 'Der Erzähler bleibt unsichtbar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Erzähler'],
      ['das Kapitel', 'die Kapitel', 'الفصل', 'Das erste Kapitel ist kurz.', 'Das erste Kapitel ist kurz es.', 'لا ضمير زائد.', 'wortstellung', 'Kapitel']
    ],
    tricks: [
      { trick: 'في السرد تُستعمل Präteritum لدوافع الأفعال: ging · kam · sah · fand', wie: 'Er kam an, sah sie und blieb stehen.', warum: 'العربية تحكي بالماضي المركّب نفسه، والألمانية تكتب السرد بـ Präteritum.', anchor: 'ging' },
      { trick: 'الأفعال المساعدة والمشروطة في السرد بلا ge-: konnte · musste · durfte · wusste', wie: 'Er konnte nicht kommen. · Wir mussten warten.', warum: 'لا Partizip II في السرد، والناطق العربي يبني «hat gekonnt» فيخطئ.', anchor: 'konnte' },
      { trick: 'بناء الحكاية: am Anfang · dann · plötzlich · am Ende', wie: 'Am Anfang war alles neu, dann geschah etwas, am Ende siegte die Vernunft.', warum: 'علامات التسلسل تُنقل من العربية كلمةً كلمة فتفقد موضعها الألماني.', anchor: 'der Anfang' }
    ]
  },

  'b1-u2-l3': {
    items: [
      ['der Besitzer', 'die Besitzer', 'المالك', 'Der Besitzer des Hauses wohnt in Berlin.', 'Der Besitzer von dem Haus wohnt in Berlin.', 'Genitiv أفضل: des Hauses.', 'kasus', 'Besitzer'],
      ['der Eigentümer', 'die Eigentümer', 'صاحب الملك', 'Der Eigentümer der Wohnung ist unbekannt.', 'Der Eigentümer von der Wohnung ist unbekannt.', 'Genitiv أفضل.', 'kasus', 'Eigentümer'],
      ['die Bedeutung', 'die Bedeutungen', 'المعنى', 'Die Bedeutung des Wortes ist wichtig.', 'Die Bedeutung von dem Wort ist wichtig.', 'Genitiv أفضل.', 'kasus', 'Bedeutung'],
      ['der Wert', 'die Werte', 'القيمة', 'Der Wert der Immobilie steigt.', 'Der Wert von der Immobilie steigt.', 'Genitiv أفضل.', 'kasus', 'Wert'],
      ['die Qualität', 'die Qualitäten', 'الجودة', 'Die Qualität der Ware ist gut.', 'Die Qualität von der Ware ist gut.', 'Genitiv أفضل.', 'kasus', 'Qualität'],
      ['die Menge', 'die Mengen', 'الكمية', 'Die Menge des Wassers reicht nicht.', 'Die Menge von dem Wasser reicht nicht.', 'Genitiv أفضل.', 'kasus', 'Menge'],
      ['die Hälfte', 'die Hälften', 'النصف', 'Die Hälfte der Arbeit ist fertig.', 'Die Hälfte von der Arbeit ist fertig.', 'Genitiv أفضل.', 'kasus', 'Hälfte'],
      ['das Drittel', 'die Drittel', 'الثلث', 'Ein Drittel der Schüler fehlt.', 'Ein Drittel von den Schülern fehlt.', 'Genitiv أفضل.', 'kasus', 'Drittel'],
      ['der Teil', 'die Teile', 'الجزء', 'Der größte Teil der Zeit ist verloren.', 'Der größte Teil von der Zeit ist verloren.', 'Genitiv أفضل.', 'kasus', 'Teil'],
      ['die Mehrheit', 'die Mehrheiten', 'الأغلبية', 'Die Mehrheit der Bürger stimmt zu.', 'Die Mehrheit von den Bürgern stimmt zu.', 'Genitiv أفضل.', 'kasus', 'Mehrheit'],
      ['die Minderheit', 'die Minderheiten', 'الأقلية', 'Eine Minderheit der Abgeordneten lehnt ab.', 'Eine Minderheit von den Abgeordneten lehnt ab.', 'Genitiv أفضل.', 'kasus', 'Minderheit'],
      ['der Rest', 'die Reste', 'الباقي', 'Der Rest des Geldes bleibt hier.', 'Der Rest von dem Geld bleibt hier.', 'Genitiv أفضل.', 'kasus', 'Rest'],
      ['die Summe', 'die Summen', 'المجموع', 'Die Summe der Kosten ist hoch.', 'Die Summe von den Kosten ist hoch.', 'Genitiv أفضل.', 'kasus', 'Summe'],
      ['der Preis', 'die Preise', 'الثمن', 'Der Preis des Autos ist gefallen.', 'Der Preis von dem Auto ist gefallen.', 'Genitiv أفضل.', 'kasus', 'Preis'],
      ['die Kosten', '—', 'التكاليف', 'Die Kosten des Umzugs sind hoch.', 'Die Kosten von dem Umzug sind hoch.', 'Genitiv أفضل.', 'kasus', 'Kosten'],
      ['der Gewinn', 'die Gewinne', 'الربح', 'Der Gewinn der Firma sinkt.', 'Der Gewinn von der Firma sinkt.', 'Genitiv أفضل.', 'kasus', 'Gewinn'],
      ['der Verlust', 'die Verluste', 'الخسارة', 'Der Verlust des Arbeitsplatzes ist schwer.', 'Der Verlust von dem Arbeitsplatz ist schwer.', 'Genitiv أفضل.', 'kasus', 'Verlust'],
      ['die Schulden', '—', 'الديون', 'Die Schulden des Landes wachsen.', 'Die Schulden von dem Land wachsen.', 'Genitiv أفضل.', 'kasus', 'Schulden'],
      ['das Eigentum', '—', 'الملكية', 'Das Eigentum des Staates ist geschützt.', 'Das Eigentum von dem Staat ist geschützt.', 'Genitiv أفضل.', 'kasus', 'Eigentum'],
      ['der Beginn', '—', 'البداية', 'Der Beginn des Kurses ist im Oktober.', 'Der Beginn von dem Kurs ist im Oktober.', 'Genitiv أفضل.', 'kasus', 'Beginn'],
      ['die Mitte', 'die Mitten', 'الوسط', 'In der Mitte des Raumes steht ein Tisch.', 'In die Mitte des Raumes steht ein Tisch.', 'in + داتيف: der.', 'kasus', 'Mitte'],
      ['die Nähe', '—', 'القرب', 'In der Nähe des Bahnhofs gibt es Cafés.', 'In der Nähe von dem Bahnhof gibt es Cafés.', 'Genitiv أفضل.', 'kasus', 'Nähe'],
      ['die Ferne', '—', 'البعد', 'In der Ferne sah man Berge.', 'In die Ferne sah man Berge.', 'in + داتيف: der.', 'kasus', 'Ferne'],
      ['die Grenze', 'die Grenzen', 'الحدّ', 'Die Grenze des Landes ist geschlossen.', 'Die Grenze von dem Land ist geschlossen.', 'Genitiv أفضل.', 'kasus', 'Grenze'],
      ['der Rand', 'die Ränder', 'الحافة', 'Am Rand des Weges stehen Bäume.', 'Am Rand von dem Weg stehen Bäume.', 'Genitiv أفضل.', 'kasus', 'Rand'],
      ['die Seite', 'die Seiten', 'الصفحة/الجهة', 'Auf der linken Seite des Bildes steht ein Haus.', 'Auf die linke Seite des Bildes steht ein Haus.', 'الوضع الثابت: auf der.', 'kasus', 'Seite'],
      ['die Richtung', 'die Richtungen', 'الاتجاه', 'In Richtung des Zentrums fährt ein Bus.', 'In die Richtung des Zentrums fährt ein Bus.', 'التركيب الثابت: in Richtung.', 'kasus', 'Richtung'],
      ['der Zweck', 'die Zwecke', 'الغرض', 'Der Zweck des Treffens ist ein Austausch.', 'Der Zweck von dem Treffen ist ein Austausch.', 'Genitiv أفضل.', 'kasus', 'Zweck'],
      ['die Ursache', 'die Ursachen', 'السبب', 'Die Ursache des Problems liegt im Plan.', 'Die Ursache von dem Problem liegt im Plan.', 'Genitiv أفضل.', 'kasus', 'Ursache'],
      ['die Folge', 'die Folgen', 'النتيجة', 'Die Folge des Fehlers war ein Streit.', 'Die Folge von dem Fehler war ein Streit.', 'Genitiv أفضل.', 'kasus', 'Folge'],
      ['die Absicht', 'die Absichten', 'القصد', 'Die Absicht des Autors ist klar.', 'Die Absicht von dem Autor ist klar.', 'Genitiv أفضل.', 'kasus', 'Absicht'],
      ['der Grund', 'die Gründe', 'السبب', 'Der Grund des Streits war Geld.', 'Der Grund von dem Streit war Geld.', 'Genitiv أفضل.', 'kasus', 'Grund'],
      ['das Ziel', 'die Ziele', 'الهدف', 'Das Ziel des Projekts ist klar.', 'Das Ziel von dem Projekt ist klar.', 'Genitiv أفضل.', 'kasus', 'Ziel'],
      ['die Meinung', 'die Meinungen', 'الرأي', 'Die Meinung der Mehrheit zählt.', 'Die Meinung von der Mehrheit zählt.', 'Genitiv أفضل.', 'kasus', 'Meinung'],
      ['die Aufgabe', 'die Aufgaben', 'المهمة', 'Die Aufgabe der Gruppe ist schwer.', 'Die Aufgabe von der Gruppe ist schwer.', 'Genitiv أفضل.', 'kasus', 'Aufgabe'],
      ['das Ergebnis', 'die Ergebnisse', 'النتيجة', 'Das Ergebnis der Prüfung kommt per Post.', 'Das Ergebnis von der Prüfung kommt per Post.', 'Genitiv أفضل.', 'kasus', 'Ergebnis'],
      ['die Entscheidung', 'die Entscheidungen', 'القرار', 'Die Entscheidung des Gerichts ist endgültig.', 'Die Entscheidung von dem Gericht ist endgültig.', 'Genitiv أفضل.', 'kasus', 'Entscheidung'],
      ['die Entwicklung', 'die Entwicklungen', 'التطور', 'Die Entwicklung der Stadt ist schnell.', 'Die Entwicklung von der Stadt ist schnell.', 'Genitiv أفضل.', 'kasus', 'Entwicklung'],
      ['die Verantwortung', 'die Verantwortungen', 'المسؤولية', 'Die Verantwortung des Chefs ist groß.', 'Die Verantwortung von dem Chef ist groß.', 'Genitiv أفضل.', 'kasus', 'Verantwortung'],
      ['der Vorteil', 'die Vorteile', 'الميزة', 'Der Vorteil des Angebots ist der Preis.', 'Der Vorteil von dem Angebot ist der Preis.', 'Genitiv أفضل.', 'kasus', 'Vorteil']
    ],
    tricks: [
      { trick: 'المضاف إليه أفضل من von + داتيف في الأسلوب الرفيع', wie: 'Die Bedeutung des Wortes … · Der Preis des Autos …', warum: 'العربية تضيف بلا علامة، والألمانية تطلب إما Genitiv أو von — والأول أفصح في الكتابة.', anchor: 'der Besitzer' },
      { trick: 'علامة المضاف إليه: des/der — وتظهر على الموصوف أولًا', wie: 'der Preis des Autos · die Farbe der Wand · das Ende des Films', warum: 'الحالة تُقاس بالسؤال عن الوسط بين كلمتين، وهي أول ما يُختبر في B1 الكتابي.', anchor: 'die Bedeutung' },
      { trick: 'أسماء الكم: die Hälfte · ein Drittel · die Mehrheit + Genitiv', wie: 'Die Hälfte der Arbeit ist fertig. · Ein Drittel der Schüler fehlt.', warum: 'الكم في العربية يتبعه «من»، والألمانية تحذفها وتضع المضاف إليه.', anchor: 'die Hälfte' }
    ]
  }

};
