/* Deutschweg — B1 lexical layer, unit 8 (part c): b1-u8-l5 · b1-u8-l6. */

module.exports = {

  'b1-u8-l5': {
    items: [
      ['die Änderung', 'die Änderungen', 'التغيير', 'Die Änderung betrifft alle Mieter.', 'Die Änderung betreffen alle Mieter.', 'الفعل مفرد: betrifft.', 'konjugation', 'Änderung'],
      ['die Aushilfe', 'die Aushilfen', 'المساعد المؤقت', 'Als Aushilfe arbeitet sie im Sommer.', 'Als Aushilfe arbeiten sie im Sommer.', 'الفعل مفرد: arbeitet.', 'konjugation', 'Aushilfe'],
      ['beruflich', '—', 'مهني', 'Beruflich geht es ihm gut.', 'Beruflich geht es ihm gut auf.', 'لا حرف جر زائد.', 'präposition', 'beruflich'],
      ['berufstätig', '—', 'مشتغل', 'Beide Eltern sind berufstätig.', 'Beide Eltern sind berufstätig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'berufstätig'],
      ['die Einführung', 'die Einführungen', 'التقديم/المقدمة', 'Die Einführung ins Thema dauert zehn Minuten.', 'Die Einführung in das Thema dauert zehn Minuten.', 'الاختصار: ins Thema.', 'präposition', 'Einführung'],
      ['einschließlich', '—', 'بما في ذلك', 'Der Preis ist einschließlich Frühstück.', 'Der Preis ist einschließlich von Frühstück.', 'einschließlich + مضاف إليه بلا von.', 'präposition', 'einschließlich'],
      ['das Einschreiben', 'die Einschreiben', 'البريد المسجّل', 'Das Einschreiben kam am Freitag an.', 'Das Einschreiben kamen am Freitag an.', 'الفعل مفرد: kam.', 'konjugation', 'Einschreiben'],
      ['die Einzelheit', 'die Einzelheiten', 'التفصيل', 'Jede Einzelheit steht im Protokoll.', 'Jede Einzelheit stehen im Protokoll.', 'الفعل مفرد: steht.', 'konjugation', 'Einzelheit'],
      ['die Entlassung', 'die Entlassungen', 'التسريح/الخروج', 'Nach der Entlassung sucht er sofort.', 'Nach der Entlassung sucht er sofort auf.', 'لا حرف جر زائد.', 'präposition', 'Entlassung'],
      ['erforderlich', '—', 'مطلوب/لازم', 'Für den Antrag sind Papiere erforderlich.', 'Für den Antrag sind Papiere erforderlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'erforderlich'],
      ['andrerseits', '—', 'ومن ناحية أخرى', 'Andrerseits hat die Stelle Vorteile.', 'Andrerseits hat die Stelle Vorteile auf.', 'لا حرف جر زائد.', 'präposition', 'andrerseits'],
      ['der Angehörige', 'die Angehörigen', 'القريب/من الأهل', 'Die Angehörigen dürfen mitkommen.', 'Die Angehörigen darf mitkommen.', 'الجمع: dürfen.', 'konjugation', 'Angehörigen'],
      ['anschaffen', '—', 'يقتني', 'Wir schaffen einen Rechner an.', 'Wir anschaffen einen Rechner.', 'الفعل المنفصل: schaffen … an.', 'wortstellung', 'schaffen'],
      ['anwesend', '—', 'حاضر', 'Heute sind alle anwesend.', 'Heute sind alle anwesend gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'anwesend'],
      ['der Import', 'die Importe', 'الاستيراد', 'Der Import wächst jedes Jahr.', 'Der Import wachsen jedes Jahr.', 'الفعل مفرد: wächst.', 'konjugation', 'Import'],
      ['fällig', '—', 'مستحق السداد', 'Die Rechnung ist nächste Woche fällig.', 'Die Rechnung ist nächste Woche fällig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'fällig'],
      ['genehmigen', '—', 'يوافق على', 'Die Chefin genehmigt den Urlaub.', 'Die Chefin genehmigen den Urlaub.', 'الفعل مفرد: genehmigt.', 'konjugation', 'genehmigt'],
      ['aufnehmen', '—', 'يستقبل/يسجّل', 'Das Heim nimmt neue Gäste auf.', 'Das Heim aufnimmt neue Gäste.', 'الفعل المنفصل: nimmt … auf.', 'wortstellung', 'nimmt'],
      ['die Kriminalpolizei', '—', 'الشرطة الجنائية', 'Die Kriminalpolizei übernimmt den Fall.', 'Die Kriminalpolizei übernehmen den Fall.', 'الفعل مفرد: übernimmt.', 'konjugation', 'Kriminalpolizei'],
      ['die Lehrstelle', 'die Lehrstellen', 'مقعد التلمذة', 'Er hat eine Lehrstelle gefunden.', 'Er hat eine Lehrstelle gefunden auf.', 'لا حرف جر زائد.', 'präposition', 'Lehrstelle'],
      ['die Leiterin', 'die Leiterinnen', 'المديرة', 'Die Leiterin unterschreibt den Vertrag.', 'Die Leiterin unterschreiben den Vertrag.', 'الفعل مفرد: unterschreibt.', 'konjugation', 'Leiterin'],
      ['die Nachhilfe', 'die Nachhilfen', 'الدروس الخصوصية', 'In Mathe braucht sie Nachhilfe.', 'In Mathe braucht sie Nachhilfe auf.', 'لا حرف جر زائد.', 'präposition', 'Nachhilfe'],
      ['der Nachwuchs', '—', 'الجيل الصاعد', 'Der Nachwuchs fehlt in vielen Betrieben.', 'Der Nachwuchs fehlen in vielen Betrieben.', 'الفعل مفرد: fehlt.', 'konjugation', 'Nachwuchs'],
      ['die Versammlung', 'die Versammlungen', 'الجمعية العمومية', 'Die Versammlung beginnt um acht.', 'Die Versammlung beginnen um acht.', 'الفعل مفرد: beginnt.', 'konjugation', 'Versammlung'],
      ['vertreten', '—', 'ينوب عن', 'Wer vertritt sie während der Ferien?', 'Wer vertritt sie während der Ferien auf?', 'vertreten بلا حرف جر.', 'präposition', 'vertritt'],
      ['ausreichen', '—', 'يكفي', 'Ein Blatt reicht für den Antrag aus.', 'Ein Blatt ausreicht für den Antrag.', 'الفعل المنفصل: reicht … aus.', 'wortstellung', 'reicht'],
      ['die Vertretung', 'die Vertretungen', 'النيابة', 'Die Vertretung arbeitet schon hier.', 'Die Vertretung arbeiten schon hier.', 'الفعل مفرد: arbeitet.', 'konjugation', 'Vertretung'],
      ['der Bedarf', '—', 'الحاجة', 'Der Bedarf an Fachkräften steigt.', 'Der Bedarf an Fachkräften steigen.', 'الفعل مفرد: steigt.', 'konjugation', 'Bedarf'],
      ['die Professorin', 'die Professorinnen', 'الأستاذة الجامعية', 'Die Professorin korrigiert die Zeichnung.', 'Die Professorin korrigieren die Zeichnung.', 'الفعل مفرد: korrigiert.', 'konjugation', 'Professorin'],
      ['die Schularbeit', 'die Schularbeiten', 'الفروض المدرسية (النمسا)', 'Die Schularbeit war schwer.', 'Die Schularbeit waren schwer.', 'الفعل مفرد: war.', 'konjugation', 'Schularbeit'],
      ['der Stempel', 'die Stempel', 'الخاتم', 'Der Stempel auf dem Zeugnis fehlt.', 'Der Stempel auf dem Zeugnis fehlen.', 'الفعل مفرد: fehlt.', 'konjugation', 'Stempel'],
      ['die Stufe', 'die Stufen', 'المرحلة/الدرجة', 'Auf dieser Stufe zählt jedes Wort.', 'Auf dieser Stufe zählen jedes Wort.', 'الفاعل مفرد: zählt.', 'konjugation', 'Stufe'],
      ['die Teilnahme', '—', 'المشاركة', 'Die Teilnahme am Kurs ist freiwillig.', 'Die Teilnahme am Kurs sind freiwillig.', 'الفعل مفرد: ist.', 'konjugation', 'Teilnahme'],
      ['die Teilnehmerin', 'die Teilnehmerinnen', 'المشاركة', 'Jede Teilnehmerin bekommt ein Heft.', 'Jede Teilnehmerin bekommen ein Heft.', 'الفعل مفرد: bekommt.', 'konjugation', 'Teilnehmerin'],
      ['die Unternehmerin', 'die Unternehmerinnen', 'صاحبة العمل', 'Die Unternehmerin stellt zwei Leute ein.', 'Die Unternehmerin stellen zwei Leute ein.', 'الفعل مفرد: stellt.', 'konjugation', 'Unternehmerin'],
      ['untersagt', '—', 'ممنوع', 'Rauchen ist hier untersagt.', 'Rauchen ist hier untersagt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'untersagt'],
      ['unterstreichen', '—', 'يضع خطًّا تحت', 'Bitte unterstreichen Sie die Fehler.', 'Bitte unterstreichen Sie auf die Fehler.', 'unterstreichen بلا حرف جر.', 'präposition', 'unterstreichen'],
      ['befinden', '—', 'يعتبر/يقع', 'Das Büro befindet sich im ersten Stock.', 'Das Büro befindet im ersten Stock.', 'انعكاسي: befindet sich.', 'lexik-kollokation', 'befindet sich'],
      ['die Zeichnung', 'die Zeichnungen', 'الرسمة', 'Die Zeichnung ist nicht datiert.', 'Die Zeichnung sind nicht datiert.', 'الفعل مفرد: ist.', 'konjugation', 'Zeichnung'],
      ['die Klassenarbeit', 'die Klassenarbeiten', 'الفرض الصفّي', 'Die Klassenarbeit wird am Montag geschrieben.', 'Die Klassenarbeit werden am Montag geschrieben.', 'المفرد: wird.', 'konjugation', 'Klassenarbeit']
    ],
    tricks: [
      { trick: 'المصدر المبني للمجهول يسبق zu: zu ernähren · anzugeben · aufzunehmen', wie: 'Der Zivilstand ist im Formular anzugeben. · Die Lage ist schwer zu prüfen.', warum: 'الفعل المنفصل يدمج zu في الوسط (an-zu-geben) وهذا ما يسقطه الطالب.', anchor: 'anzugeben' },
      { trick: 'الأفعال المنفصلة في جملة ثابتة: schaffen … an · nimmt … auf · reicht … aus', wie: 'Wir schaffen einen Rechner an. · Das Heim nimmt neue Gäste auf.', warum: 'وضع البادئة في الآخر هو موضعها الطبيعي، فمن يبقيها في الأول يخلط مع غير المنفصل.', anchor: 'schaffen einen Rechner an' },
      { trick: 'أسماء السلطة والمدرسة بفعل مفرد: die Polizei · das Institut · die Professorin', wie: 'Die Kriminalpolizei übernimmt den Fall. · Die Professorin korrigiert die Zeichnung.', warum: 'الأسماء الجمعية في العربية تُعالج جمعًا، والألمانية تعاملها مفردًا مؤنثًا.', anchor: 'übernimmt den Fall' }
    ]
  },

  'b1-u8-l6': {
    items: [
      ['begegnen', '—', 'يصادف', 'Auf dem Weg begegne ich dem Trainer.', 'Auf dem Weg begegne ich den Trainer.', 'begegnen + داتيف: dem Trainer.', 'kasus', 'begegne ich dem'],
      ['der Blitz', 'die Blitze', 'البرق', 'Der Blitz kam vor dem Donner.', 'Der Blitz kamen vor dem Donner.', 'الفعل مفرد: kam.', 'konjugation', 'Blitz'],
      ['blitzen', '—', 'يومض', 'Am Himmel blitzt es schon.', 'Am Himmel blitzen es schon.', 'الضمير es مفرد: blitzt.', 'konjugation', 'blitzt es'],
      ['blühen', '—', 'يزهر', 'Im März blühen die Bäume.', 'Im März blühen die Bäume auf.', 'blühen بلا حرف جر.', 'präposition', 'blühen'],
      ['der Donner', 'die Donner', 'الرعد', 'Der Donner war weit weg.', 'Der Donner waren weit weg.', 'الفعل مفرد: war.', 'konjugation', 'Donner'],
      ['donnern', '—', 'يدوّي', 'Es donnert seit einer Stunde.', 'Es donnern seit einer Stunde.', 'الضمير es: donnert.', 'konjugation', 'donnert'],
      ['das Golf', '—', 'الغولف', 'Golf spielt er nur im Sommer.', 'Golf spielt er nur im Sommer auf.', 'لا حرف جر زائد.', 'präposition', 'Golf'],
      ['grillieren', '—', 'يشوي (سويسرا)', 'Am Abend grillieren wir im Garten.', 'Am Abend grillieren wir in den Garten.', 'في الحديقة: im Garten.', 'kasus', 'im Garten'],
      ['die Gymnastik', '—', 'التمارين البدنية', 'Gymnastik am Morgen hilft.', 'Gymnastik am Morgen helfen.', 'الفاعل مفرد: hilft.', 'konjugation', 'Gymnastik'],
      ['das Hallenbad', 'die Hallenbäder', 'المسبح المغطى', 'Das Hallenbad öffnet um sieben.', 'Das Hallenbad öffnen um sieben.', 'الفعل مفرد: öffnet.', 'konjugation', 'Hallenbad'],
      ['die Hitze', '—', 'الحرارة', 'Die Hitze macht uns müde.', 'Die Hitze machen uns müde.', 'الفعل مفرد: macht.', 'konjugation', 'Hitze'],
      ['der Humor', '—', 'الفكاهة', 'Sein Humor gefällt allen.', 'Sein Humor gefallen allen.', 'الفعل مفرد: gefällt.', 'konjugation', 'Humor'],
      ['die Hütte', 'die Hütten', 'الكوخ', 'Die Hütte liegt am See.', 'Die Hütte liegen am See.', 'الفعل مفرد: liegt.', 'konjugation', 'Hütte'],
      ['der Kampf', 'die Kämpfe', 'الصراع', 'Der Kampf um den Platz war hart.', 'Der Kampf für den Platz war hart.', 'um + من أجل.', 'präposition', 'Kampf um'],
      ['kämpfen', '—', 'يصارع', 'Die Mannschaft kämpft um den Sieg.', 'Die Mannschaft kämpfen um den Sieg.', 'الفعل مفرد: kämpft.', 'konjugation', 'kämpft'],
      ['die Katastrophe', 'die Katastrophen', 'الكارثة', 'Die Katastrophe traf das Tal.', 'Die Katastrophe trafen das Tal.', 'الفعل مفرد: traf.', 'konjugation', 'Katastrophe'],
      ['das Kostüm', 'die Kostüme', 'الزيّ التنكري', 'Zum Fasching trägt sie ein Kostüm.', 'Zum Fasching trägt sie ein Kostüm auf.', 'لا حرف جر زائد.', 'präposition', 'Kostüm'],
      ['die Landung', 'die Landungen', 'الهبوط', 'Die Landung war ruhig.', 'Die Landung waren ruhig.', 'الفعل مفرد: war.', 'konjugation', 'Landung'],
      ['der Mond', 'die Monde', 'القمر', 'Der Mond ist heute klar.', 'Der Mond sind heute klar.', 'الفعل مفرد: ist.', 'konjugation', 'Mond'],
      ['die Nordsee', '—', 'بحر الشمال', 'Die Nordsee ist im Herbst rau.', 'Die Nordsee sind im Herbst rau.', 'الفعل مفرد: ist.', 'konjugation', 'Nordsee'],
      ['der Ozean', 'die Ozeane', 'المحيط', 'Der Ozean ist hier sehr tief.', 'Der Ozean sind hier sehr tief.', 'الفعل مفرد: ist.', 'konjugation', 'Ozean'],
      ['die Ostsee', '—', 'بحر البلطيق', 'An der Ostsee ist es windig.', 'An der Ostsee sind es windig.', 'es واحد: ist.', 'konjugation', 'Ostsee'],
      ['das Picknick', 'die Picknicke', 'النزهة', 'Das Picknick war schön.', 'Das Picknick waren schön.', 'الفعل مفرد: war.', 'konjugation', 'Picknick'],
      ['der Rekord', 'die Rekorde', 'الرقم القياسي', 'Der Rekord fiel im letzten Versuch.', 'Der Rekord fielen im letzten Versuch.', 'الفعل مفرد: fiel.', 'konjugation', 'Rekord'],
      ['die Rückfahrt', 'die Rückfahrten', 'رحلة العودة', 'Die Rückfahrt dauert zwei Stunden.', 'Die Rückfahrt dauern zwei Stunden.', 'الفعل مفرد: dauert.', 'konjugation', 'Rückfahrt'],
      ['die Rückkehr', 'die Rückkehren', 'العودة', 'Nach der Rückkehr rufe ich an.', 'Nach der Rückkehr rufe ich an auf.', 'لا حرف جر زائد.', 'präposition', 'Rückkehr'],
      ['die Rundfahrt', 'die Rundfahrten', 'الجولة', 'Die Rundfahrt durch die Stadt lohnt sich.', 'Die Rundfahrt durch die Stadt lohnen sich.', 'الفعل مفرد: lohnt.', 'konjugation', 'Rundfahrt'],
      ['die Saison', 'die Saisons', 'الموسم', 'Die Saison beginnt im Mai.', 'Die Saison beginnen im Mai.', 'الفعل مفرد: beginnt.', 'konjugation', 'Saison'],
      ['der Salon', 'die Salons', 'الصالون', 'Der Salon im Erdgeschoss ist offen.', 'Der Salon im Erdgeschoss sind offen.', 'الفعل مفرد: ist.', 'konjugation', 'Salon'],
      ['das Schaufenster', 'die Schaufenster', 'الواجهة الزجاجية', 'Im Schaufenster liegt das neue Modell.', 'Im Schaufenster liegen das neue Modell.', 'الفاعل مفرد: liegt.', 'konjugation', 'im Schaufenster liegt'],
      ['der Schatten', 'die Schatten', 'الظل', 'Der Schatten der Hütte kühlt uns.', 'Der Schatten von der Hütte kühlt uns.', 'الإضافة: der Hütte.', 'kasus', 'Schatten der'],
      ['die Schlange', 'die Schlangen', 'الأفعى/الطابور', 'Vor der Kasse steht eine lange Schlange.', 'Vor der Kasse stehen eine lange Schlange.', 'الفاعل مفرد: steht.', 'konjugation', 'steht eine lange Schlange'],
      ['die Sportart', 'die Sportarten', 'نوع الرياضة', 'Diese Sportart ist nicht für jeden.', 'Diese Sportart sind nicht für jeden.', 'الفعل مفرد: ist.', 'konjugation', 'Sportart'],
      ['der Sportler', 'die Sportler', 'الرياضي', 'Der Sportler trainiert jeden Tag.', 'Der Sportler trainieren jeden Tag.', 'الفعل مفرد: trainiert.', 'konjugation', 'Sportler'],
      ['die Spielerin', 'die Spielerinnen', 'اللاعبة', 'Die Spielerin wirft den Ball.', 'Die Spielerin werfen den Ball.', 'الفعل مفرد: wirft.', 'konjugation', 'Spielerin'],
      ['das Spielzeug', 'die Spielzeuge', 'اللعبة', 'Das Spielzeug gehört den Kindern.', 'Das Spielzeug gehören den Kindern.', 'الفعل مفرد: gehört.', 'konjugation', 'Spielzeug'],
      ['das Stadion', 'die Stadien', 'الملعب', 'Das Stadion war voll.', 'Das Stadion waren voll.', 'الفعل مفرد: war.', 'konjugation', 'Stadion'],
      ['der Treffpunkt', 'die Treffpunkte', 'نقطة اللقاء', 'Der Treffpunkt bleibt derselbe.', 'Der Treffpunkt bleiben derselbe.', 'الفعل مفرد: bleibt.', 'konjugation', 'Treffpunkt'],
      ['die Übernachtung', 'die Übernachtungen', 'المبيت', 'Die Übernachtung kostet extra.', 'Die Übernachtung kosten extra.', 'الفعل مفرد: kostet.', 'konjugation', 'Übernachtung'],
      ['der Tierpark', 'die Tierparks', 'حديقة الحيوان', 'Der Tierpark öffnet im April.', 'Der Tierpark öffnen im April.', 'الفعل مفرد: öffnet.', 'konjugation', 'Tierpark']
    ],
    tricks: [
      { trick: 'begegnen يأخذ الداتيف: ich begegne dem Trainer', wie: 'Auf dem Weg begegne ich dem Trainer.', warum: 'الفعل يدل على لقاء ويأخذ مفعولًا غير مباشر، والطالب يضع الأكوزاتيف تلقائيًا.', anchor: 'begegne ich dem Trainer' },
      { trick: 'الطقس بضمير es: es blitzt · es donnert · es ist windig', wie: 'Am Himmel blitzt es schon. · Es donnert seit einer Stunde.', warum: 'الضمير es لا يُترجم، وحذفه يجعل الجملة بلا فاعل.', anchor: 'Es donnert' },
      { trick: 'الرياضة والمكان بجار ومجرور واحد: Golf spielen · im Stadion sein', wie: 'Golf spielt er nur im Sommer. · Das Stadion war voll.', warum: 'أسماء الألعاب تُستعمل بلا أداة («Golf spielen») وهذه عادة مختلفة عن العربية.', anchor: 'Golf spielt er' }
    ]
  }

};
