/* Deutschweg — B1 lexical layer, unit 5 (part b): b1-u5-l4 … b1-u5-l6.
   40 items per lesson, the count the B1 rows declare (amendment B1-L1).
   Appended to tools/vocab-b1.js as each lesson is finished. */

module.exports = {

  'b1-u5-l4': {
    items: [
      ['das Problem', 'die Probleme', 'المشكلة', 'Das Problem muss man ansprechen.', 'Das Problem muss man ansprechen es.', 'لا ضمير زائد.', 'wortstellung', 'Problem'],
      ['das Konflikt', 'die Konflikte', 'النزاع', 'Der Konflikt belastet das Team.', 'Der Konflikt belastet für das Team.', 'بلا حرف جر.', 'kasus', 'Konflikt'],
      ['die Auseinandersetzung', 'die Auseinandersetzungen', 'المواجهة', 'Die Auseinandersetzung war unnötig.', 'Die Auseinandersetzung war unnötig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Auseinandersetzung'],
      ['die Spannung', 'die Spannungen', 'التوتّر', 'Die Spannung im Team wächst.', 'Die Spannung im Team wächst es.', 'لا ضمير زائد.', 'wortstellung', 'Spannung'],
      ['der Streit', 'die Streitigkeiten', 'الخلاف', 'Der Streit eskaliert schnell.', 'Der Streit eskaliert schnell es.', 'لا ضمير زائد.', 'wortstellung', 'Streit'],
      ['sich streiten', 'streitet sich · stritt sich · hat sich gestritten', 'يتخاصم', 'Sie streiten sich über die Aufgaben.', 'Sie streiten sich für die Aufgaben.', 'über + نصب.', 'präposition', 'streiten'],
      ['der Kollege', 'die Kollegen', 'الزميل', 'Ein Kollege beschwert sich ständig.', 'Ein Kollege beschwert sich ständig es.', 'لا ضمير زائد.', 'wortstellung', 'Kollege'],
      ['die Kollegin', 'die Kolleginnen', 'الزميلة', 'Meine Kollegin hilft mir immer.', 'Meine Kollegin hilft mich immer.', 'helfen + داتيف: mir.', 'kasus', 'Kollegin'],
      ['der Vorgesetzte', 'die Vorgesetzten', 'الرئيس المباشر', 'Der Vorgesetzte entscheidet am Ende.', 'Der Vorgesetzte entscheidet in Ende.', 'am Ende.', 'präposition', 'Vorgesetzte'],
      ['die Abteilung', 'die Abteilungen', 'القسم', 'Die Abteilung arbeitet unter Druck.', 'Die Abteilung arbeitet unter Druck es.', 'لا ضمير زائد.', 'wortstellung', 'Abteilung'],
      ['die Besprechung', 'die Besprechungen', 'الاجتماع', 'Die Besprechung dauert eine Stunde.', 'Die Besprechung dauert für eine Stunde.', 'بلا حرف جر.', 'präposition', 'Besprechung'],
      ['die Sitzung', 'die Sitzungen', 'الجلسة', 'Die Sitzung wurde verschoben.', 'Die Sitzung wurde verschieben.', 'المجهول: verschoben.', 'konjugation', 'Sitzung'],
      ['die Aufgabe', 'die Aufgaben', 'المهمة', 'Die Aufgaben sind unklar verteilt.', 'Die Aufgaben sind unklar verteilen.', 'الصفة + Partizip II.', 'konjugation', 'Aufgaben'],
      ['die Zuständigkeit', 'die Zuständigkeiten', 'الاختصاص', 'Die Zuständigkeit liegt bei mir.', 'Die Zuständigkeit liegt in mir.', 'bei لا in.', 'präposition', 'Zuständigkeit'],
      ['die Überstunde', 'die Überstunden', 'الساعة الإضافية', 'Die Überstunden häufen sich.', 'Die Überstunden häufen sich es.', 'لا ضمير زائد.', 'wortstellung', 'Überstunden'],
      ['die Belastung', 'die Belastungen', 'العبء', 'Die Belastung ist zu hoch.', 'Die Belastung ist zu hoch gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Belastung'],
      ['der Druck', '—', 'الضغط', 'Der Druck nimmt zu.', 'Der Druck nimmt zu es.', 'لا ضمير زائد.', 'wortstellung', 'Druck'],
      ['das Burnout', '—', 'الإنهاك', 'Burnout ist ein ernstes Thema.', 'Burnout ist ein ernstes Thema gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Burnout'],
      ['die Kündigung', 'die Kündigungen', 'الاستقالة', 'Die Kündigung war die letzte Lösung.', 'Die Kündigung war die letzte Lösung gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Kündigung'],
      ['kündigen', 'kündigt · kündigte · hat gekündigt', 'يستقيل', 'Er hat aus Frust gekündigt.', 'Er hat aus Frust kündigen.', 'الماضي المركّب: gekündigt.', 'konjugation', 'gekündigt'],
      ['die Lösung', 'die Lösungen', 'الحل', 'Wir suchen eine gemeinsame Lösung.', 'Wir suchen für eine gemeinsame Lösung.', 'بلا حرف جر.', 'kasus', 'Lösung'],
      ['lösen', 'löst · löste · hat gelöst', 'يحلّ', 'So lösen wir den Konflikt.', 'So wir lösen den Konflikt.', 'الفعل ثانٍ.', 'wortstellung', 'lösen'],
      ['das Gespräch suchen', 'sucht · suchte · hat gesucht', 'يبحث عن الحوار', 'Ich suche das Gespräch mit ihm.', 'Ich suche das Gespräch für ihn.', 'mit + داتيف.', 'präposition', 'suche'],
      ['ansprechen', 'spricht an · sprach an · hat angesprochen', 'يخاطب', 'Sprich das Problem direkt an.', 'Sprich das Problem direkt du an.', 'التعليمة بلا ضمير.', 'wortstellung', 'an'],
      ['die Rückmeldung', 'die Rückmeldungen', 'التغذية الراجعة', 'Ich gebe dir eine ehrliche Rückmeldung.', 'Ich gebe dir ein ehrliche Rückmeldung.', 'مؤنث نصب: eine.', 'kasus', 'Rückmeldung'],
      ['die Kritik', '—', 'النقد', 'Kritik sollte sachlich bleiben.', 'Kritik sollte sachlich bleiben gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Kritik'],
      ['der Vorwurf', 'die Vorwürfe', 'الاتّهام', 'Der Vorwurf war nicht fair.', 'Der Vorwurf war nicht fair gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Vorwurf'],
      ['die Schuld', '—', 'الذنب', 'Die Schuld liegt nicht bei dir.', 'Die Schuld liegt nicht in dir.', 'bei لا in.', 'präposition', 'Schuld'],
      ['sich entschuldigen', 'entschuldigt sich · entschuldigte sich · hat sich entschuldigt', 'يعتذر', 'Er hat sich bei mir entschuldigt.', 'Er hat sich für mich entschuldigt.', 'bei (الشخص) لا für.', 'präposition', 'entschuldigt'],
      ['die Vereinbarung', 'die Vereinbarungen', 'الاتفاق', 'Die Vereinbarung gilt ab morgen.', 'Die Vereinbarung gilt von morgen.', 'ab لا von.', 'präposition', 'Vereinbarung'],
      ['der Kompromiss', 'die Kompromisse', 'الحل الوسط', 'Wir brauchen einen Kompromiss.', 'Wir brauchen ein Kompromiss.', 'مذكر نصب: einen.', 'kasus', 'Kompromiss'],
      ['die Mediation', 'die Mediationen', 'الوساطة', 'Eine Mediation kann helfen.', 'Eine Mediation kann helfen es.', 'لا ضمير زائد.', 'wortstellung', 'Mediation'],
      ['die Teamarbeit', '—', 'العمل الجماعي', 'Teamarbeit spart Zeit.', 'Teamarbeit spart Zeit es.', 'لا ضمير زائد.', 'wortstellung', 'Teamarbeit'],
      ['das Vertrauen', '—', 'الثقة', 'Vertrauen muss man aufbauen.', 'Vertrauen muss man aufbauen es.', 'لا ضمير زائد.', 'wortstellung', 'Vertrauen'],
      ['der Respekt', '—', 'الاحترام', 'Respekt ist die Grundlage.', 'Respekt ist die Grundlage gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Respekt'],
      ['die Rücksicht', '—', 'المراعاة', 'Nimm Rücksicht auf die Kollegen!', 'Nimm Rücksicht für die Kollegen!', 'auf لا für.', 'präposition', 'Rücksicht'],
      ['der Ausgleich', '—', 'التوازن', 'Der Ausgleich zwischen Arbeit und Familie fehlt.', 'Der Ausgleich zwischen Arbeit und Familie fehlt es.', 'لا ضمير زائد.', 'wortstellung', 'Ausgleich'],
      ['die Anerkennung', 'die Anerkennungen', 'التقدير', 'Anerkennung motiviert mehr als Geld.', 'Anerkennung motiviert mehr wie Geld.', 'أفعل: als.', 'kasus', 'Anerkennung'],
      ['die Work-Life-Balance', '—', 'التوازن بين العمل والحياة', 'Work-Life-Balance ist kein Luxus.', 'Work-Life-Balance ist kein Luxus es.', 'لا ضمير زائد.', 'wortstellung', 'Work-Life-Balance'],
      ['das Betriebsklima', '—', 'مناخ العمل', 'Das Betriebsklima ist wichtig.', 'Das Betriebsklima ist wichtig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Betriebsklima']
    ],
    tricks: [
      { trick: 'الخلاف في العمل يُحلّ بالخطوات: ansprechen · das Gespräch suchen · eine Vereinbarung treffen', wie: 'Sprich das Problem direkt an. Ich suche das Gespräch mit ihm. Am Ende steht eine Vereinbarung.', warum: 'العربية تحلّ الخلاف بالصمت أو الوسيط، والألمانية تتوقّع المعالجة المباشرة الموثّقة.', anchor: 'ansprechen' },
      { trick: 'الاعتذار ينفصل عن السبب: sich bei jemandem für etwas entschuldigen', wie: 'Er hat sich bei mir für den Fehler entschuldigt.', warum: 'العربية تقول «اعتذر لي عن الخطأ» بحرف واحد، والألمانية تفصل الشخص (bei) عن السبب (für).', anchor: 'sich entschuldigen' },
      { trick: 'الحمل: die Belastung · der Druck · die Überstunde · das Burnout', wie: 'Der Druck nimmt zu, die Überstunden häufen sich.', warum: 'هذه الكلمات تحمل الشكوى المهنية في B1، والعربية تصف الحالة بجملة طويلة.', anchor: 'die Belastung' }
    ]
  },

  'b1-u5-l5': {
    items: [
      ['die Gesundheit', '—', 'الصحة', 'Gesundheit ist das Wichtigste.', 'Gesundheit ist das Wichtigste es.', 'لا ضمير زائد.', 'wortstellung', 'Gesundheit'],
      ['die Krankenkasse', 'die Krankenkassen', 'صندوق المرض', 'Die Krankenkasse zahlt meistens.', 'Die Krankenkasse zahlt meistens es.', 'لا ضمير زائد.', 'wortstellung', 'Krankenkasse'],
      ['die Versicherung', 'die Versicherungen', 'التأمين', 'Die Versicherung ist Pflicht.', 'Die Versicherung ist Pflicht gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Versicherung'],
      ['der Arzt', 'die Ärzte', 'الطبيب', 'Der Arzt untersucht mich morgen.', 'Der Arzt untersucht mir morgen.', 'untersuchen + نصب: mich.', 'kasus', 'Arzt'],
      ['Ärztin', 'die Ärztinnen', 'الطبيبة', 'Die Ärztin hat mich beruhigt.', 'Die Ärztin hat mich beruhigen.', 'الماضي المركّب: beruhigt.', 'konjugation', 'Ärztin'],
      ['die Praxis', 'die Praxen', 'العيادة', 'Die Praxis öffnet um acht.', 'Die Praxis öffnet in acht.', 'الساعة: um.', 'präposition', 'Praxis'],
      ['der Termin', 'die Termine', 'الموعد', 'Der Termin ist erst nächste Woche frei.', 'Der Termin ist erst in nächste Woche frei.', 'بلا حرف جر.', 'präposition', 'Termin'],
      ['die Überweisung', 'die Überweisungen', 'إحالة طبية', 'Ich brauche eine Überweisung zum Facharzt.', 'Ich brauche eine Überweisung für den Facharzt.', 'zu + داتيف: zum.', 'präposition', 'Überweisung'],
      ['der Facharzt', 'die Fachärzte', 'الطبيب المختص', 'Der Facharzt hat lange Wartezeiten.', 'Der Facharzt hat lange Wartezeit.', 'الجمع: Wartezeiten.', 'plural', 'Facharzt'],
      ['die Behandlung', 'die Behandlungen', 'العلاج', 'Die Behandlung dauert drei Wochen.', 'Die Behandlung dauert für drei Wochen.', 'بلا حرف جر.', 'präposition', 'Behandlung'],
      ['behandeln', 'behandelt · behandelte · hat behandelt', 'يعالج', 'Der Arzt behandelt die Wunde.', 'Der Arzt behandelt für die Wunde.', 'بلا حرف جر.', 'kasus', 'behandelt'],
      ['die Untersuchung', 'die Untersuchungen', 'الفحص', 'Die Untersuchung ergab nichts.', 'Die Untersuchung ergab nichts es.', 'لا ضمير زائد.', 'wortstellung', 'Untersuchung'],
      ['das Medikament', 'die Medikamente', 'الدواء', 'Das Medikament hilft schnell.', 'Das Medikament hilft schnell es.', 'لا ضمير زائد.', 'wortstellung', 'Medikament'],
      ['die Tablette', 'die Tabletten', 'القرص', 'Nimm die Tablette nach dem Essen.', 'Nimm die Tablette nach das Essen.', 'nach + داتيف: dem.', 'kasus', 'Tablette'],
      ['das Rezept', 'die Rezepte', 'الوصفة الطبية', 'Ohne Rezept gibt es das nicht.', 'Ohne ein Rezept gibt es das nicht.', 'بعد ohne بلا أداة.', 'kasus', 'Rezept'],
      ['die Apotheke', 'die Apotheken', 'الصيدلية', 'Die Apotheke hat Notdienst.', 'Die Apotheke hat ein Notdienst.', 'Notdienst بلا أداة.', 'lexik-kollokation', 'Apotheke'],
      ['die Krankheit', 'die Krankheiten', 'المرض', 'Die Krankheit ist ansteckend.', 'Die Krankheit ist ansteckend gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Krankheit'],
      ['die Erkältung', 'die Erkältungen', 'الزكام', 'Eine Erkältung dauert eine Woche.', 'Ein Erkältung dauert eine Woche.', 'مؤنث: eine.', 'genus', 'Erkältung'],
      ['der Husten', '—', 'الكحّة', 'Der Husten wird nicht besser.', 'Der Husten wird nicht besser es.', 'لا ضمير زائد.', 'wortstellung', 'Husten'],
      ['das Fieber', '—', 'الحمّى', 'Das Fieber ist gesunken.', 'Das Fieber ist sinken.', 'الماضي المركّب: gesunken.', 'konjugation', 'Fieber'],
      ['der Schmerz', 'die Schmerzen', 'الألم', 'Die Schmerzen sind stark.', 'Die Schmerzen sind stark gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Schmerzen'],
      ['die Wunde', 'die Wunden', 'الجرح', 'Die Wunde muss sauber bleiben.', 'Die Wunde muss sauber bleiben gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Wunde'],
      ['der Unfall', 'die Unfälle', 'الحادث', 'Nach dem Unfall kam der Notarzt.', 'Nach der Unfall kam der Notarzt.', 'مذكر داتيف: dem.', 'kasus', 'Unfall'],
      ['der Notarzt', 'die Notärzte', 'طبيب الطوارئ', 'Der Notarzt kam in zehn Minuten.', 'Der Notarzt kam in zehn Minute.', 'الجمع: Minuten.', 'plural', 'Notarzt'],
      ['die Notaufnahme', 'die Notaufnahmen', 'الاستقبال الطارئ', 'In der Notaufnahme warteten viele.', 'In die Notaufnahme warteten viele.', 'in + داتيف.', 'kasus', 'Notaufnahme'],
      ['das Krankenhaus', 'die Krankenhäuser', 'المستشفى', 'Er liegt im Krankenhaus.', 'Er liegt in Krankenhaus.', 'im.', 'präposition', 'Krankenhaus'],
      ['der Aufenthalt', 'die Aufenthalte', 'الإقامة', 'Der Aufenthalt dauert drei Tage.', 'Der Aufenthalt dauert für drei Tage.', 'بلا حرف جر.', 'präposition', 'Aufenthalt'],
      ['die Operation', 'die Operationen', 'العملية الجراحية', 'Die Operation verlief gut.', 'Die Operation hat gut verlaufen.', 'السرد: verlief.', 'konjugation', 'Operation'],
      ['der Eingriff', 'die Eingriffe', 'التدخّل', 'Der Eingriff war nötig.', 'Der Eingriff war nötig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Eingriff'],
      ['die Vorsorge', '—', 'الوقاية', 'Vorsorge ist besser als Behandlung.', 'Vorsorge ist besser wie Behandlung.', 'أفعل: als.', 'kasus', 'Vorsorge'],
      ['die Impfung', 'die Impfungen', 'التلقيح', 'Die Impfung wird empfohlen.', 'Die Impfung wird empfehlen.', 'المجهول: empfohlen.', 'konjugation', 'Impfung'],
      ['impfen', 'impft · impfte · hat geimpft', 'يلقّح', 'Der Arzt impft die Kinder.', 'Der Arzt impft für die Kinder.', 'بلا حرف جر.', 'kasus', 'impft'],
      ['die Bewegung', 'die Bewegungen', 'الحركة', 'Bewegung hält gesund.', 'Bewegung hält gesund es.', 'لا ضمير زائد.', 'wortstellung', 'Bewegung'],
      ['die Ernährung', '—', 'التغذية', 'Gesunde Ernährung ist wichtig.', 'Gesund Ernährung ist wichtig.', 'الصفة: Gesunde.', 'deklination', 'Ernährung'],
      ['der Stress', '—', 'الإجهاد', 'Stress macht krank.', 'Stress macht krank es.', 'لا ضمير زائد.', 'wortstellung', 'Stress'],
      ['die Ursache', 'die Ursachen', 'السبب', 'Die Ursache ist unklar.', 'Die Ursache ist unklar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Ursache'],
      ['die Diagnose', 'die Diagnosen', 'التشخيص', 'Die Diagnose kam schnell.', 'Die Diagnose kam schnell es.', 'لا ضمير زائد.', 'wortstellung', 'Diagnose'],
      ['die Wartezeit', 'die Wartezeiten', 'مدة الانتظار', 'Die Wartezeit ist zu lang.', 'Die Wartezeit ist zu lang gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Wartezeit'],
      ['die Beschwerde', 'die Beschwerden', 'الشكوى/الأعراض', 'Die Beschwerden halten an.', 'Die Beschwerden halten an es.', 'لا ضمير زائد.', 'wortstellung', 'Beschwerden'],
      ['die Genesung', '—', 'الشفاء', 'Gute Genesung!', 'Gute Genesung du!', 'التعليمة بلا ضمير.', 'wortstellung', 'Genesung']
    ],
    tricks: [
      { trick: 'طريق المريض: der Termin · die Überweisung · die Untersuchung · das Rezept · die Apotheke', wie: 'Ich brauche einen Termin. Der Arzt schreibt eine Überweisung. Dann hole ich das Rezept in der Apotheke.', warum: 'المسار الصحي الألماني إجراء متسلسل بأسماء ثابتة، والعربية تشرحه وصفًا.', anchor: 'der Termin' },
      { trick: 'الفرق بين Behandlung (علاج) وVorsorge (وقاية) وImpfung (تلقيح)', wie: 'Vorsorge ist besser als Behandlung. Die Impfung wird empfohlen.', warum: 'العربية تستعمل «طب/علاج» للجميع، والألمانية تفرّق فتُخطئ القراءة.', anchor: 'die Vorsorge' },
      { trick: 'الأعراض بصيغة الجمع: die Schmerzen · die Beschwerden · der Husten (بلا جمع)', wie: 'Die Schmerzen sind stark. Die Beschwerden halten an.', warum: 'الشكوى الطبية تُصاغ بالجمع في الألمانية، والعربية تستعمل المفرد غالبًا.', anchor: 'die Beschwerden' }
    ]
  },

  'b1-u5-l6': {
    items: [
      ['die Wiederholung', 'die Wiederholungen', 'المراجعة', 'Die Wiederholung festigt alles.', 'Die Wiederholung festigt alles es.', 'لا ضمير زائد.', 'wortstellung', 'Wiederholung'],
      ['wiederholen', 'wiederholt · wiederholte · hat wiederholt', 'يراجع', 'Ich wiederhole die Regeln jeden Tag.', 'Ich wiederhole die Regeln in jeden Tag.', 'بلا حرف جر.', 'präposition', 'wiederhole'],
      ['das Passiv', '—', 'المبني للمجهول', 'Das Passiv wird mit werden gebildet.', 'Das Passiv wird mit werden bilden.', 'المجهول: gebildet.', 'konjugation', 'Passiv'],
      ['der Relativsatz', 'die Relativsätze', 'جملة الصلة', 'Der Relativsatz steht nach dem Komma.', 'Der Relativsatz steht in dem Komma.', 'nach لا in.', 'präposition', 'Relativsatz'],
      ['der Konjunktiv', 'die Konjunktive', 'صيغة الشرط', 'Der Konjunktiv klingt höflicher.', 'Der Konjunktiv klingt höflicher es.', 'لا ضمير زائد.', 'wortstellung', 'Konjunktiv'],
      ['der Genitiv', 'die Genitive', 'الإضافة', 'Der Genitiv wirkt schriftlich.', 'Der Genitiv wirkt schriftlich es.', 'لا ضمير زائد.', 'wortstellung', 'Genitiv'],
      ['die Deklination', 'die Deklinationen', 'التصريف الاسمي', 'Die Deklination des Adjektivs ist schwierig.', 'Die Deklination von dem Adjektiv ist schwierig.', 'Genitiv أفضل.', 'kasus', 'Deklination'],
      ['das Präteritum', '—', 'الماضي البسيط', 'Das Präteritum steht in Erzählungen.', 'Das Präteritum steht in Erzählungen es.', 'لا ضمير زائد.', 'wortstellung', 'Präteritum'],
      ['der Nebensatz', 'die Nebensätze', 'الجملة الثانوية', 'Im Nebensatz steht das Verb am Ende.', 'In Nebensatz steht das Verb am Ende.', 'im.', 'präposition', 'Nebensatz'],
      ['die Konjunktion', 'die Konjunktionen', 'أداة الربط', 'Die Konjunktion verbindet zwei Sätze.', 'Die Konjunktion verbindet zwei Satz.', 'الجمع: Sätze.', 'plural', 'Konjunktion'],
      ['die Wortstellung', '—', 'ترتيب الكلمات', 'Die Wortstellung ist entscheidend.', 'Die Wortstellung ist entscheidend gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Wortstellung'],
      ['der Wortschatz', '—', 'المفردات', 'Mein Wortschatz wächst langsam.', 'Mein Wortschatz wächst langsam es.', 'لا ضمير زائد.', 'wortstellung', 'Wortschatz'],
      ['die Aussprache', '—', 'النطق', 'Die Aussprache ist noch unsicher.', 'Die Aussprache ist noch unsicher gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Aussprache'],
      ['die Grammatik', 'die Grammatiken', 'القواعد', 'Die Grammatik ist kein Selbstzweck.', 'Die Grammatik ist kein Selbstzweck es.', 'لا ضمير زائد.', 'wortstellung', 'Grammatik'],
      ['der Fehler', 'die Fehler', 'الخطأ', 'Diesen Fehler mache ich nicht mehr.', 'Diese Fehler mache ich nicht mehr.', 'المفعول مذكر: diesen.', 'kasus', 'Fehler'],
      ['die Übung', 'die Übungen', 'التمرين', 'Die Übung macht den Meister.', 'Die Übung macht der Meister.', 'المفعول: den Meister.', 'kasus', 'Übung'],
      ['die Aufgabe', 'die Aufgaben', 'المهمة', 'Die Aufgabe war schwer.', 'Die Aufgabe war schwer gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Aufgabe'],
      ['das Niveau', 'die Niveaus', 'المستوى', 'Das Niveau steigt langsam.', 'Das Niveau steigt langsam es.', 'لا ضمير زائد.', 'wortstellung', 'Niveau'],
      ['die Prüfung', 'die Prüfungen', 'الامتحان', 'Die Prüfung besteht aus vier Teilen.', 'Die Prüfung besteht von vier Teilen.', 'aus لا von (المكوّن).', 'präposition', 'Prüfung'],
      ['der Teil', 'die Teile', 'القسم', 'Der erste Teil ist am leichtesten.', 'Der erste Teil ist am leichtesten gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Teil'],
      ['das Hören', '—', 'الاستماع', 'Beim Hören notiere ich Stichworte.', 'In Hören notiere ich Stichworte.', 'beim.', 'präposition', 'Hören'],
      ['das Lesen', '—', 'القراءة', 'Beim Lesen suche ich Schlüsselwörter.', 'In Lesen suche ich Schlüsselwörter.', 'beim.', 'präposition', 'Lesen'],
      ['das Schreiben', '—', 'الكتابة', 'Beim Schreiben achte ich auf die Struktur.', 'In Schreiben achte ich auf die Struktur.', 'beim.', 'präposition', 'Schreiben'],
      ['das Sprechen', '—', 'التحدث', 'Beim Sprechen zählt die Flüssigkeit.', 'In Sprechen zählt die Flüssigkeit.', 'beim.', 'präposition', 'Sprechen'],
      ['die Flüssigkeit', '—', 'الطلاقة', 'Die Flüssigkeit kommt mit Übung.', 'Die Flüssigkeit kommt mit die Übung.', 'mit + داتيف: der.', 'kasus', 'Flüssigkeit'],
      ['die Sicherheit', '—', 'الثقة', 'Die Sicherheit wächst mit der Zeit.', 'Die Sicherheit wächst mit die Zeit.', 'mit + داتيف: der.', 'kasus', 'Sicherheit'],
      ['das Selbstvertrauen', '—', 'الثقة بالنفس', 'Selbstvertrauen hilft im Gespräch.', 'Selbstvertrauen hilft in Gespräch.', 'im.', 'präposition', 'Selbstvertrauen'],
      ['die Strategie', 'die Strategien', 'الاستراتيجية', 'Jeder braucht eigene Strategien.', 'Jeder braucht eigene Strategie.', 'الجمع: Strategien.', 'plural', 'Strategien'],
      ['die Notiz', 'die Notizen', 'الملاحظة', 'Ich mache mir kurze Notizen.', 'Ich mache mir kurze Notiz.', 'الجمع: Notizen.', 'plural', 'Notizen'],
      ['der Schlüssel', 'die Schlüssel', 'المفتاح', 'Der Schlüssel liegt auf dem Tisch.', 'Der Schlüssel liegt in dem Tisch.', 'auf لا in (السطح).', 'präposition', 'Schlüssel'],
      ['das Schlüsselwort', 'die Schlüsselwörter', 'الكلمة المفتاحية', 'Markiere die Schlüsselwörter!', 'Markiere die Schlüsselwort!', 'الجمع: Schlüsselwörter.', 'plural', 'Schlüsselwörter'],
      ['die Zusammenfassung', 'die Zusammenfassungen', 'التلخيص', 'Eine Zusammenfassung ordnet das Gelernte.', 'Eine Zusammenfassung ordnet das Gelernte es.', 'لا ضمير زائد.', 'wortstellung', 'Zusammenfassung'],
      ['der Fortschritt', 'die Fortschritte', 'التقدّم', 'Der Fortschritt ist messbar.', 'Der Fortschritt ist messbar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Fortschritt'],
      ['das Ziel', 'die Ziele', 'الهدف', 'Setz dir realistische Ziele!', 'Setz dir realistische Ziele du!', 'التعليمة بلا ضمير.', 'wortstellung', 'Ziele'],
      ['die Routine', 'die Routinen', 'الروتين', 'Eine feste Routine hilft.', 'Eine feste Routine hilft es.', 'لا ضمير زائد.', 'wortstellung', 'Routine'],
      ['die Motivation', '—', 'الحافز', 'Die Motivation schwankt.', 'Die Motivation schwankt es.', 'لا ضمير زائد.', 'wortstellung', 'Motivation'],
      ['die Geduld', '—', 'الصبر', 'Geduld ist die halbe Arbeit.', 'Geduld ist die halbe Arbeit es.', 'لا ضمير زائد.', 'wortstellung', 'Geduld'],
      ['das Stichwort', 'die Stichworte', 'الكلمة المفتاحية', 'Ich notiere nur Stichworte.', 'Ich notiere nur Stichwort.', 'الجمع: Stichworte.', 'plural', 'Stichworte'],
      ['prüfen', 'prüft · prüfte · hat geprüft', 'يفحص', 'Prüfe deine Antworten noch einmal!', 'Prüfe deine Antworten noch einmal du!', 'التعليمة بلا ضمير.', 'wortstellung', 'Prüfe'],
      ['verbessern', 'verbessert · verbesserte · hat verbessert', 'يحسّن', 'Ich verbessere meine Fehler.', 'Ich verbessere meine Fehler für.', 'بلا حرف جر.', 'kasus', 'verbessere']
    ],
    tricks: [
      { trick: 'أربعة أقسام في B1: Hören · Lesen · Schreiben · Sprechen — ولكل قسم استراتيجيته', wie: 'Beim Hören notiere ich Stichworte. Beim Schreiben achte ich auf die Struktur.', warum: 'الامتحان الألماني يقيس الأقسام الأربعة منفصلة، والعربية تذاكر القواعد وحدها فتُهمل التوزيع.', anchor: 'das Hören' },
      { trick: 'المراجعة اليومية تكسب بالروتين لا بالمزاج: die Routine · die Notiz · die Wiederholung', wie: 'Eine feste Routine hilft. Ich wiederhole die Regeln jeden Tag.', warum: 'الاستمرارية الصغيرة هي الفارق في B1، والعربية تخطّط للمراجعة الكبرى ثم تتوقف.', anchor: 'die Routine' },
      { trick: 'اللغة تُبنى بالخروج من الفشل: der Fehler · verbessern · der Fortschritt', wie: 'Ich verbessere meine Fehler. Der Fortschritt ist messbar.', warum: 'الخطأ في العربية عيب يُخفى، وفي منهج B1 هو المادة الأولى للتصحيح.', anchor: 'der Fehler' }
    ]
  }

};
