/* Deutschweg — B1 lexical layer, unit 2 (part b): b1-u2-l4 … b1-u2-l6.
   40 items per lesson, the count the B1 rows declare (amendment B1-L1).
   Not wired yet — see the header of vocab-b1-u1a.js for why and how. */

module.exports = {

  'b1-u2-l4': {
    items: [
      ['neu', '—', 'جديد', 'Ich kaufe den neuen Wagen.', 'Ich kaufe den neu Wagen.', 'بعد الأداة المعرفة: neuen.', 'deklination', 'neuen'],
      ['alt', '—', 'قديم', 'Das alte Haus ist verkauft.', 'Das alt Haus ist verkauft.', 'بعد das: alte.', 'deklination', 'alte'],
      ['jung', '—', 'صغير السن', 'Die junge Frau arbeitet hier.', 'Die jung Frau arbeitet hier.', 'بعد die: junge.', 'deklination', 'junge'],
      ['groß', '—', 'كبير', 'Er wohnt in einem großen Haus.', 'Er wohnt in einem groß Haus.', 'بعد einem: großen.', 'deklination', 'großen'],
      ['klein', '—', 'صغير', 'Sie hat ein kleines Kind.', 'Sie hat ein klein Kind.', 'بعد ein: kleines.', 'deklination', 'kleines'],
      ['gut', '—', 'جيد', 'Das ist ein gutes Zeichen.', 'Das ist ein gut Zeichen.', 'بعد ein: gutes.', 'deklination', 'gutes'],
      ['schlecht', '—', 'سيئ', 'Bei schlechtem Wetter bleiben wir hier.', 'Bei schlecht Wetter bleiben wir hier.', 'bei + داتيف: schlechtem.', 'deklination', 'schlechtem'],
      ['teuer', '—', 'غالي', 'Das teure Auto gehört ihm.', 'Das teuer Auto gehört ihm.', 'بعد das: teure.', 'deklination', 'teure'],
      ['billig', '—', 'رخيص', 'Ich suche ein billiges Hotel.', 'Ich suche ein billig Hotel.', 'بعد ein: billiges.', 'deklination', 'billiges'],
      ['lang', '—', 'طويل', 'Der lange Weg war anstrengend.', 'Der lang Weg war anstrengend.', 'بعد der: lange.', 'deklination', 'lange'],
      ['kurz', '—', 'قصير', 'Nach kurzer Zeit kam er zurück.', 'Nach kurz Zeit kam er zurück.', 'nach + داتيف: kurzer.', 'deklination', 'kurzer'],
      ['hoch', '—', 'عالٍ', 'Der hohe Turm ist alt.', 'Der hoch Turm ist alt.', 'hoch تفقد ch أمام النهاية: hohe.', 'deklination', 'hohe'],
      ['tief', '—', 'عميق', 'Das tiefe Wasser ist gefährlich.', 'Das tief Wasser ist gefährlich.', 'بعد das: tiefe.', 'deklination', 'tiefe'],
      ['breit', '—', 'عريض', 'Die breite Straße ist neu.', 'Die breit Straße ist neu.', 'بعد die: breite.', 'deklination', 'breite'],
      ['schmal', '—', 'ضيّق', 'Ein schmaler Weg führt zum Dorf.', 'Ein schmal Weg führt zum Dorf.', 'بعد ein: schmaler.', 'deklination', 'schmaler'],
      ['schön', '—', 'جميل', 'Das schöne Wetter bleibt.', 'Das schön Wetter bleibt.', 'بعد das: schöne.', 'deklination', 'schöne'],
      ['hässlich', '—', 'قبيح', 'Das hässliche Gebäude wird abgerissen.', 'Das hässlich Gebäude wird abgerissen.', 'بعد das: hässliche.', 'deklination', 'hässliche'],
      ['sauber', '—', 'نظيف', 'In einer sauberen Stadt lebt man besser.', 'In einer sauber Stadt lebt man besser.', 'بعد einer: sauberen.', 'deklination', 'sauberen'],
      ['schmutzig', '—', 'متسخ', 'Die schmutzigen Schuhe bleiben draußen.', 'Die schmutzig Schuhe bleiben draußen.', 'الجمع بلا أداة أو مع die: schmutzigen.', 'deklination', 'schmutzigen'],
      ['ruhig', '—', 'هادئ', 'Ein ruhiges Zimmer kostet mehr.', 'Ein ruhig Zimmer kostet mehr.', 'بعد ein: ruhiges.', 'deklination', 'ruhiges'],
      ['laut', '—', 'صاخب', 'Der laute Motor stört alle.', 'Der laut Motor stört alle.', 'بعد der: laute.', 'deklination', 'laute'],
      ['freundlich', '—', 'ودود', 'Die freundliche Bedienung gefällt mir.', 'Die freundlich Bedienung gefällt mir.', 'بعد die: freundliche.', 'deklination', 'freundliche'],
      ['höflich', '—', 'مؤدّب', 'Ein höflicher Mensch grüßt zurück.', 'Ein höflich Mensch grüßt zurück.', 'بعد ein: höflicher.', 'deklination', 'höflicher'],
      ['ehrlich', '—', 'صادق', 'Ich erwarte eine ehrliche Antwort.', 'Ich erwarte eine ehrlich Antwort.', 'بعد eine: ehrliche.', 'deklination', 'ehrliche'],
      ['fleißig', '—', 'مجتهد', 'Die fleißigen Studenten bestehen.', 'Die fleißig Studenten bestehen.', 'بعد die (جمع): fleißigen.', 'deklination', 'fleißigen'],
      ['faul', '—', 'كسول', 'Der faule Schüler schläft im Unterricht.', 'Der faul Schüler schläft im Unterricht.', 'بعد der: faule.', 'deklination', 'faule'],
      ['klug', '—', 'ذكي', 'Ein kluger Kopf findet eine Lösung.', 'Ein klug Kopf findet eine Lösung.', 'بعد ein: kluger.', 'deklination', 'kluger'],
      ['dumm', '—', 'أحمق', 'Das war eine dumme Idee.', 'Das war eine dumm Idee.', 'بعد eine: dumme.', 'deklination', 'dumme'],
      ['stark', '—', 'قوي', 'Ein starker Wind weht heute.', 'Ein stark Wind weht heute.', 'بعد ein: starker.', 'deklination', 'starker'],
      ['schwach', '—', 'ضعيف', 'Der schwache Akku ist leer.', 'Der schwach Akku ist leer.', 'بعد der: schwache.', 'deklination', 'schwache'],
      ['reich', '—', 'غني', 'Die reichen Leute zahlen mehr Steuern.', 'Die reich Leute zahlen mehr Steuern.', 'بعد die (جمع): reichen.', 'deklination', 'reichen'],
      ['arm', '—', 'فقير', 'Die armen Familien brauchen Hilfe.', 'Die arm Familien brauchen Hilfe.', 'بعد die (جمع): armen.', 'deklination', 'armen'],
      ['gesund', '—', 'صحي', 'Gesunde Ernährung ist wichtig.', 'Gesund Ernährung ist wichtig.', 'بلا أداة: gesunde.', 'deklination', 'Gesunde'],
      ['krank', '—', 'مريض', 'Der kranke Mann bleibt im Bett.', 'Der krank Mann bleibt im Bett.', 'بعد der: kranke.', 'deklination', 'kranke'],
      ['glücklich', '—', 'سعيد', 'Das glückliche Paar lacht.', 'Das glücklich Paar lacht.', 'بعد das: glückliche.', 'deklination', 'glückliche'],
      ['traurig', '—', 'حزين', 'Die traurige Nachricht kam gestern.', 'Die traurig Nachricht kam gestern.', 'بعد die: traurige.', 'deklination', 'traurige'],
      ['wichtig', '—', 'مهم', 'Das ist eine wichtige Frage.', 'Das ist eine wichtig Frage.', 'بعد eine: wichtige.', 'deklination', 'wichtige'],
      ['sicher', '—', 'آمن', 'Ein sicherer Weg ist besser.', 'Ein sicher Weg ist besser.', 'بعد ein: sicherer.', 'deklination', 'sicherer'],
      ['gefährlich', '—', 'خطير', 'Die gefährliche Kurve ist bekannt.', 'Die gefährlich Kurve ist bekannt.', 'بعد die: gefährliche.', 'deklination', 'gefährliche'],
      ['bequem', '—', 'مريح', 'Ein bequemes Sofa kostet viel.', 'Ein bequem Sofa kostet viel.', 'بعد ein: bequemes.', 'deklination', 'bequemes']
    ],
    tricks: [
      { trick: 'بعد der/die/das تأخذ الصفة نهاية ضعيفة: -e في المفرد المرفوع، -en في غيره', wie: 'das alte Haus · den alten Wagen · dem alten Mann · der alten Frau.', warum: 'الأداة المعرفة تحمل علامة الحالة، فتُخفَّف الصفة؛ والعربية لا نهاية فيها أصلًا.', anchor: 'neuen' },
      { trick: 'بعد ein/eine تأخذ الصفة علامة الحالة إذا غابت عن الأداة', wie: 'ein neues Auto · einen neuen Wagen · einem neuen Wagen.', warum: 'ein لا يُظهر الحالة في المذكر والمحايد، فالصفة تظهرها نيابةً عنه.', anchor: 'ein gutes' },
      { trick: 'بلا أداة تحمل الصفة كل العلامات: großes Haus · große Häuser · großer Mann', wie: 'Gesunde Ernährung ist wichtig. · Ein kluger Kopf findet eine Lösung.', warum: 'حذف الأداة في الألمانية يُلزم بدفع العلامة إلى الصفة، وقد يحذفها الناطق العربي ظنًّا أنها زائدة.', anchor: 'Gesunde' }
    ]
  },

  'b1-u2-l5': {
    items: [
      ['als', '—', 'عندما (مرة واحدة في الماضي)', 'Als ich klein war, wohnten wir in Nabeul.', 'Wenn ich klein war, wohnten wir in Nabeul.', 'الحدث الفريد في الماضي: als.', 'wortstellung', 'Als'],
      ['wenn', '—', 'إذا/كلما', 'Wenn ich Zeit habe, gehe ich schwimmen.', 'Als ich Zeit habe, gehe ich schwimmen.', 'الحاضر والمتكرر: wenn.', 'wortstellung', 'Wenn'],
      ['wann', '—', 'متى (سؤال)', 'Ich weiß nicht, wann der Zug fährt.', 'Ich weiß nicht, als der Zug fährt.', 'السؤال: wann.', 'wortstellung', 'wann'],
      ['sobald', '—', 'حالما', 'Sobald ich fertig bin, rufe ich dich an.', 'Sobald ich bin fertig, rufe ich dich an.', 'الفعل في نهاية الجملة الثانوية.', 'wortstellung', 'Sobald'],
      ['bevor', '—', 'قبل أن', 'Bevor ich gehe, räume ich auf.', 'Bevor ich gehe, ich räume auf.', 'بعد الجملة الثانوية ينقلب الترتيب.', 'wortstellung', 'Bevor'],
      ['nachdem', '—', 'بعد أن', 'Nachdem ich gegessen hatte, ging ich los.', 'Nachdem ich gegessen habe, ging ich los.', 'الترتيب الزمني: Plusquamperfekt + Präteritum.', 'konjugation', 'Nachdem'],
      ['während', '—', 'بينما', 'Während sie kochte, deckte er den Tisch.', 'Während sie kochte, er deckte den Tisch.', 'الفعل ثانٍ في الرئيسية.', 'wortstellung', 'Während'],
      ['seitdem', '—', 'منذ أن', 'Seitdem er in Berlin wohnt, spricht er besser.', 'Seitdem er wohnt in Berlin, spricht er besser.', 'الفعل في نهاية الثانوية.', 'wortstellung', 'Seitdem'],
      ['solange', '—', 'طالما', 'Solange du hier bist, helfen wir dir.', 'Solange du bist hier, helfen wir dir.', 'الفعل في النهاية.', 'wortstellung', 'Solange'],
      ['ehe', '—', 'قبل أن (فصيحة)', 'Ehe du gehst, ruf mich an.', 'Ehe du gehst, ruf du mich an.', 'الأمر بلا ضمير.', 'wortstellung', 'Ehe'],
      ['bis', '—', 'حتى', 'Warte hier, bis ich komme.', 'Warte hier, bis ich kommen werde.', 'لا مستقبل في جملة bis.', 'konjugation', 'bis'],
      ['falls', '—', 'في حال', 'Falls es regnet, bleiben wir zu Hause.', 'Falls es regnet, wir bleiben zu Hause.', 'الفعل ثانٍ في الرئيسية.', 'wortstellung', 'Falls'],
      ['sofern', '—', 'بشرط أن', 'Sofern du Zeit hast, komm mit.', 'Sofern du hast Zeit, komm mit.', 'الفعل في النهاية.', 'wortstellung', 'Sofern'],
      ['sowie', '—', 'حالما (فصيحة)', 'Sowie er ankommt, schreibt er mir.', 'Sowie er ankommt, er schreibt mir.', 'الفعل ثانٍ.', 'wortstellung', 'Sowie'],
      ['der Zeitraum', 'die Zeiträume', 'المدة الزمنية', 'Der Zeitraum ist zu kurz.', 'Der Zeitraum ist zu kurz gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Zeitraum'],
      ['der Zeitpunkt', 'die Zeitpunkte', 'اللحظة الزمنية', 'Der Zeitpunkt ist günstig.', 'Der Zeitpunkt ist günstig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Zeitpunkt'],
      ['der Augenblick', 'die Augenblicke', 'اللحظة', 'In diesem Augenblick klingelte das Telefon.', 'In diesem Augenblick das Telefon klingelte.', 'الفعل ثانٍ بعد الظرف.', 'wortstellung', 'Augenblick'],
      ['das Jahrzehnt', 'die Jahrzehnte', 'العقد', 'In den letzten Jahrzehnten hat sich viel geändert.', 'In den letzten Jahrzehnte hat sich viel geändert.', 'الجمع داتيف: Jahrzehnten.', 'deklination', 'Jahrzehnten'],
      ['das Jahrhundert', 'die Jahrhunderte', 'القرن', 'Das Jahrhundert begann mit einem Krieg.', 'Das Jahrhundert begann mit ein Krieg.', 'mit + داتيف: einem.', 'kasus', 'Jahrhundert'],
      ['die Dauer', '—', 'المدة', 'Die Dauer des Kurses beträgt sechs Monate.', 'Die Dauer von dem Kurs beträgt sechs Monate.', 'Genitiv أفضل.', 'kasus', 'Dauer'],
      ['die Gewohnheit', 'die Gewohnheiten', 'العادة', 'Diese Gewohnheit habe ich seit der Kindheit.', 'Diese Gewohnheit ich habe seit der Kindheit.', 'الفعل ثانٍ.', 'wortstellung', 'Gewohnheit'],
      ['die Routine', 'die Routinen', 'الروتين', 'Die tägliche Routine hilft mir.', 'Die täglich Routine hilft mir.', 'الصفة: tägliche.', 'deklination', 'Routine'],
      ['der Alltag', 'die Alltage', 'اليومي', 'Im Alltag spreche ich wenig Deutsch.', 'In Alltag spreche ich wenig Deutsch.', 'في: im.', 'präposition', 'Alltag'],
      ['das Ereignis', 'die Ereignisse', 'الحدث', 'Das Ereignis bleibt unvergessen.', 'Das Ereignis bleibt unvergessen gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Ereignis'],
      ['der Vorfall', 'die Vorfälle', 'الحادثة', 'Der Vorfall ereignete sich nachts.', 'Der Vorfall hat sich nachts ereignet gehabt.', 'السرد: ereignete sich.', 'konjugation', 'Vorfall'],
      ['die Jugend', '—', 'الشباب', 'In meiner Jugend spielte ich Fußball.', 'In meine Jugend spielte ich Fußball.', 'في: in + داتيف.', 'kasus', 'Jugend'],
      ['das Alter', '—', 'العمر', 'Im Alter wird man ruhiger.', 'In Alter wird man ruhiger.', 'im.', 'präposition', 'Alter'],
      ['der Werdegang', 'die Werdegänge', 'المسار المهني', 'Sein Werdegang ist ungewöhnlich.', 'Sein Werdegang ist ungewöhnlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Werdegang'],
      ['vergehen', 'vergeht · verging · ist vergangen', 'يمرّ (الوقت)', 'Die Zeit vergeht schnell.', 'Die Zeit vergeht schnell es.', 'لا ضمير زائد.', 'wortstellung', 'vergeht'],
      ['dauern', 'dauert · dauerte · hat gedauert', 'يستمر', 'Die Fahrt dauert zwei Stunden.', 'Die Fahrt dauert für zwei Stunden.', 'بلا حرف جر.', 'kasus', 'dauert'],
      ['stattfinden', 'findet statt · fand statt · hat stattgefunden', 'يُقام', 'Das Fest findet am Samstag statt.', 'Das Fest findet am Samstag.', 'المنفصل: statt آخرًا.', 'wortstellung', 'statt'],
      ['sich erinnern', 'erinnert sich · erinnerte sich · hat sich erinnert', 'يتذكّر', 'Ich erinnere mich an den Tag genau.', 'Ich erinnere mich den Tag genau.', 'an + نصب.', 'präposition', 'erinnere'],
      ['sich gewöhnen', 'gewöhnt sich · gewöhnte sich · hat sich gewöhnt', 'يتعوّد', 'Ich habe mich an das Klima gewöhnt.', 'Ich habe mich das Klima gewöhnt.', 'an + نصب.', 'präposition', 'gewöhnt'],
      ['verpassen', 'verpasst · verpasste · hat verpasst', 'يفوّت', 'Ich habe den Zug verpasst.', 'Ich habe dem Zug verpasst.', 'المفعول نصب: den Zug.', 'kasus', 'verpasst'],
      ['rechtzeitig', '—', 'في الوقت المناسب', 'Wir sind rechtzeitig angekommen.', 'Wir sind rechtzeitig angekommen gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'rechtzeitig'],
      ['pünktlich', '—', 'دقيق الموعد', 'Sei bitte pünktlich!', 'Sei bitte pünktlich du!', 'الأمر بلا ضمير.', 'wortstellung', 'pünktlich'],
      ['kürzlich', '—', 'مؤخرًا', 'Kürzlich habe ich ihn getroffen.', 'Kürzlich ich habe ihn getroffen.', 'الفعل ثانٍ.', 'wortstellung', 'Kürzlich'],
      ['regelmäßig', '—', 'بانتظام', 'Ich übe regelmäßig.', 'Ich übe regelmäßig es.', 'لا ضمير زائد.', 'wortstellung', 'regelmäßig'],
      ['allmählich', '—', 'تدريجيًا', 'Allmählich verstehe ich mehr.', 'Allmählich ich verstehe mehr.', 'الفعل ثانٍ.', 'wortstellung', 'Allmählich'],
      ['gelegentlich', '—', 'من حين لآخر', 'Gelegentlich arbeite ich am Wochenende.', 'Gelegentlich ich arbeite am Wochenende.', 'الفعل ثانٍ.', 'wortstellung', 'Gelegentlich']
    ],
    tricks: [
      { trick: 'als لحدث واحد في الماضي · wenn للمتكرر والحاضر والمستقبل', wie: 'Als ich in Tunis war, regnete es täglich. · Wenn ich in Tunis bin, regnet es oft.', warum: 'العربية تستعمل «عندما» للحالتين، والألمانية تفرّق تفرقة صارمة يُختبر عليها.', anchor: 'als' },
      { trick: 'الجملة الثانوية أولًا تُزيح الفعل الرئيسي بعده: Als …, wohnten wir …', wie: 'Als ich klein war, wohnten wir in Nabeul.', warum: 'الجزء الأول يشغل الموضع الأول، فالفعل يبقى في الموضع الثاني.', anchor: 'Als' },
      { trick: 'nachdem تحتاج ترتيبًا زمنيًا: hatte … , ging …', wie: 'Nachdem ich gegessen hatte, ging ich los.', warum: 'العربية تقول «بعد أن أكلت» بالماضي نفسه، والألمانية تفصل بين الماضي وما قبله.', anchor: 'nachdem' }
    ]
  },

  'b1-u2-l6': {
    items: [
      ['ob', '—', 'هل (سؤال غير مباشر)', 'Ich weiß nicht, ob er kommt.', 'Ich weiß nicht, ob kommt er.', 'الفعل في النهاية.', 'wortstellung', 'ob'],
      ['wer', '—', 'مَن', 'Ich frage, wer das gemacht hat.', 'Ich frage, wer hat das gemacht.', 'الفعل في النهاية.', 'wortstellung', 'wer'],
      ['was', '—', 'ماذا', 'Sie weiß nicht, was sie will.', 'Sie weiß nicht, was will sie.', 'الفعل في النهاية.', 'wortstellung', 'was'],
      ['wann', '—', 'متى', 'Können Sie mir sagen, wann der Kurs beginnt?', 'Können Sie mir sagen, wann beginnt der Kurs?', 'الفعل في النهاية.', 'wortstellung', 'wann'],
      ['wo', '—', 'أين', 'Ich habe vergessen, wo ich geparkt habe.', 'Ich habe vergessen, wo habe ich geparkt.', 'الفعل في النهاية.', 'wortstellung', 'wo'],
      ['wie', '—', 'كيف', 'Er erklärt, wie die Maschine funktioniert.', 'Er erklärt, wie funktioniert die Maschine.', 'الفعل في النهاية.', 'wortstellung', 'wie'],
      ['warum', '—', 'لماذا', 'Sie fragt, warum ich zu spät komme.', 'Sie fragt, warum komme ich zu spät.', 'الفعل في النهاية.', 'wortstellung', 'warum'],
      ['wieso', '—', 'كيف ذلك', 'Wieso weißt du das nicht?', 'Wieso du weißt das nicht?', 'في السؤال المباشر: الفعل ثانٍ.', 'wortstellung', 'Wieso'],
      ['weshalb', '—', 'لماذا (فصيحة)', 'Ich verstehe nicht, weshalb er ablehnt.', 'Ich verstehe nicht, weshalb lehnt er ab.', 'الفعل في النهاية.', 'wortstellung', 'weshalb'],
      ['welcher', '—', 'أيّ', 'Ich weiß nicht, welcher Zug schneller ist.', 'Ich weiß nicht, welcher Zug ist schneller.', 'الفعل في النهاية.', 'wortstellung', 'welcher'],
      ['wie viel', '—', 'كم', 'Kannst du mir sagen, wie viel das kostet?', 'Kannst du mir sagen, wie viel kostet das?', 'الفعل في النهاية.', 'wortstellung', 'viel'],
      ['wie lange', '—', 'كم من الوقت', 'Ich frage, wie lange die Fahrt dauert.', 'Ich frage, wie lange dauert die Fahrt.', 'الفعل في النهاية.', 'wortstellung', 'lange'],
      ['wie oft', '—', 'كم مرة', 'Er will wissen, wie oft ich übe.', 'Er will wissen, wie oft übe ich.', 'الفعل في النهاية.', 'wortstellung', 'oft'],
      ['wohin', '—', 'إلى أين', 'Sie fragt, wohin wir fahren.', 'Sie fragt, wohin fahren wir.', 'الفعل في النهاية.', 'wortstellung', 'wohin'],
      ['woher', '—', 'من أين', 'Ich weiß nicht, woher er kommt.', 'Ich weiß nicht, woher kommt er.', 'الفعل في النهاية.', 'wortstellung', 'woher'],
      ['womit', '—', 'بماذا', 'Er fragt, womit ich fahre.', 'Er fragt, womit fahre ich.', 'الفعل في النهاية.', 'wortstellung', 'womit'],
      ['woran', '—', 'بمَ (في)', 'Ich weiß nicht, woran es liegt.', 'Ich weiß nicht, woran liegt es.', 'الفعل في النهاية.', 'wortstellung', 'woran'],
      ['fragen', 'fragt · fragte · hat gefragt', 'يسأل', 'Ich frage, ob du Zeit hast.', 'Ich frage, ob hast du Zeit.', 'الفعل في النهاية.', 'wortstellung', 'frage'],
      ['sich erkundigen', 'erkundigt sich · erkundigte sich · hat sich erkundigt', 'يستفسر', 'Ich erkundige mich, wann der Kurs beginnt.', 'Ich erkundige wann der Kurs beginnt.', 'الضمير mich لازم.', 'konjugation', 'erkundige'],
      ['nachfragen', 'fragt nach · fragte nach · hat nachgefragt', 'يستفسر مرة أخرى', 'Ich frage noch einmal nach.', 'Ich frage noch einmal.', 'المنفصل: nach.', 'wortstellung', 'nach'],
      ['anfragen', 'fragt an · fragte an · hat angefragt', 'يراسل للاستفسار', 'Wir fragen beim Amt an.', 'Wir fragen beim Amt.', 'المنفصل: an.', 'wortstellung', 'an'],
      ['wissen wollen', 'will wissen · wollte wissen · hat wissen wollen', 'يريد أن يعرف', 'Sie will wissen, ob wir kommen.', 'Sie will wissen, ob wir kommen es.', 'لا ضمير زائد.', 'wortstellung', 'wissen'],
      ['ahnen', 'ahnt · ahnte · hat geahnt', 'يحدس', 'Ich ahne, dass es schwierig wird.', 'Ich ahne, dass es wird schwierig.', 'الفعل في النهاية.', 'wortstellung', 'ahne'],
      ['vermuten', 'vermutet · vermutete · hat vermutet', 'يظنّ', 'Ich vermute, dass er zu Hause ist.', 'Ich vermute, dass er ist zu Hause.', 'الفعل في النهاية.', 'wortstellung', 'vermute'],
      ['erklären', 'erklärt · erklärte · hat erklärt', 'يشرح', 'Der Lehrer erklärt, wie es funktioniert.', 'Der Lehrer erklärt, wie es funktioniert es.', 'لا ضمير زائد.', 'wortstellung', 'erklärt'],
      ['mitteilen', 'teilt mit · teilte mit · hat mitgeteilt', 'يبلّغ', 'Er teilt mir mit, dass er später kommt.', 'Er teilt mir mit, dass er kommt später.', 'الفعل في النهاية.', 'wortstellung', 'mit'],
      ['berichten', 'berichtet · berichtete · hat berichtet', 'يخبر', 'Die Zeitung berichtet, was gestern geschah.', 'Die Zeitung berichtet, was geschah gestern.', 'الفعل في النهاية.', 'wortstellung', 'berichtet'],
      ['antworten', 'antwortet · antwortete · hat geantwortet', 'يجيب', 'Er antwortet, dass er nicht kommen kann.', 'Er antwortet, dass er kann nicht kommen.', 'الفعل في النهاية.', 'wortstellung', 'antwortet'],
      ['erwidern', 'erwidert · erwiderte · hat erwidert', 'يردّ', 'Sie erwidert, dass sie müde ist.', 'Sie erwidert, dass sie ist müde.', 'الفعل في النهاية.', 'wortstellung', 'erwidert'],
      ['bestätigen', 'bestätigt · bestätigte · hat bestätigt', 'يؤكّد', 'Er bestätigt, dass er kommt.', 'Er bestätigt, dass er kommt es.', 'لا ضمير زائد.', 'wortstellung', 'bestätigt'],
      ['verneinen', 'verneint · verneinte · hat verneint', 'ينفي', 'Er verneint, dass er das gesagt hat.', 'Er verneint, dass er hat das gesagt.', 'الفعل في النهاية.', 'wortstellung', 'verneint'],
      ['klären', 'klärt · klärte · hat geklärt', 'يجلّي', 'Wir klären, wer dafür zuständig ist.', 'Wir klären, wer ist dafür zuständig.', 'الفعل في النهاية.', 'wortstellung', 'klären'],
      ['die Frage', 'die Fragen', 'السؤال', 'Ich habe eine Frage zur Anmeldung.', 'Ich habe eine Frage über die Anmeldung.', 'إلى: zu + داتيف.', 'präposition', 'Frage'],
      ['das Rätsel', 'die Rätsel', 'اللغز', 'Das Rätsel bleibt ungelöst.', 'Das Rätsel bleibt ungelöst gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Rätsel'],
      ['das Geheimnis', 'die Geheimnisse', 'السر', 'Sie hat mir das Geheimnis verraten.', 'Sie hat mir das Geheimnis verraten gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Geheimnis'],
      ['die Neugier', '—', 'الفضول', 'Neugier ist hier erlaubt.', 'Neugier ist hier erlaubt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Neugier'],
      ['der Hinweis', 'die Hinweise', 'الإشارة', 'Der Hinweis war hilfreich.', 'Der Hinweis war hilfreich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Hinweis'],
      ['die Erklärung', 'die Erklärungen', 'الشرح', 'Seine Erklärung war verständlich.', 'Seine Erklärung war verständlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Erklärung'],
      ['die Umfrage', 'die Umfragen', 'الاستبيان', 'Die Umfrage zeigt ein klares Bild.', 'Die Umfrage zeigt ein klar Bild.', 'الصفة: klares.', 'deklination', 'Umfrage'],
      ['die Auskunft', 'die Auskünfte', 'المعلومة الرسمية', 'Die Auskunft erhalten Sie am Schalter.', 'Die Auskunft erhalten Sie am Schalter es.', 'لا ضمير زائد.', 'wortstellung', 'Auskunft']
    ],
    tricks: [
      { trick: 'السؤال غير المباشر: الفعل في النهاية، وسؤال بلا أداة يبدأ بـ ob', wie: 'Ich weiß nicht, ob er kommt. · Er fragt, wann der Kurs beginnt.', warum: 'العربية تنقل السؤال بترتيبه نفسه؛ الألمانية تقلب الجملة إلى ترتيب خبري بأداة استفهام.', anchor: 'ob' },
      { trick: 'حرف الجر يسأل عن شيء: woran · womit · worüber', wie: 'Ich weiß nicht, woran es liegt. · Er fragt, womit ich fahre.', warum: 'wo + حرف الجر يبني أداة السؤال عن غير العاقل، والعربية تسأل «بماذا» بلا تركيب.', anchor: 'woran' },
      { trick: 'السؤال المهذب: Können Sie mir sagen, …? — الفعل في النهاية', wie: 'Können Sie mir sagen, wann der Kurs beginnt?', warum: 'العربية تقول «هل يمكن أن تخبرني متى يبدأ؟» بالفعل ثانٍ بعد «متى»، والألمانية تدفعه آخرًا.', anchor: 'wann' }
    ]
  }

};
