/* Deutschweg — B1 lexical layer, unit 3 (part a): b1-u3-l1 … b1-u3-l3.
   40 items per lesson, the count the B1 rows declare (amendment B1-L1).
   Not wired yet — see the header of vocab-b1-u1a.js for why and how. */

module.exports = {

  'b1-u3-l1': {
    items: [
      ['sich bewerben', 'bewirbt sich · bewarb sich · hat sich beworben', 'يتقدّم بطلب', 'Ich bewerbe mich um eine Stelle als Koch.', 'Ich bewerbe mich für eine Stelle als Koch.', 'um لا für.', 'präposition', 'bewerbe'],
      ['die Bewerbung', 'die Bewerbungen', 'طلب التوظيف', 'Meine Bewerbung ist schon raus.', 'Meine Bewerbung ist schon raus es.', 'لا ضمير زائد.', 'wortstellung', 'Bewerbung'],
      ['das Bewerbungsschreiben', 'die Bewerbungsschreiben', 'خطاب الطلب', 'Das Bewerbungsschreiben ist zu lang.', 'Das Bewerbungsschreiben ist zu lang gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Bewerbungsschreiben'],
      ['der Lebenslauf', 'die Lebensläufe', 'السيرة الذاتية', 'Der Lebenslauf muss lückenlos sein.', 'Der Lebenslauf muss lückenlos gemacht sein.', 'الصفة تكفي.', 'lexik-kollokation', 'Lebenslauf'],
      ['das Anschreiben', 'die Anschreiben', 'الخطاب المرافق', 'Im Anschreiben erkläre ich meine Motivation.', 'In das Anschreiben erkläre ich meine Motivation.', 'in + داتيف: dem.', 'kasus', 'Anschreiben'],
      ['das Zeugnis', 'die Zeugnisse', 'الشهادة', 'Die Zeugnisse liegen bei.', 'Die Zeugnisse liegen bei es.', 'لا ضمير زائد.', 'wortstellung', 'Zeugnisse'],
      ['die Stelle', 'die Stellen', 'الوظيفة', 'Die Stelle ist ab September frei.', 'Die Stelle ist von September frei.', 'من: ab لا von.', 'präposition', 'Stelle'],
      ['der Arbeitsplatz', 'die Arbeitsplätze', 'مكان العمل', 'Der Arbeitsplatz ist gut erreichbar.', 'Der Arbeitsplatz ist gut erreichbar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Arbeitsplatz'],
      ['die Anzeige', 'die Anzeigen', 'الإعلان', 'Die Anzeige stand in der Zeitung.', 'Die Anzeige stand in die Zeitung.', 'in + داتيف.', 'kasus', 'Anzeige'],
      ['die Ausschreibung', 'die Ausschreibungen', 'الإعلان الوظيفي', 'Die Ausschreibung richtet sich an Berufserfahrene.', 'Die Ausschreibung richtet sich für Berufserfahrene.', 'an + نصب.', 'präposition', 'Ausschreibung'],
      ['die Voraussetzung', 'die Voraussetzungen', 'الشرط المسبق', 'Die Voraussetzung ist ein Führerschein.', 'Die Voraussetzung ist ein Führerschein gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Voraussetzung'],
      ['die Anforderung', 'die Anforderungen', 'المتطلّب', 'Die Anforderungen sind hoch.', 'Die Anforderungen sind hoch gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Anforderungen'],
      ['die Erfahrung', 'die Erfahrungen', 'الخبرة', 'Ich bringe fünf Jahre Erfahrung mit.', 'Ich bringe fünf Jahre Erfahrung.', 'المنفصل: mit.', 'wortstellung', 'mit'],
      ['die Kenntnis', 'die Kenntnisse', 'المعرفة', 'Gute Englischkenntnisse sind nötig.', 'Gute Englischkenntnis sind nötig.', 'الجمع: Kenntnisse.', 'plural', 'Englischkenntnisse'],
      ['die Qualifikation', 'die Qualifikationen', 'المؤهّل', 'Seine Qualifikation passt genau.', 'Seine Qualifikation passt genau es.', 'لا ضمير زائد.', 'wortstellung', 'Qualifikation'],
      ['die Ausbildung', 'die Ausbildungen', 'التكوين', 'Die Ausbildung dauerte drei Jahre.', 'Die Ausbildung dauerte für drei Jahre.', 'بلا حرف جر.', 'präposition', 'Ausbildung'],
      ['das Studium', 'die Studien', 'الدراسة الجامعية', 'Das Studium habe ich in Tunis gemacht.', 'Das Studium ich habe in Tunis gemacht.', 'الفعل ثانٍ.', 'wortstellung', 'Studium'],
      ['die Berufserfahrung', '—', 'الخبرة المهنية', 'Berufserfahrung ist mir wichtig.', 'Berufserfahrung ist mir wichtig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Berufserfahrung'],
      ['die Motivation', 'die Motivationen', 'الدافع', 'Meine Motivation ist die Sprache.', 'Meine Motivation ist die Sprache gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Motivation'],
      ['die Stärke', 'die Stärken', 'نقطة القوة', 'Meine Stärke ist die Geduld.', 'Meine Stärke ist die Geduld gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Stärke'],
      ['die Schwäche', 'die Schwächen', 'نقطة الضعف', 'Über Schwächen spricht man ungern.', 'Über Schwächen spricht man ungern es.', 'لا ضمير زائد.', 'wortstellung', 'Schwächen'],
      ['die Teamfähigkeit', '—', 'القدرة على العمل الجماعي', 'Teamfähigkeit wird vorausgesetzt.', 'Teamfähigkeit wird vorausgesetzt gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Teamfähigkeit'],
      ['die Zuverlässigkeit', '—', 'الموثوقية', 'Zuverlässigkeit ist hier Pflicht.', 'Zuverlässigkeit ist hier Pflicht gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Zuverlässigkeit'],
      ['die Flexibilität', '—', 'المرونة', 'Flexibilität wird erwartet.', 'Flexibilität wird erwartet gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Flexibilität'],
      ['der Arbeitgeber', 'die Arbeitgeber', 'صاحب العمل', 'Der Arbeitgeber zahlt die Versicherung.', 'Der Arbeitgeber zahlt für die Versicherung.', 'بلا حرف جر.', 'kasus', 'Arbeitgeber'],
      ['der Arbeitnehmer', 'die Arbeitnehmer', 'العامل', 'Die Arbeitnehmer fordern mehr Lohn.', 'Die Arbeitnehmer fordern mehr Lohn es.', 'لا ضمير زائد.', 'wortstellung', 'Arbeitnehmer'],
      ['der Chef', 'die Chefs', 'الرئيس في العمل', 'Der Chef liest jede Bewerbung.', 'Der Chef liest jede Bewerbung es.', 'لا ضمير زائد.', 'wortstellung', 'Chef'],
      ['die Geschäftsleitung', 'die Geschäftsleitungen', 'الإدارة', 'Die Geschäftsleitung entscheidet morgen.', 'Die Geschäftsleitung entscheidet morgen es.', 'لا ضمير زائد.', 'wortstellung', 'Geschäftsleitung'],
      ['die Abteilung', 'die Abteilungen', 'القسم', 'Ich arbeite in der Abteilung für Einkauf.', 'Ich arbeite in die Abteilung für Einkauf.', 'in + داتيف.', 'kasus', 'Abteilung'],
      ['das Vorstellungsgespräch', 'die Vorstellungsgespräche', 'مقابلة العمل', 'Das Vorstellungsgespräch war anstrengend.', 'Das Vorstellungsgespräch war anstrengend gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Vorstellungsgespräch'],
      ['das Gehalt', 'die Gehälter', 'الراتب', 'Das Gehalt ist verhandelbar.', 'Das Gehalt ist verhandelbar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Gehalt'],
      ['der Lohn', 'die Löhne', 'الأجر', 'Der Lohn wird monatlich gezahlt.', 'Der Lohn wird monatlich zahlen.', 'المجهول: gezahlt.', 'konjugation', 'Lohn'],
      ['die Kündigung', 'die Kündigungen', 'الاستقالة/الإنهاء', 'Die Kündigung kam überraschend.', 'Die Kündigung kam überraschend gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Kündigung'],
      ['der Vertrag', 'die Verträge', 'العقد', 'Der Vertrag läuft unbefristet.', 'Der Vertrag läuft unbefristet es.', 'لا ضمير زائد.', 'wortstellung', 'Vertrag'],
      ['die Probezeit', 'die Probezeiten', 'فترة التجربة', 'Die Probezeit beträgt sechs Monate.', 'Die Probezeit beträgt für sechs Monate.', 'بلا حرف جر.', 'präposition', 'Probezeit'],
      ['sich vorstellen', 'stellt sich vor · stellte sich vor · hat sich vorgestellt', 'يقدّم نفسه', 'Im Gespräch stelle ich mich kurz vor.', 'Im Gespräch stelle ich mich kurz.', 'المنفصل: vor.', 'wortstellung', 'vor'],
      ['einladen', 'lädt ein · lud ein · hat eingeladen', 'يدعو', 'Die Firma hat mich zum Gespräch eingeladen.', 'Die Firma hat mich zum Gespräch geladen ein.', 'Partizip II: eingeladen.', 'konjugation', 'eingeladen'],
      ['absagen', 'sagt ab · sagte ab · hat abgesagt', 'يلغي', 'Er hat den Termin abgesagt.', 'Er hat den Termin gesagt ab.', 'Partizip II: abgesagt.', 'konjugation', 'abgesagt'],
      ['zusagen', 'sagt zu · sagte zu · hat zugesagt', 'يقبل', 'Sie hat sofort zugesagt.', 'Sie hat sofort gesagt zu.', 'Partizip II: zugesagt.', 'konjugation', 'zugesagt'],
      ['überzeugen', 'überzeugt · überzeugte · hat überzeugt', 'يقنع', 'Seine Erfahrung hat uns überzeugt.', 'Seine Erfahrung hat uns überzeugen.', 'الماضي المركّب: überzeugt.', 'konjugation', 'überzeugt']
    ],
    tricks: [
      { trick: 'sich bewerben um eine Stelle — وdie Bewerbung unterlagen gehören dazu', wie: 'Ich bewerbe mich um eine Stelle. · Die Bewerbung enthält Anschreiben, Lebenslauf und Zeugnisse.', warum: 'العربية تقول «تقدّمت لوظيفة»، والألمانية تطلب um لا für.', anchor: 'sich bewerben' },
      { trick: 'الخطاب الرسمي: Sehr geehrte … · Mit freundlichen Grüßen', wie: 'Sehr geehrte Frau Müller, … Mit freundlichen Grüßen, Ali Ben Salah', warum: 'الرسالة الرسمية الألمانية قالب مغلق، وترجمته الحرفية من العربية تبدو غير مهنية.', anchor: 'Bewerbungsschreiben' },
      { trick: 'أفعال الطلب الرسمي: einladen · absagen · zusagen · überzeugen — كلها منفصلة أو مركّبة', wie: 'Die Firma hat mich eingeladen. · Sie hat zugesagt.', warum: 'البادئات المنفصلة تنتقل إلى اسم المفعول فتُدمج، والعربية لا تفصل أصلًا.', anchor: 'einladen' }
    ]
  },

  'b1-u3-l2': {
    items: [
      ['sich beschweren', 'beschwert sich · beschwerte sich · hat sich beschwert', 'يشتكي', 'Ich beschwere mich über den Lärm.', 'Ich beschwere mich für den Lärm.', 'über + نصب.', 'präposition', 'beschwere'],
      ['die Beschwerde', 'die Beschwerden', 'الشكوى', 'Meine Beschwerde wurde nicht beantwortet.', 'Meine Beschwerde wurde nicht beantworten.', 'المجهول: beantwortet.', 'konjugation', 'Beschwerde'],
      ['die Reklamation', 'die Reklamationen', 'الاعتراض على منتج', 'Die Reklamation ist berechtigt.', 'Die Reklamation ist berechtigt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Reklamation'],
      ['reklamieren', 'reklamiert · reklamierte · hat reklamiert', 'يعترض على منتج', 'Ich reklamiere den defekten Kühlschrank.', 'Ich reklamiere über den defekten Kühlschrank.', 'بلا حرف جر.', 'kasus', 'reklamiere'],
      ['beanstanden', 'beanstandet · beanstandete · hat beanstandet', 'يعترض على', 'Der Kunde beanstandet die Rechnung.', 'Der Kunde beanstandet über die Rechnung.', 'بلا حرف جر.', 'kasus', 'beanstandet'],
      ['sich ärgern', 'ärgert sich · ärgerte sich · hat sich geärgert', 'يغتاظ', 'Ich ärgere mich über den Fehler.', 'Ich ärgere mich für den Fehler.', 'über + نصب.', 'präposition', 'ärgere'],
      ['der Ärger', '—', 'الغضب', 'Der Ärger war schnell vorbei.', 'Der Ärger war schnell vorbei gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Ärger'],
      ['die Unzufriedenheit', '—', 'عدم الرضا', 'Die Unzufriedenheit der Kunden wächst.', 'Die Unzufriedenheit von den Kunden wächst.', 'Genitiv أفضل.', 'kasus', 'Unzufriedenheit'],
      ['die Enttäuschung', 'die Enttäuschungen', 'خيبة الأمل', 'Die Enttäuschung war groß.', 'Die Enttäuschung war groß gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Enttäuschung'],
      ['das Missverständnis', 'die Missverständnisse', 'سوء الفهم', 'Da liegt ein Missverständnis vor.', 'Da liegt ein Missverständnis vor es.', 'لا ضمير زائد.', 'wortstellung', 'Missverständnis'],
      ['der Mangel', 'die Mängel', 'العيب', 'Der Mangel wurde schnell behoben.', 'Der Mangel wurde schnell beheben.', 'المجهول: behoben.', 'konjugation', 'Mangel'],
      ['der Fehler', 'die Fehler', 'الخطأ', 'Der Fehler liegt bei uns.', 'Der Fehler liegt in uns.', 'bei (المسؤولية).', 'präposition', 'Fehler'],
      ['der Schaden', 'die Schäden', 'الضرر', 'Der Schaden ist versichert.', 'Der Schaden ist versichern.', 'المجهول: versichert.', 'konjugation', 'Schaden'],
      ['die Lieferung', 'die Lieferungen', 'التسليم', 'Die Lieferung kam zu spät.', 'Die Lieferung kam zu spät es.', 'لا ضمير زائد.', 'wortstellung', 'Lieferung'],
      ['die Frist', 'die Fristen', 'الأجل', 'Die Frist ist abgelaufen.', 'Die Frist ist ablaufen.', 'اسم المفعول: abgelaufen.', 'konjugation', 'Frist'],
      ['die Garantie', 'die Garantien', 'الضمان', 'Die Garantie gilt zwei Jahre.', 'Die Garantie gilt für zwei Jahre.', 'بلا حرف جر هنا.', 'präposition', 'Garantie'],
      ['die Gewährleistung', '—', 'الضمان القانوني', 'Die Gewährleistung ist gesetzlich geregelt.', 'Die Gewährleistung ist gesetzlich regeln.', 'المجهول: geregelt.', 'konjugation', 'Gewährleistung'],
      ['der Umtausch', 'die Umtäusche', 'الاستبدال', 'Der Umtausch ist kostenlos.', 'Der Umtausch ist kostenlos gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Umtausch'],
      ['umtauschen', 'tauscht um · tauschte um · hat umgetauscht', 'يستبدل', 'Ich möchte die Ware umtauschen.', 'Ich möchte die Ware tauschen um.', 'المنفصل يندمج في المفعول: umgetauscht.', 'konjugation', 'umtauschen'],
      ['zurückgeben', 'gibt zurück · gab zurück · hat zurückgegeben', 'يعيد', 'Ich gebe das Buch zurück.', 'Ich gebe das Buch.', 'المنفصل: zurück.', 'wortstellung', 'zurück'],
      ['erstatten', 'erstattet · erstattete · hat erstattet', 'يعوّض', 'Wir erstatten Ihnen den Betrag.', 'Wir erstatten Ihnen für den Betrag.', 'بلا حرف جر.', 'kasus', 'erstatten'],
      ['die Rückerstattung', 'die Rückerstattungen', 'ردّ المبلغ', 'Die Rückerstattung dauert eine Woche.', 'Die Rückerstattung dauert für eine Woche.', 'بلا حرف جر.', 'präposition', 'Rückerstattung'],
      ['der Betrag', 'die Beträge', 'المبلغ', 'Der Betrag ist auf dem Konto.', 'Der Betrag ist in dem Konto.', 'auf dem Konto.', 'präposition', 'Betrag'],
      ['die Rechnung', 'die Rechnungen', 'الفاتورة', 'Die Rechnung ist falsch.', 'Die Rechnung ist falsch gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Rechnung'],
      ['die Gutschrift', 'die Gutschriften', 'الإضافة الحسابية', 'Die Gutschrift erfolgt nächste Woche.', 'Die Gutschrift erfolgt in nächste Woche.', 'بلا حرف جر.', 'präposition', 'Gutschrift'],
      ['der Kunde', 'die Kunden', 'العميل', 'Der Kunde hat immer recht.', 'Der Kunde hat immer recht es.', 'لا ضمير زائد.', 'wortstellung', 'Kunde'],
      ['der Kundendienst', '—', 'خدمة العملاء', 'Der Kundendienst ist schwer erreichbar.', 'Der Kundendienst ist schwer erreichbar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Kundendienst'],
      ['die Hotline', 'die Hotlines', 'الخط الساخن', 'Die Hotline ist rund um die Uhr offen.', 'Die Hotline ist rund um die Uhr offen es.', 'لا ضمير زائد.', 'wortstellung', 'Hotline'],
      ['die Antwort', 'die Antworten', 'الجواب', 'Bis heute kam keine Antwort.', 'Bis heute kam kein Antwort.', 'مؤنث نصب: keine.', 'kasus', 'Antwort'],
      ['die Entschuldigung', 'die Entschuldigungen', 'الاعتذار', 'Wir bitten um Entschuldigung.', 'Wir bitten für Entschuldigung.', 'bitten um.', 'präposition', 'Entschuldigung'],
      ['sich entschuldigen', 'entschuldigt sich · entschuldigte sich · hat sich entschuldigt', 'يعتذر', 'Die Firma entschuldigt sich für den Fehler.', 'Die Firma entschuldigt für den Fehler.', 'الضمير sich.', 'konjugation', 'entschuldigt'],
      ['die Ursache', 'die Ursachen', 'السبب', 'Die Ursache war ein Computerfehler.', 'Die Ursache war ein Computerfehler gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Ursache'],
      ['beheben', 'behebt · behob · hat behoben', 'يعالج عطلًا', 'Wir beheben den Fehler sofort.', 'Wir beheben den Fehler sofort gemacht.', 'الفعل كامل بذاته.', 'lexik-kollokation', 'beheben'],
      ['lösen', 'löst · löste · hat gelöst', 'يحلّ', 'Das Problem ist gelöst.', 'Das Problem ist lösen.', 'اسم المفعول: gelöst.', 'konjugation', 'gelöst'],
      ['klären', 'klärt · klärte · hat geklärt', 'يجلّي', 'Wir klären den Fall heute.', 'Wir klären den Fall heute es.', 'لا ضمير زائد.', 'wortstellung', 'klären'],
      ['prüfen', 'prüft · prüfte · hat geprüft', 'يتحقّق', 'Wir prüfen Ihren Auftrag noch einmal.', 'Wir prüfen Ihren Auftrag für noch einmal.', 'بلا حرف جر.', 'kasus', 'prüfen'],
      ['die Forderung', 'die Forderungen', 'المطالبة', 'Die Forderung ist berechtigt.', 'Die Forderung ist berechtigt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Forderung'],
      ['fordern', 'fordert · forderte · hat gefordert', 'يطالب', 'Wir fordern eine Rückerstattung.', 'Wir fordern für eine Rückerstattung.', 'بلا حرف جر.', 'kasus', 'fordern'],
      ['die Frist setzen', 'setzt · setzte · hat gesetzt', 'يحدّد أجلًا', 'Wir setzen Ihnen eine Frist von zwei Wochen.', 'Wir setzen Ihnen eine Frist für zwei Wochen.', 'von لا für.', 'präposition', 'Frist'],
      ['der Anwalt', 'die Anwälte', 'المحامي', 'Wenn nichts passiert, gehe ich zum Anwalt.', 'Wenn nichts passiert, ich gehe zum Anwalt.', 'الفعل ثانٍ في الرئيسية.', 'wortstellung', 'Anwalt']
    ],
    tricks: [
      { trick: 'الشكوى الرسمية بالترتيب: Beschwerde · Fehler · Frist · Forderung', wie: 'Ich beschwere mich über die Lieferung. Der Fehler liegt bei Ihnen. Ich setze eine Frist von zwei Wochen.', warum: 'النص العربي يبدأ بالعتاب، والألمانية تبدأ بالوقائع ثم تطلب؛ الترتيب هو الرسالة.', anchor: 'die Beschwerde' },
      { trick: 'beschweren über · sich ärgern über · bitten um — الحرف يحدّد المعنى', wie: 'Ich beschwere mich über den Lärm. · Ich bitte um Entschuldigung.', warum: 'العربية تستعمل «على/من» بحرية، والألمانية تربط الفعل بحرف ثابت.', anchor: 'sich beschweren' },
      { trick: 'الاستبدال والإعادة: umtauschen · zurückgeben · erstatten', wie: 'Ich tausche die Ware um. · Wir erstatten Ihnen den Betrag.', warum: 'العربية تقول «أرجّع/أبدّل» بلا فصل، والألمانية تفصل البادئة وتدمجها في اسم المفعول.', anchor: 'umtauschen' }
    ]
  },

  'b1-u3-l3': {
    items: [
      ['die Umwelt', '—', 'البيئة', 'Wir müssen die Umwelt schützen.', 'Wir müssen die Umwelt schützen es.', 'لا ضمير زائد.', 'wortstellung', 'Umwelt'],
      ['der Umweltschutz', '—', 'حماية البيئة', 'Umweltschutz beginnt im Alltag.', 'Umweltschutz beginnt in Alltag.', 'im.', 'präposition', 'Umweltschutz'],
      ['der Klimawandel', '—', 'تغيّر المناخ', 'Der Klimawandel ist eine Tatsache.', 'Der Klimawandel ist eine Tatsache gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Klimawandel'],
      ['der Müll', '—', 'النفايات', 'Der Müll wird getrennt.', 'Der Müll wird trennen.', 'المجهول: getrennt.', 'konjugation', 'Müll'],
      ['die Mülltrennung', '—', 'فرز النفايات', 'Die Mülltrennung ist hier Pflicht.', 'Die Mülltrennung ist hier Pflicht gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Mülltrennung'],
      ['der Abfall', 'die Abfälle', 'الفضلات', 'Der Abfall wird abgeholt.', 'Der Abfall wird abholen.', 'المجهول: abgeholt.', 'konjugation', 'Abfall'],
      ['der Plastik', '—', 'البلاستيك', 'Plastik braucht Jahrhunderte.', 'Plastik braucht Jahrhunderte es.', 'لا ضمير زائد.', 'wortstellung', 'Plastik'],
      ['das Recycling', '—', 'إعادة التدوير', 'Recycling spart Energie.', 'Recycling spart Energie es.', 'لا ضمير زائد.', 'wortstellung', 'Recycling'],
      ['die Energie', 'die Energien', 'الطاقة', 'Die Energie kommt von der Sonne.', 'Die Energie kommt aus der Sonne.', 'von لا aus (المصدر).', 'präposition', 'Energie'],
      ['der Strom', '—', 'التيار الكهربائي', 'Der Strom wird teurer.', 'Der Strom wird teurer es.', 'لا ضمير زائد.', 'wortstellung', 'Strom'],
      ['die Sonnenenergie', '—', 'الطاقة الشمسية', 'Die Sonnenenergie ist unerschöpflich.', 'Die Sonnenenergie ist unerschöpflich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Sonnenenergie'],
      ['die Windkraft', '—', 'طاقة الرياح', 'Die Windkraft wächst schnell.', 'Die Windkraft wächst schnell es.', 'لا ضمير زائد.', 'wortstellung', 'Windkraft'],
      ['erneuerbar', '—', 'متجدّد', 'Erneuerbare Energien sind wichtig.', 'Erneuerbar Energien sind wichtig.', 'الصفة: erneuerbare.', 'deklination', 'Erneuerbare'],
      ['das Wasser', '—', 'الماء', 'Wasser ist knapp.', 'Wasser ist knapp es.', 'لا ضمير زائد.', 'wortstellung', 'Wasser'],
      ['der Verbrauch', 'die Verbräuche', 'الاستهلاك', 'Der Verbrauch ist gesunken.', 'Der Verbrauch ist gesunken gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Verbrauch'],
      ['verbrauchen', 'verbraucht · verbrauchte · hat verbraucht', 'يستهلك', 'Wir verbrauchen zu viel Strom.', 'Wir verbrauchen zu viel Strom für.', 'بلا حرف جر.', 'kasus', 'verbrauchen'],
      ['sparen', 'spart · sparte · hat gespart', 'يوفّر', 'So sparst du Wasser.', 'So du sparst Wasser.', 'الفعل ثانٍ.', 'wortstellung', 'sparst'],
      ['schützen', 'schützt · schützte · hat geschützt', 'يحمي', 'Diese Regeln schützen die Natur.', 'Diese Regeln schützen für die Natur.', 'بلا حرف جر.', 'kasus', 'schützen'],
      ['verschmutzen', 'verschmutzt · verschmutzte · hat verschmutzt', 'يلوّث', 'Fabriken verschmutzen die Flüsse.', 'Fabriken verschmutzen für die Flüsse.', 'بلا حرف جر.', 'kasus', 'verschmutzen'],
      ['die Verschmutzung', 'die Verschmutzungen', 'التلوّث', 'Die Verschmutzung der Luft ist gefährlich.', 'Die Verschmutzung von der Luft ist gefährlich.', 'Genitiv أفضل.', 'kasus', 'Verschmutzung'],
      ['die Luft', '—', 'الهواء', 'Die Luft ist hier sauber.', 'Die Luft ist hier sauber gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Luft'],
      ['das Klima', '—', 'المناخ', 'Das Klima hat sich verändert.', 'Das Klima hat verändert.', 'الانعكاس: sich verändert.', 'konjugation', 'Klima'],
      ['die Temperatur', 'die Temperaturen', 'الحرارة', 'Die Temperaturen steigen.', 'Die Temperaturen steigen es.', 'لا ضمير زائد.', 'wortstellung', 'Temperaturen'],
      ['die Trockenheit', '—', 'الجفاف', 'Die Trockenheit dauert Monate.', 'Die Trockenheit dauert für Monate.', 'بلا حرف جر.', 'präposition', 'Trockenheit'],
      ['das Hochwasser', 'die Hochwasser', 'الفيضان', 'Das Hochwasser zerstörte die Felder.', 'Das Hochwasser hat die Felder zerstört gehabt.', 'السرد: zerstörte.', 'konjugation', 'Hochwasser'],
      ['die Wetterkatastrophe', 'die Wetterkatastrophen', 'كارثة مناخية', 'Die Wetterkatastrophen nehmen zu.', 'Die Wetterkatastrophen nehmen zu es.', 'لا ضمير زائد.', 'wortstellung', 'Wetterkatastrophen'],
      ['die Dürre', 'die Dürren', 'الجدب', 'Die Dürre trifft die Bauern.', 'Die Dürre trifft auf die Bauern.', 'بلا حرف جر.', 'kasus', 'Dürre'],
      ['die Ernte', 'die Ernten', 'الحصاد', 'Die Ernte war schlecht.', 'Die Ernte war schlecht gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Ernte'],
      ['der Boden', 'die Böden', 'التربة', 'Der Boden verliert Wasser.', 'Der Boden verliert Wasser es.', 'لا ضمير زائد.', 'wortstellung', 'Boden'],
      ['das Artenschutz', '—', 'حماية الأنواع', 'Artenschutz ist Tierschutz.', 'Artenschutz ist Tierschutz es.', 'لا ضمير زائد.', 'wortstellung', 'Artenschutz'],
      ['die Art', 'die Arten', 'النوع', 'Viele Arten verschwinden.', 'Viele Arten verschwinden es.', 'لا ضمير زائد.', 'wortstellung', 'Arten'],
      ['der Wald', 'die Wälder', 'الغابة', 'Der Wald wird geschützt.', 'Der Wald wird schützen.', 'المجهول: geschützt.', 'konjugation', 'Wald'],
      ['das Meer', 'die Meere', 'البحر', 'Das Meer ist voller Plastik.', 'Das Meer ist voller Plastik gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Meer'],
      ['der Küstenstreifen', 'die Küstenstreifen', 'الشريط الساحلي', 'Der Küstenstreifen braucht Schutz.', 'Der Küstenstreifen braucht ein Schutz.', 'Schutz بلا أداة.', 'lexik-kollokation', 'Küstenstreifen'],
      ['das Verbot', 'die Verbote', 'المنع', 'Das Verbot gilt ab Januar.', 'Das Verbot gilt von Januar.', 'ab لا von.', 'präposition', 'Verbot'],
      ['die Vorschrift', 'die Vorschriften', 'اللائحة', 'Die Vorschrift ist neu.', 'Die Vorschrift ist neu gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Vorschrift'],
      ['die Maßnahme', 'die Maßnahmen', 'الإجراء', 'Die Maßnahme greift langsam.', 'Die Maßnahme greift langsam es.', 'لا ضمير زائد.', 'wortstellung', 'Maßnahme'],
      ['nachhaltig', '—', 'مستدام', 'Nachhaltiges Wirtschaften ist nötig.', 'Nachhaltig Wirtschaften ist nötig.', 'الصفة: nachhaltiges.', 'deklination', 'Nachhaltiges'],
      ['bewusst', '—', 'واعٍ', 'Ich lebe bewusst.', 'Ich lebe bewusst es.', 'لا ضمير زائد.', 'wortstellung', 'bewusst'],
      ['verzichten', 'verzichtet · verzichtete · hat verzichtet', 'يتنازل', 'Wir verzichten auf Plastiktüten.', 'Wir verzichten die Plastiktüten.', 'verzichten auf.', 'präposition', 'verzichten']
    ],
    tricks: [
      { trick: 'البيئة بأفعالها: schützen · sparen · trennen · verzichten auf', wie: 'Wir schützen die Umwelt. · Wir verzichten auf Plastiktüten.', warum: 'العربية تقول «نحمي البيئة من البلاستيك»، والألمانية تربط كل فعل بحرفه الخاص.', anchor: 'schützen' },
      { trick: 'النص البيئي الرسمي: die Verschmutzung · der Verbrauch · die Maßnahme', wie: 'Der Verbrauch ist gesunken. · Die Maßnahme greift langsam.', warum: 'الأسماء تحمل الحجة في الألمانية المكتوبة، والعربية تفضّل الأفعال.', anchor: 'der Verbrauch' },
      { trick: 'أشهر صفة في الملف: Erneuerbare Energien — الاسم معها يعرَّف بالأداة', wie: 'Erneuerbare Energien sind wichtig. · Wir brauchen saubere Energie.', warum: 'الصفة قبل الجمع بلا أداة تأخذ en، والناطق العربي ينساها فتضيع القراءة.', anchor: 'erneuerbar' }
    ]
  }

};
