/* Deutschweg — B1 lexical layer, unit 5 (part a): b1-u5-l1 … b1-u5-l3.
   40 items per lesson, the count the B1 rows declare (amendment B1-L1).
   Appended to tools/vocab-b1.js as each lesson is finished. */

module.exports = {

  'b1-u5-l1': {
    items: [
      ['der Kommentar', 'die Kommentare', 'التعليق', 'Der Kommentar ist sachlich geschrieben.', 'Der Kommentar ist sachlich schreiben.', 'الصفة + Partizip II.', 'konjugation', 'Kommentar'],
      ['kommentieren', 'kommentiert · kommentierte · hat kommentiert', 'يعلّق', 'Er kommentiert die neue Regel.', 'Er kommentiert über die neue Regel.', 'بلا حرف جر.', 'kasus', 'kommentiert'],
      ['die Meinung', 'die Meinungen', 'الرأي', 'Meine Meinung weicht davon ab.', 'Meine Meinung weicht davon.', 'المنفصل: ab.', 'wortstellung', 'ab'],
      ['die Behauptung', 'die Behauptungen', 'الادّعاء', 'Die Behauptung bleibt unbewiesen.', 'Die Behauptung bleibt unbewiesen gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Behauptung'],
      ['die These', 'die Thesen', 'الأطروحة', 'Die These ist gewagt.', 'Die These ist gewagt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'These'],
      ['das Argument', 'die Argumente', 'الحجة', 'Dieses Argument überzeugt mich.', 'Dieses Argument überzeugt mich es.', 'لا ضمير زائد.', 'wortstellung', 'Argument'],
      ['der Beweis', 'die Beweise', 'الدليل', 'Der Beweis fehlt.', 'Der Beweis fehlt es.', 'لا ضمير زائد.', 'wortstellung', 'Beweis'],
      ['der Beleg', 'die Belege', 'الإثبات', 'Ohne Beleg bleibt es eine Meinung.', 'Ohne ein Beleg bleibt es eine Meinung.', 'بعد ohne بلا أداة.', 'kasus', 'Beleg'],
      ['die Statistik', 'die Statistiken', 'الإحصاء', 'Die Statistik stützt meine These.', 'Die Statistik stützt für meine These.', 'بلا حرف جر.', 'kasus', 'Statistik'],
      ['das Beispiel', 'die Beispiele', 'المثال', 'Ein Beispiel macht es greifbar.', 'Ein Beispiel macht es greifbar es.', 'لا ضمير زائد.', 'wortstellung', 'Beispiel'],
      ['der Vergleich', 'die Vergleiche', 'المقارنة', 'Der Vergleich hinkt.', 'Der Vergleich hinkt es.', 'لا ضمير زائد.', 'wortstellung', 'Vergleich'],
      ['der Widerspruch', 'die Widersprüche', 'التناقض', 'Da steckt ein Widerspruch drin.', 'Da steckt ein Widerspruch drin es.', 'لا ضمير زائد.', 'wortstellung', 'Widerspruch'],
      ['die Schlussfolgerung', 'die Schlussfolgerungen', 'الاستنتاج', 'Die Schlussfolgerung ist voreilig.', 'Die Schlussfolgerung ist voreilig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Schlussfolgerung'],
      ['die Stellungnahme', 'die Stellungnahmen', 'بيان الموقف', 'Die Stellungnahme war knapp.', 'Die Stellungnahme war knapp gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Stellungnahme'],
      ['das Fazit', 'die Fazits', 'الخلاصة', 'Das Fazit überrascht nicht.', 'Das Fazit überrascht nicht es.', 'لا ضمير زائد.', 'wortstellung', 'Fazit'],
      ['die Einleitung', 'die Einleitungen', 'المقدمة', 'Die Einleitung führt zum Thema hin.', 'Die Einleitung führt zu das Thema hin.', 'zu + داتيف: zum.', 'kasus', 'Einleitung'],
      ['der Hauptteil', 'die Hauptteile', 'المتن', 'Im Hauptteil kommen die Argumente.', 'In Hauptteil kommen die Argumente.', 'im.', 'präposition', 'Hauptteil'],
      ['der Schluss', 'die Schlüsse', 'الخاتمة', 'Der Schluss wiederholt die These.', 'Der Schluss wiederholt die These es.', 'لا ضمير زائد.', 'wortstellung', 'Schluss'],
      ['das Thema', 'die Themen', 'الموضوع', 'Das Thema wird kontrovers diskutiert.', 'Das Thema wird kontrovers diskutieren.', 'المجهول: diskutiert.', 'konjugation', 'Thema'],
      ['die Überschrift', 'die Überschriften', 'العنوان', 'Die Überschrift macht neugierig.', 'Die Überschrift macht neugierig es.', 'لا ضمير زائد.', 'wortstellung', 'Überschrift'],
      ['die Zeitschrift', 'die Zeitschriften', 'المجلة', 'Die Zeitschrift sucht Leserbriefe.', 'Die Zeitschrift sucht für Leserbriefe.', 'بلا حرف جر.', 'kasus', 'Zeitschrift'],
      ['der Leserbrief', 'die Leserbriefe', 'رسالة القارئ', 'Der Leserbrief ist kurz und klar.', 'Der Leserbrief ist kurz und klar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Leserbrief'],
      ['kritisieren', 'kritisiert · kritisierte · hat kritisiert', 'ينقد', 'Die Zeitung kritisiert den Beschluss.', 'Die Zeitung kritisiert über den Beschluss.', 'بلا حرف جر.', 'kasus', 'kritisiert'],
      ['loben', 'lobt · lobte · hat gelobt', 'يمدح', 'Der Autor lobt die neue Regelung.', 'Der Autor lobt für die neue Regelung.', 'بلا حرف جر.', 'kasus', 'lobt'],
      ['befürworten', 'befürwortet · befürwortete · hat befürwortet', 'يؤيّد', 'Ich befürworte den Vorschlag.', 'Ich befürworte für den Vorschlag.', 'بلا حرف جر.', 'kasus', 'befürworte'],
      ['ablehnen', 'lehnt ab · lehnte ab · hat abgelehnt', 'يرفض', 'Ich lehne den Plan ab.', 'Ich lehne den Plan.', 'المنفصل: ab.', 'wortstellung', 'ab'],
      ['der Vorschlag', 'die Vorschläge', 'الاقتراح', 'Sein Vorschlag ist vernünftig.', 'Sein Vorschlag ist vernünftig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Vorschlag'],
      ['vernünftig', '—', 'معقول', 'Das ist die vernünftigste Lösung.', 'Das ist die vernünftig Lösung.', 'التفضيل: vernünftigste.', 'deklination', 'vernünftigste'],
      ['übertreiben', 'übertreibt · übertrieb · hat übertrieben', 'يبالغ', 'Der Autor übertreibt maßlos.', 'Der Autor übertreibt maßlos es.', 'لا ضمير زائد.', 'wortstellung', 'übertreibt'],
      ['die Übertreibung', 'die Übertreibungen', 'المبالغة', 'Die Übertreibung schwächt den Text.', 'Die Übertreibung schwächt den Text es.', 'لا ضمير زائد.', 'wortstellung', 'Übertreibung'],
      ['sachlich', '—', 'موضوعي', 'Bleib sachlich!', 'Bleib sachlich du!', 'التعليمة بلا ضمير.', 'wortstellung', 'sachlich'],
      ['emotional', '—', 'عاطفي', 'Die Debatte wurde emotional.', 'Die Debatte wurde emotional gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'emotional'],
      ['der Ton', 'die Töne', 'اللهجة', 'Der Ton macht die Musik.', 'Der Ton macht die Musik es.', 'لا ضمير زائد.', 'wortstellung', 'Ton'],
      ['die Wortwahl', '—', 'اختيار الكلمات', 'Die Wortwahl ist entscheidend.', 'Die Wortwahl ist entscheidend gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Wortwahl'],
      ['der Stil', 'die Stile', 'الأسلوب', 'Der Stil ist klar und knapp.', 'Der Stil ist klar und knapp gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Stil'],
      ['der Leser', 'die Leser', 'القارئ', 'Die Leser reagierten empört.', 'Die Leser haben empört reagiert gehabt.', 'السرد: reagierten.', 'konjugation', 'Leser'],
      ['die Öffentlichkeit', '—', 'الرأي العام', 'Die Öffentlichkeit diskutiert darüber.', 'Die Öffentlichkeit diskutiert über das.', 'über لا بلا حرف مع الظرف: darüber.', 'präposition', 'Öffentlichkeit'],
      ['die Debatte', 'die Debatten', 'الجدل', 'Die Debatte läuft seit Wochen.', 'Die Debatte läuft von Wochen.', 'منذ: seit.', 'präposition', 'Debatte'],
      ['die Meinungsfreiheit', '—', 'حرية التعبير', 'Meinungsfreiheit ist ein Grundrecht.', 'Meinungsfreiheit ist ein Grundrecht es.', 'لا ضمير زائد.', 'wortstellung', 'Meinungsfreiheit'],
      ['der Standpunkt', 'die Standpunkte', 'الموقف', 'Ich verstehe deinen Standpunkt nicht.', 'Ich verstehe dein Standpunkt nicht.', 'مذكر نصب: deinen.', 'kasus', 'Standpunkt']
    ],
    tricks: [
      { trick: 'بنية نص الرأي: Einleitung mit These · Hauptteil mit Argumenten · Schluss mit Fazit', wie: 'In der Einleitung steht die These, im Hauptteil die Argumente, im Schluss das Fazit.', warum: 'النص العربي يبني الحجة بالمقابلة، والألمانية تُقيَّم على الإعلان الواضح عن الأطروحة أولًا.', anchor: 'die These' },
      { trick: 'لكل حجة شاهدها: ein Beispiel · eine Statistik · ein Zitat', wie: 'Mein Argument stützt sich auf eine Statistik. Zum Beispiel …', warum: 'الحجة بلا شاهد تُعدّ رأيًا لا حجة، وهذا الفرق هو ما يقيسه الممتحن.', anchor: 'das Beispiel' },
      { trick: 'النبرة تُقاس: sachlich · der Ton · die Wortwahl · die Übertreibung', wie: 'Bleib sachlich, vermeide Übertreibungen.', warum: 'العربية تحبّ التوكيد والمبالغة، والألمانية المكتوبة تعتبره ضعفًا في الحجة.', anchor: 'sachlich' }
    ]
  },

  'b1-u5-l2': {
    items: [
      ['würden', 'würde · wurde · hat gewollt', 'لو (مهذّب)', 'Wenn Sie mir helfen würden, wäre ich dankbar.', 'Wenn Sie mir helfen werden, wäre ich dankbar.', 'الشرط المهذّب: würden لا werden.', 'konjugation', 'würden'],
      ['könnten', 'kann · konnte · hat gekonnt', 'يمكن (مهذّب)', 'Könnten Sie das wiederholen?', 'Können Sie das wiederholen gewesen?', 'الأدب: könnten.', 'konjugation', 'Könnten'],
      ['dürfte', 'darf · durfte · hat gedurft', 'يُسمح (مهذّب)', 'Dürfte ich kurz etwas fragen?', 'Darf ich kurz etwas fragen gewesen?', 'الأدب: dürfte.', 'konjugation', 'Dürfte'],
      ['hätte', 'hat · hatte · hat gehabt', 'لو كان عندي', 'Ich hätte eine Bitte.', 'Ich habe eine Bitte gewesen.', 'الطلب المهذّب: hätte.', 'konjugation', 'hätte'],
      ['wäre', 'ist · war · ist gewesen', 'لو كان', 'Es wäre nett, wenn Sie mir schreiben.', 'Es ist nett gewesen, wenn Sie mir schreiben.', 'الشرط المهذّب: wäre.', 'konjugation', 'wäre'],
      ['falls', '—', 'في حال', 'Falls es Ihnen passt, komme ich morgen.', 'Falls es passt Ihnen, komme ich morgen.', 'الفعل في نهاية جملة falls.', 'wortstellung', 'Falls'],
      ['sofern', '—', 'بشرط أن', 'Sofern Sie einverstanden sind, machen wir weiter.', 'Sofern Sie sind einverstanden, machen wir weiter.', 'الفعل في النهاية.', 'wortstellung', 'Sofern'],
      ['unter der Bedingung', '—', 'بشرط', 'Unter der Bedingung, dass Sie zustimmen.', 'Unter der Bedingung, dass Sie zustimmen es.', 'لا ضمير زائد.', 'wortstellung', 'Bedingung'],
      ['die Bedingung', 'die Bedingungen', 'الشرط', 'Die Bedingungen sind klar.', 'Die Bedingungen sind klar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Bedingungen'],
      ['die Bitte', 'die Bitten', 'الرجاء', 'Ich habe eine große Bitte.', 'Ich habe ein große Bitte.', 'مؤنث: eine.', 'genus', 'Bitte'],
      ['bitten', 'bittet · bat · hat gebeten', 'يرجو', 'Ich bitte Sie um Geduld.', 'Ich bitte Sie für Geduld.', 'bitten um.', 'präposition', 'bitte'],
      ['die Anfrage', 'die Anfragen', 'الاستفسار', 'Die Anfrage wurde weitergeleitet.', 'Die Anfrage wurde weiterleiten.', 'المجهول: weitergeleitet.', 'konjugation', 'Anfrage'],
      ['der Vorschlag', 'die Vorschläge', 'الاقتراح', 'Mein Vorschlag wäre ein Kompromiss.', 'Mein Vorschlag ist ein Kompromiss gewesen.', 'الاقتراح المهذّب: wäre.', 'konjugation', 'Vorschlag'],
      ['vorschlagen', 'schlägt vor · schlug vor · hat vorgeschlagen', 'يقترح', 'Ich würde vorschlagen, dass wir warten.', 'Ich würde vorschlagen, dass wir warten es.', 'لا ضمير زائد.', 'wortstellung', 'vorschlagen'],
      ['der Wunsch', 'die Wünsche', 'الرغبة', 'Haben Sie einen Wunsch?', 'Haben Sie ein Wunsch?', 'مذكر نصب: einen.', 'kasus', 'Wunsch'],
      ['die Möglichkeit', 'die Möglichkeiten', 'الإمكانية', 'Wäre eine Verlängerung eine Möglichkeit?', 'Ist eine Verlängerung eine Möglichkeit gewesen?', 'الاستفسار المهذّب: wäre.', 'konjugation', 'Möglichkeit'],
      ['eventuell', '—', 'ربما', 'Eventuell könnten wir tauschen.', 'Eventuell wir könnten tauschen.', 'الفعل ثانٍ.', 'wortstellung', 'Eventuell'],
      ['gegebenenfalls', '—', 'عند الحاجة', 'Gegebenenfalls verlängern wir den Vertrag.', 'Gegebenenfalls wir verlängern den Vertrag.', 'الفعل ثانٍ.', 'wortstellung', 'Gegebenenfalls'],
      ['notfalls', '—', 'عند الضرورة', 'Notfalls rufe ich später an.', 'Notfalls ich rufe später an.', 'الفعل ثانٍ.', 'wortstellung', 'Notfalls'],
      ['auf keinen Fall', '—', 'مستحيل', 'Auf keinen Fall!', 'Auf kein Fall!', 'keinen Fall (نصب).', 'kasus', 'Fall'],
      ['die Rücksprache', 'die Rücksprachen', 'التشاور', 'Nach Rücksprache mit dem Chef …', 'Nach Rücksprache mit der Chef …', 'mit dem Chef.', 'kasus', 'Rücksprache'],
      ['sich erkundigen', 'erkundigt sich · erkundigte sich · hat sich erkundigt', 'يستفسر', 'Ich erkundige mich nach dem Termin.', 'Ich erkundige mich für den Termin.', 'nach لا für.', 'präposition', 'erkundige'],
      ['nachfragen', 'fragt nach · fragte nach · hat nachgefragt', 'يستفسر', 'Ich frage morgen nach.', 'Ich frage morgen nach es.', 'لا ضمير زائد.', 'wortstellung', 'nach'],
      ['sich wenden an', 'wendet sich · wandte sich · hat sich gewandt', 'يتوجّه إلى', 'Wenden Sie sich an das Sekretariat.', 'Wenden Sie sich zu dem Sekretariat.', 'an لا zu.', 'präposition', 'wenden'],
      ['der Ansprechpartner', 'die Ansprechpartner', 'جهة الاتصال', 'Mein Ansprechpartner ist Herr Klein.', 'Mein Ansprechpartner ist Herr Klein es.', 'لا ضمير زائد.', 'wortstellung', 'Ansprechpartner'],
      ['die Auskunft', 'die Auskünfte', 'المعلومة', 'Für Auskünfte bin ich dankbar.', 'Für Auskünfte ich bin dankbar.', 'الفعل ثانٍ.', 'wortstellung', 'Auskünfte'],
      ['die Zustimmung', 'die Zustimmungen', 'الموافقة', 'Die Zustimmung fehlt noch.', 'Die Zustimmung fehlt noch es.', 'لا ضمير زائد.', 'wortstellung', 'Zustimmung'],
      ['zustimmen', 'stimmt zu · stimmte zu · hat zugestimmt', 'يوافق', 'Wenn Sie dem zustimmen würden, …', 'Wenn Sie das zustimmen würden, …', 'داتيف: dem.', 'kasus', 'zustimmen'],
      ['die Absage', 'die Absagen', 'الرفض', 'Eine Absage wäre enttäuschend.', 'Eine Absage ist enttäuschend gewesen.', 'المهذّب: wäre.', 'konjugation', 'Absage'],
      ['die Zusage', 'die Zusagen', 'القبول', 'Über eine Zusage würde ich mich freuen.', 'Über eine Zusage ich würde mich freuen.', 'الفعل ثانٍ.', 'wortstellung', 'Zusage'],
      ['die Frist', 'die Fristen', 'المهلة', 'Bis Ende der Frist können Sie tauschen.', 'Bis Ende der Frist Sie können tauschen.', 'الفعل ثانٍ.', 'wortstellung', 'Frist'],
      ['die Verlängerung', 'die Verlängerungen', 'التمديد', 'Ich würde um eine Verlängerung bitten.', 'Ich würde für eine Verlängerung bitten.', 'bitten um.', 'präposition', 'Verlängerung'],
      ['der Aufschub', 'die Aufschübe', 'التأجيل', 'Ein kurzer Aufschub wäre hilfreich.', 'Ein kurzer Aufschub ist hilfreich gewesen.', 'المهذّب: wäre.', 'konjugation', 'Aufschub'],
      ['die Alternative', 'die Alternativen', 'البديل', 'Gäbe es eine Alternative?', 'Gibt es eine Alternative gehabt?', 'الافتراض: gäbe.', 'konjugation', 'Alternative'],
      ['der Kompromiss', 'die Kompromisse', 'الحل الوسط', 'Wäre ein Kompromiss denkbar?', 'Ist ein Kompromiss denkbar gewesen?', 'المقترح المهذّب: wäre.', 'konjugation', 'Kompromiss'],
      ['entgegenkommen', 'kommt entgegen · kam entgegen · ist entgegengekommen', 'يجاري', 'Wir können Ihnen entgegenkommen.', 'Wir können Ihnen entgegenkommen du.', 'لا ضمير زائد.', 'wortstellung', 'entgegenkommen'],
      ['berücksichtigen', 'berücksichtigt · berücksichtigte · hat berücksichtigt', 'يراعي', 'Wir werden Ihren Wunsch berücksichtigen.', 'Wir werden Ihren Wunsch berücksichtigen für.', 'بلا حرف جر.', 'kasus', 'berücksichtigen'],
      ['dankbar', '—', 'شاكر', 'Ich wäre Ihnen sehr dankbar.', 'Ich bin Ihnen sehr dankbar gewesen.', 'المهذّب: wäre.', 'konjugation', 'dankbar'],
      ['die Zusage geben', 'gibt · gab · hat gegeben', 'يعطي موافقة', 'Könnten Sie mir eine Zusage geben?', 'Könnten Sie mir eine Zusage geben du?', 'لا ضمير زائد في الطلب المهذّب.', 'wortstellung', 'geben'],
      ['verbindlich', '—', 'ملزم', 'Eine verbindliche Zusage wäre gut.', 'Eine verbindlich Zusage wäre gut.', 'الصفة: verbindliche.', 'deklination', 'verbindliche']
    ],
    tricks: [
      { trick: 'الطلب المهذّب لا يأمر: Würden Sie … · Könnten Sie … · Ich hätte eine Bitte', wie: 'Könnten Sie das wiederholen? · Ich hätte eine Bitte.', warum: 'العربية تستعمل الأمر المباشر أو «من فضلك»، والألمانية تعتبر صيغة الأمر في الطلب الرسمي فظاظة.', anchor: 'würden' },
      { trick: 'الشرط المهذّب: falls · sofern · unter der Bedingung, dass …', wie: 'Falls es Ihnen passt, komme ich morgen. · Sofern Sie einverstanden sind, …', warum: 'الشرط في العربية يُفهم من السياق، والألمانية تحتاج رابطًا يدفع الفعل إلى النهاية.', anchor: 'falls' },
      { trick: 'الرفض المهذّب أيضًا بصيغة الافتراض: Das wäre schwierig · Da müsste ich fragen', wie: 'Das wäre schwierig. · Da müsste ich erst fragen.', warum: 'العربية تقول «لا يمكن» مباشرة، والألمانية تخفّف بالافتراض فتبدو مهنية.', anchor: 'wäre' }
    ]
  },

  'b1-u5-l3': {
    items: [
      ['das System', 'die Systeme', 'النظام', 'Das System ist anders aufgebaut.', 'Das System ist anders aufbauen.', 'الصفة + Partizip II.', 'konjugation', 'System'],
      ['das Bildungssystem', 'die Bildungssysteme', 'النظام التعليمي', 'Das Bildungssystem unterscheidet sich stark.', 'Das Bildungssystem unterscheidet sich stark es.', 'لا ضمير زائد.', 'wortstellung', 'Bildungssystem'],
      ['das Gesundheitssystem', 'die Gesundheitssysteme', 'النظام الصحي', 'Das Gesundheitssystem ist teuer.', 'Das Gesundheitssystem ist teuer gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Gesundheitssystem'],
      ['das Steuersystem', 'die Steuersysteme', 'النظام الضريبي', 'Das Steuersystem ist kompliziert.', 'Das Steuersystem ist kompliziert gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Steuersystem'],
      ['das Schulsystem', 'die Schulsysteme', 'النظام المدرسي', 'Das Schulsystem ist dreigliedrig.', 'Das Schulsystem ist dreigliedrig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Schulsystem'],
      ['der Vergleich', 'die Vergleiche', 'المقارنة', 'Der Vergleich zeigt große Unterschiede.', 'Der Vergleich zeigt große Unterschied.', 'الجمع: Unterschiede.', 'plural', 'Vergleich'],
      ['vergleichen', 'vergleicht · verglich · hat verglichen', 'يقارن', 'Vergleiche die beiden Systeme!', 'Vergleiche mit die beiden Systeme!', 'بلا حرف جر.', 'kasus', 'Vergleiche'],
      ['der Unterschied', 'die Unterschiede', 'الفرق', 'Der Unterschied ist deutlich.', 'Der Unterschied ist deutlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Unterschied'],
      ['die Ähnlichkeit', 'die Ähnlichkeiten', 'الشبه', 'Die Ähnlichkeit überrascht.', 'Die Ähnlichkeit überrascht es.', 'لا ضمير زائد.', 'wortstellung', 'Ähnlichkeit'],
      ['der Vorteil', 'die Vorteile', 'الميزة', 'Jedes System hat Vorteile.', 'Jedes System hat Vorteile es.', 'لا ضمير زائد.', 'wortstellung', 'Vorteile'],
      ['der Nachteil', 'die Nachteile', 'العيب', 'Der Nachteil liegt in den Kosten.', 'Der Nachteil liegt in die Kosten.', 'in + داتيف.', 'kasus', 'Nachteil'],
      ['im Gegensatz zu', '—', 'على عكس', 'Im Gegensatz zu Deutschland ist das hier gratis.', 'Im Gegensatz mit Deutschland ist das hier gratis.', 'zu لا mit.', 'präposition', 'Gegensatz'],
      ['im Vergleich zu', '—', 'بالمقارنة مع', 'Im Vergleich zu früher lernen die Kinder mehr.', 'Im Vergleich mit früher lernen die Kinder mehr.', 'zu لا mit.', 'präposition', 'Vergleich'],
      ['dagegen', '—', 'في المقابل', 'In Tunesien ist es warm, dagegen ist es hier kalt.', 'In Tunesien ist es warm, dagegen es ist hier kalt.', 'الفعل ثانٍ.', 'wortstellung', 'dagegen'],
      ['hingegen', '—', 'بينما', 'Hier zahlt man bar, dort hingegen mit Karte.', 'Hier zahlt man bar, dort hingegen man zahlt mit Karte.', 'الفعل ثانٍ.', 'wortstellung', 'hingegen'],
      ['während', '—', 'بينما (مقابلة)', 'Während die einen sparen, geben die anderen aus.', 'Während die einen sparen, die anderen geben aus.', 'الفعل ثانٍ في الرئيسية.', 'wortstellung', 'Während'],
      ['einerseits', '—', 'من جهة', 'Einerseits ist es billig, andererseits langsam.', 'Einerseits es ist billig, andererseits langsam.', 'الفعل ثانٍ.', 'wortstellung', 'einerseits'],
      ['andererseits', '—', 'من جهة أخرى', 'Andererseits spart man Zeit.', 'Andererseits man spart Zeit.', 'الفعل ثانٍ.', 'wortstellung', 'andererseits'],
      ['die Grundlage', 'die Grundlagen', 'الأساس', 'Bildung ist die Grundlage der Demokratie.', 'Bildung ist die Grundlage von der Demokratie.', 'Genitiv أفضل.', 'kasus', 'Grundlage'],
      ['die Gesellschaft', 'die Gesellschaften', 'المجتمع', 'Die Gesellschaft verändert sich.', 'Die Gesellschaft hat sich verändert gehabt.', 'الحاضر: verändert sich.', 'konjugation', 'Gesellschaft'],
      ['die Politik', 'die Politiken', 'السياسة', 'Die Politik reagiert langsam.', 'Die Politik reagiert langsam es.', 'لا ضمير زائد.', 'wortstellung', 'Politik'],
      ['die Politik verdient', 'verdient · verdiente · hat verdient', 'يستحق', 'Diese Frage verdient Aufmerksamkeit.', 'Diese Frage verdient für Aufmerksamkeit.', 'بلا حرف جر.', 'kasus', 'verdient'],
      ['die Reform', 'die Reformen', 'الإصلاح', 'Die Reform greift 2027.', 'Die Reform greift in 2027.', 'بلا حرف جر مع السنة.', 'präposition', 'Reform'],
      ['die Verwaltung', 'die Verwaltungen', 'الإدارة', 'Die Verwaltung arbeitet langsam.', 'Die Verwaltung arbeitet langsam es.', 'لا ضمير زائد.', 'wortstellung', 'Verwaltung'],
      ['die Bürokratie', '—', 'البيروقراطية', 'Die Bürokratie kostet Zeit.', 'Die Bürokratie kostet eine Zeit.', 'Zeit بلا أداة.', 'lexik-kollokation', 'Bürokratie'],
      ['der Beamte', 'die Beamten', 'الموظّف الرسمي', 'Der Beamte prüft die Unterlagen.', 'Der Beamte prüft für die Unterlagen.', 'بلا حرف جر.', 'kasus', 'Beamte'],
      ['die Steuer', 'die Steuern', 'الضريبة', 'Die Steuern sind gesunken.', 'Die Steuern sind sinken.', 'الماضي المركّب: gesunken.', 'konjugation', 'Steuern'],
      ['die Krankenkasse', 'die Krankenkassen', 'صندوق التأمين الصحي', 'Die Krankenkasse zahlt die Behandlung.', 'Die Krankenkasse zahlt für die Behandlung.', 'بلا حرف جر.', 'kasus', 'Krankenkasse'],
      ['die Versicherung', 'die Versicherungen', 'التأمين', 'In Deutschland ist die Versicherung Pflicht.', 'In Deutschland die Versicherung ist Pflicht.', 'الفعل ثانٍ.', 'wortstellung', 'Versicherung'],
      ['die Rente', 'die Renten', 'المعاش', 'Die Rente reicht kaum.', 'Die Rente reicht kaum es.', 'لا ضمير زائد.', 'wortstellung', 'Rente'],
      ['die Arbeitslosigkeit', '—', 'البطالة', 'Die Arbeitslosigkeit sinkt langsam.', 'Die Arbeitslosigkeit sinkt langsam es.', 'لا ضمير زائد.', 'wortstellung', 'Arbeitslosigkeit'],
      ['der Arbeitsmarkt', 'die Arbeitsmärkte', 'سوق العمل', 'Der Arbeitsmarkt verlangt Flexibilität.', 'Der Arbeitsmarkt verlangt für Flexibilität.', 'بلا حرف جر.', 'kasus', 'Arbeitsmarkt'],
      ['die Wirtschaft', 'die Wirtschaften', 'الاقتصاد', 'Die Wirtschaft wächst wieder.', 'Die Wirtschaft wächst wieder es.', 'لا ضمير زائد.', 'wortstellung', 'Wirtschaft'],
      ['das Wachstum', '—', 'النمو', 'Das Wachstum bleibt schwach.', 'Das Wachstum bleibt schwach gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Wachstum'],
      ['die Krise', 'die Krisen', 'الأزمة', 'Die Krise traf alle Branchen.', 'Die Krise traf für alle Branchen.', 'بلا حرف جر.', 'kasus', 'Krise'],
      ['der Haushalt', 'die Haushalte', 'الميزانية/الأسرة', 'Der Haushalt muss sparen.', 'Der Haushalt muss sparen es.', 'لا ضمير زائد.', 'wortstellung', 'Haushalt'],
      ['der Bürger', 'die Bürger', 'المواطن', 'Die Bürger fordern Transparenz.', 'Die Bürger fordern für Transparenz.', 'بلا حرف جر.', 'kasus', 'Bürger'],
      ['die Demokratie', 'die Demokratien', 'الديمقراطية', 'Die Demokratie lebt von Beteiligung.', 'Die Demokratie lebt von die Beteiligung.', 'von + داتيف: der.', 'kasus', 'Demokratie'],
      ['die Beteiligung', 'die Beteiligungen', 'المشاركة', 'Die Beteiligung der Bürger ist wichtig.', 'Die Beteiligung von den Bürgern ist wichtig.', 'Genitiv أفضل.', 'kasus', 'Beteiligung'],
      ['die Transparenz', '—', 'الشفافية', 'Transparenz schafft Vertrauen.', 'Transparenz schafft ein Vertrauen.', 'Vertrauen بلا أداة.', 'lexik-kollokation', 'Transparenz']
    ],
    tricks: [
      { trick: 'المقارنة النظامية تحتاج زوجًا متقابلًا: im Gegensatz zu · im Vergleich zu · dagegen', wie: 'Im Gegensatz zu Deutschland ist das hier gratis. · Hier zahlt man bar, dort dagegen mit Karte.', warum: 'المقال المقارن في B1 يُقاس على الربط الصريح بين النظامين، والعربية تكتفي بـ«أما».', anchor: 'im Gegensatz zu' },
      { trick: 'مفردات الدولة: die Verwaltung · die Bürokratie · der Beamte · die Steuer', wie: 'Die Bürokratie kostet Zeit, die Verwaltung arbeitet langsam.', warum: 'هذا الحقل المعجمي هو المطلوب في نصوص B1 عن المجتمع، وترجمته الحرفية تُفقد الدقة.', anchor: 'die Bürokratie' },
      { trick: 'vergleichen بلا حرف جر، والأمثال الثابتة للمقارنة حروفها ثابتة', wie: 'Vergleiche die beiden Systeme! · Im Gegensatz zu früher …', warum: 'العربية تقول «قارن بين»، والألمانية تصل الفعل بالمفعول مباشرة.', anchor: 'vergleichen' }
    ]
  }

};
