/* Deutschweg — B1 lexical layer, unit 1 (part b): b1-u1-l4 … b1-u1-l6.
   40 items per lesson, the count the B1 rows declare (amendment B1-L1).
   Not wired yet — see the header of vocab-b1-u1a.js for why and how. */

module.exports = {

  'b1-u1-l4': {
    items: [
      ['deshalb', '—', 'لذلك', 'Ich war krank, deshalb bin ich zu Hause geblieben.', 'Ich war krank, deshalb ich bin zu Hause geblieben.', 'الفعل ثانٍ بعد deshalb.', 'wortstellung', 'deshalb'],
      ['deswegen', '—', 'لهذا السبب', 'Der Zug fiel aus, deswegen kam ich später.', 'Der Zug fiel aus, deswegen ich kam später.', 'الفعل ثانٍ.', 'wortstellung', 'deswegen'],
      ['daher', '—', 'من ثم', 'Es regnete stark, daher blieben wir im Hotel.', 'Es regnete stark, daher wir blieben im Hotel.', 'الفعل ثانٍ.', 'wortstellung', 'daher'],
      ['folglich', '—', 'وبالتالي', 'Die Preise stiegen, folglich kauften wir weniger.', 'Die Preise stiegen, folglich wir kauften weniger.', 'الفعل ثانٍ.', 'wortstellung', 'folglich'],
      ['also', '—', 'إذن', 'Du hast keine Zeit, also komme ich allein.', 'Du hast keine Zeit, also ich komme allein.', 'الفعل ثانٍ.', 'wortstellung', 'also'],
      ['denn', '—', 'لأنّ', 'Ich bleibe hier, denn es regnet.', 'Ich bleibe hier, denn es regnet stark es.', 'لا ضمير زائد.', 'wortstellung', 'denn'],
      ['verursachen', 'verursacht · verursachte · hat verursacht', 'يسبّب', 'Der Sturm hat große Schäden verursacht.', 'Der Sturm hat große Schäden verursacht gemacht.', 'الفعل كامل بذاته.', 'lexik-kollokation', 'verursacht'],
      ['bewirken', 'bewirkt · bewirkte · hat bewirkt', 'يُحدث', 'Diese Maßnahme bewirkt viel.', 'Diese Maßnahme bewirkt viel gemacht.', 'الفعل كامل بذاته.', 'lexik-kollokation', 'bewirkt'],
      ['verhindern', 'verhindert · verhinderte · hat verhindert', 'يمنع من الحدوث', 'Der Zaun verhindert den Unfall.', 'Der Zaun verhindert von dem Unfall.', 'بلا حرف جر.', 'kasus', 'verhindert'],
      ['vermeiden', 'vermeidet · vermied · hat vermieden', 'يتجنّب', 'So vermeidest du Fehler.', 'So vermeidest du von Fehlern.', 'بلا حرف جر.', 'kasus', 'vermeidest'],
      ['reduzieren', 'reduziert · reduzierte · hat reduziert', 'يقلّل', 'Wir müssen die Kosten reduzieren.', 'Wir müssen die Kosten reduzieren von.', 'بلا حرف جر.', 'kasus', 'reduzieren'],
      ['verringern', 'verringert · verringerte · hat verringert', 'يخفّض', 'Die Firma verringert den Verbrauch.', 'Die Firma verringert von dem Verbrauch.', 'بلا حرف جر.', 'kasus', 'verringert'],
      ['erweitern', 'erweitert · erweiterte · hat erweitert', 'يوسّع', 'Sie erweitert ihre Kenntnisse.', 'Sie erweitert ihre Kenntnisse von.', 'بلا حرف جر.', 'kasus', 'erweitert'],
      ['verbessern', 'verbessert · verbesserte · hat verbessert', 'يحسّن', 'Ich will mein Deutsch verbessern.', 'Ich will mein Deutsch verbessern machen.', 'bessern فعل كامل.', 'lexik-kollokation', 'verbessern'],
      ['verändern', 'verändert · veränderte · hat verändert', 'يغيّر', 'Die Stadt hat sich stark verändert.', 'Die Stadt hat stark verändert.', 'الانعكاس: sich verändert.', 'konjugation', 'verändert'],
      ['ermöglichen', 'ermöglicht · ermöglichte · hat ermöglicht', 'يتيح', 'Die Stelle ermöglicht mir mehr Freiheit.', 'Die Stelle ermöglicht mir für mehr Freiheit.', 'داتيف + مفعول بلا حرف جر.', 'kasus', 'ermöglicht'],
      ['abhängen', 'hängt ab · hing ab · hat abgehangen', 'يتوقّف على', 'Der Preis hängt von der Qualität ab.', 'Der Preis hängt ab von der Qualität.', 'von … ab: البادئة آخرًا.', 'wortstellung', 'ab'],
      ['beitragen', 'trägt bei · trug bei · hat beigetragen', 'يسهم', 'Jeder kann zum Umweltschutz beitragen.', 'Jeder kann zu Umweltschutz beitragen.', 'zu + داتيف: zum.', 'präposition', 'beitragen'],
      ['die Folge', 'die Folgen', 'النتيجة', 'Die Folge war ein langer Streit.', 'Die Folge war ein lange Streit.', 'المفعول: einen langen Streit.', 'kasus', 'Folge'],
      ['die Wirkung', 'die Wirkungen', 'الأثر', 'Die Wirkung des Medikaments ist stark.', 'Die Wirkung von dem Medikament ist stark.', 'في الأسلوب الرفيع: Genitiv.', 'kasus', 'Wirkung'],
      ['die Ursache', 'die Ursachen', 'السبب', 'Die Ursache liegt in der Planung.', 'Die Ursache liegt in die Planung.', 'in + داتيف: der.', 'kasus', 'Ursache'],
      ['der Effekt', 'die Effekte', 'المفعول', 'Der Effekt war sofort sichtbar.', 'Der Effekt war sofort sichtbar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Effekt'],
      ['die Konsequenz', 'die Konsequenzen', 'التبعة', 'Er trägt die Konsequenzen.', 'Er trägt für die Konsequenzen.', 'بلا حرف جر.', 'kasus', 'Konsequenzen'],
      ['der Einfluss', 'die Einflüsse', 'التأثير', 'Das hat Einfluss auf die Entscheidung.', 'Das hat Einfluss für die Entscheidung.', 'auf لا für.', 'präposition', 'Einfluss'],
      ['die Maßnahme', 'die Maßnahmen', 'الإجراء', 'Die Maßnahme greift ab Januar.', 'Die Maßnahme greift von Januar.', 'من: ab لا von.', 'präposition', 'Maßnahme'],
      ['der Plan', 'die Pläne', 'الخطة', 'Der Plan ist noch nicht fertig.', 'Der Plan ist noch nicht fertig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Plan'],
      ['der Beschluss', 'die Beschlüsse', 'القرار', 'Der Beschluss wurde gestern gefasst.', 'Der Beschluss wurde gestern fassen.', 'المجهول: gefasst.', 'konjugation', 'gefasst'],
      ['die Entscheidung', 'die Entscheidungen', 'القرار', 'Die Entscheidung war richtig.', 'Die Entscheidung ist richtig gewesen.', 'war.', 'konjugation', 'Entscheidung'],
      ['die Entwicklung', 'die Entwicklungen', 'التطور', 'Die Entwicklung der Stadt ist schnell.', 'Die Entwicklung von der Stadt ist schnell.', 'Genitiv أو von + داتيف كلاهما جائز؛ الأجمل Genitiv.', 'kasus', 'Entwicklung'],
      ['die Veränderung', 'die Veränderungen', 'التغيير', 'Die Veränderung betrifft alle.', 'Die Veränderung betrifft alle es.', 'لا ضمير زائد.', 'wortstellung', 'Veränderung'],
      ['die Verbesserung', 'die Verbesserungen', 'التحسين', 'Die Verbesserung war nötig.', 'Die Verbesserung ist nötig gewesen.', 'war.', 'konjugation', 'Verbesserung'],
      ['die Erweiterung', 'die Erweiterungen', 'التوسيع', 'Die Erweiterung kostet Geld.', 'Die Erweiterung kostet Gelder.', 'Geld بلا جمع.', 'plural', 'Erweiterung'],
      ['der Zusammenhang', 'die Zusammenhänge', 'الترابط', 'Zwischen den Zahlen gibt es einen Zusammenhang.', 'Zwischen den Zahlen gibt es ein Zusammenhang.', 'مذكر: einen.', 'genus', 'Zusammenhang'],
      ['die Auswirkung', 'die Auswirkungen', 'الانعكاس', 'Die Auswirkungen sind schwer abzuschätzen.', 'Die Auswirkungen sind schwer abzuschätzen gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Auswirkungen'],
      ['der Vorteil', 'die Vorteile', 'الميزة', 'Der Vorteil liegt auf der Hand.', 'Der Vorteil liegt in der Hand.', 'العبارة: auf der Hand liegen.', 'lexik-kollokation', 'Vorteil'],
      ['der Nachteil', 'die Nachteile', 'العيب', 'Der Nachteil ist der Preis.', 'Der Nachteil ist der Preis gemacht.', 'الصيغة تكفي.', 'lexik-kollokation', 'Nachteil'],
      ['die Lösung', 'die Lösungen', 'الحل', 'Wir suchen eine schnelle Lösung.', 'Wir suchen für eine schnelle Lösung.', 'بلا حرف جر.', 'kasus', 'Lösung'],
      ['das Problem', 'die Probleme', 'المشكلة', 'Das Problem lässt sich lösen.', 'Das Problem lässt sich lösen es.', 'لا ضمير زائد.', 'wortstellung', 'Problem'],
      ['die Schwierigkeit', 'die Schwierigkeiten', 'الصعوبة', 'Die Schwierigkeit liegt im Detail.', 'Die Schwierigkeit liegt in das Detail.', 'in + داتيف: im.', 'kasus', 'Schwierigkeit'],
      ['der Zweck', 'die Zwecke', 'الغرض', 'Der Zweck heiligt nicht jedes Mittel.', 'Der Zweck heiligt nicht jede Mittel.', 'المفعول: jedes Mittel.', 'kasus', 'Zweck']
    ],
    tricks: [
      { trick: 'السبب يسبق: deshalb · deswegen · daher · folglich — والفعل ثانٍ بعدها', wie: 'Es regnete, deshalb blieben wir hier. · Der Zug fiel aus, deswegen kam ich später.', warum: 'العربية تصل النتيجة بلا إزاحة، والألمانية تُزيح الفاعل بعد الظرف.', anchor: 'deshalb' },
      { trick: 'abhängen von · beitragen zu · Einfluss auf — الفعل يجرّ حرفه معه', wie: 'Der Preis hängt von der Qualität ab. · Das hat Einfluss auf die Entscheidung.', warum: 'العربية تقول «يعتمد على» فيبدّل المتعلم الحرف أو يحذفه.', anchor: 'abhängen' },
      { trick: 'die Folge · die Wirkung · die Konsequenz — اسم المفعول يختصر الجملة', wie: 'Die Folge war ein Streit. · Die Wirkung ist stark.', warum: 'الكتابة الأكاديمية B1 تفضّل الاسم، والعربية تميل إلى «فأدّى ذلك إلى…».', anchor: 'die Folge' }
    ]
  },

  'b1-u1-l5': {
    items: [
      ['damit', '—', 'لكي', 'Ich lerne jeden Tag, damit ich die Prüfung bestehe.', 'Ich lerne jeden Tag, damit ich bestehe die Prüfung.', 'الفعل في نهاية جملة damit.', 'wortstellung', 'damit'],
      ['um', '—', 'لكي (مع zu)', 'Ich lerne Deutsch, um in Berlin zu studieren.', 'Ich lerne Deutsch, um in Berlin studieren.', 'um … zu: zu قبل المصدر.', 'wortstellung', 'um'],
      ['erreichen', 'erreicht · erreichte · hat erreicht', 'يبلغ/يحقق', 'Mit Geduld erreichst du dein Ziel.', 'Mit Geduld du erreichst dein Ziel.', 'الفعل ثانٍ بعد الظرف.', 'wortstellung', 'erreichst'],
      ['ermöglichen', 'ermöglicht · ermöglichte · hat ermöglicht', 'يتيح', 'Die Übung ermöglicht ein sicheres Sprechen.', 'Die Übung ermöglicht für ein sicheres Sprechen.', 'مفعولان بلا حرف جر.', 'kasus', 'ermöglicht'],
      ['erleichtern', 'erleichtert · erleichterte · hat erleichtert', 'يسهّل', 'Die App erleichtert das Lernen.', 'Die App erleichtert für das Lernen.', 'بلا حرف جر.', 'kasus', 'erleichtert'],
      ['unterstützen', 'unterstützt · unterstützte · hat unterstützt', 'يدعم', 'Die Firma unterstützt ihre Mitarbeiter.', 'Die Firma unterstützt für ihre Mitarbeiter.', 'بلا حرف جر.', 'kasus', 'unterstützt'],
      ['fördern', 'fördert · förderte · hat gefördert', 'يعزّز', 'Der Kurs fördert die Aussprache.', 'Der Kurs fördert für die Aussprache.', 'بلا حرف جر.', 'kasus', 'fördert'],
      ['verstärken', 'verstärkt · verstärkte · hat verstärkt', 'يعزّز', 'Wir verstärken den Kontakt.', 'Wir verstärken mit dem Kontakt.', 'بلا حرف جر.', 'kasus', 'verstärken'],
      ['sparen', 'spart · sparte · hat gespart', 'يوفّر', 'So sparst du Zeit und Geld.', 'So du sparst Zeit und Geld.', 'الفعل ثانٍ.', 'wortstellung', 'sparst'],
      ['verdienen', 'verdient · verdiente · hat verdient', 'يكسب', 'Sie verdient genug für die Familie.', 'Sie verdient genug für die Familie zu.', 'حرف الجر einmal.', 'wortstellung', 'verdient'],
      ['investieren', 'investiert · investierte · hat investiert', 'يستثمر', 'Die Firma investiert in neue Maschinen.', 'Die Firma investiert für neue Maschinen.', 'in لا für.', 'präposition', 'investiert'],
      ['organisieren', 'organisiert · organisierte · hat organisiert', 'ينظّم', 'Wir organisieren ein Fest für die Nachbarn.', 'Wir organisieren ein Fest zu die Nachbarn.', 'für لا zu (في المعنى «لأجل»).', 'präposition', 'organisieren'],
      ['vorbereiten', 'bereitet vor · bereitete vor · hat vorbereitet', 'يحضّر', 'Ich bereite mich auf die Prüfung vor.', 'Ich bereite mich für die Prüfung vor.', 'auf لا für.', 'präposition', 'vor'],
      ['sich interessieren', 'interessiert sich · interessierte sich · hat sich interessiert', 'يهتم', 'Sie interessiert sich für Musik.', 'Sie interessiert für Musik.', 'الضمير sich لازم.', 'konjugation', 'interessiert'],
      ['helfen', 'hilft · half · hat geholfen', 'يساعد', 'Das hilft mir sehr.', 'Das hilft mich sehr.', 'helfen + داتيف.', 'kasus', 'hilft'],
      ['dienen', 'dient · diente · hat gedient', 'يخدم/يؤدي غرضًا', 'Diese Übung dient der Wiederholung.', 'Diese Übung dient für die Wiederholung.', 'dienen + داتيف بلا حرف جر.', 'kasus', 'dient'],
      ['nutzen', 'nutzt · nutzte · hat genutzt', 'يستفيد من', 'Nutze die Zeit!', 'Nutze von der Zeit!', 'بلا حرف جر.', 'kasus', 'Nutze'],
      ['vermeiden', 'vermeidet · vermied · hat vermieden', 'يتجنّب', 'Um Fehler zu vermeiden, liest er langsam.', 'Um Fehler vermeiden, liest er langsam.', 'in um … zu لا بد من zu.', 'wortstellung', 'vermeiden'],
      ['das Ziel', 'die Ziele', 'الهدف', 'Mein Ziel ist es, fließend zu sprechen.', 'Mein Ziel ist fließend zu sprechen.', 'الفاصلة وes مع Ziel.', 'wortstellung', 'Ziel'],
      ['der Zweck', 'die Zwecke', 'الغرض', 'Der Zweck der Reise ist ein Termin.', 'Der Zweck von der Reise ist ein Termin.', 'Genitiv: der Reise.', 'kasus', 'Zweck'],
      ['die Absicht', 'die Absichten', 'القصد', 'Ich habe die Absicht, umzuziehen.', 'Ich habe die Absicht umzuziehen.', 'الفاصلة قبل zu.', 'orthographie', 'Absicht'],
      ['das Motiv', 'die Motive', 'الدافع', 'Das Motiv ist unklar.', 'Das Motiv ist unklar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Motiv'],
      ['der Grund', 'die Gründe', 'السبب', 'Es gibt keinen Grund zur Sorge.', 'Es gibt kein Grund zur Sorge.', 'مذكر نصب: keinen.', 'kasus', 'Grund'],
      ['die Begründung', 'die Begründungen', 'التعليل', 'Ohne Begründung akzeptiere ich das nicht.', 'Ohne eine Begründung akzeptiere ich das nicht.', 'بعد ohne بلا أداة.', 'kasus', 'Begründung'],
      ['die Folge', 'die Folgen', 'النتيجة', 'Das hat keine Folgen.', 'Das hat kein Folgen.', 'الجمع نصب: keine.', 'kasus', 'Folgen'],
      ['die Maßnahme', 'die Maßnahmen', 'الإجراء', 'Um Strom zu sparen, schalten wir alles aus.', 'Um Strom sparen, schalten wir alles aus.', 'zu قبل المصدر.', 'wortstellung', 'sparen'],
      ['die Möglichkeit', 'die Möglichkeiten', 'الإمكانية', 'Es gibt die Möglichkeit, online zu lernen.', 'Es gibt die Möglichkeit online lernen.', 'zu + مصدر.', 'wortstellung', 'lernen'],
      ['die Gelegenheit', 'die Gelegenheiten', 'الفرصة', 'Nutze die Gelegenheit, um zu üben!', 'Nutze die Gelegenheit um zu üben!', 'الفاصلة قبل um.', 'orthographie', 'Gelegenheit'],
      ['die Aufgabe', 'die Aufgaben', 'المهمة', 'Die Aufgabe ist es, den Text zu kürzen.', 'Die Aufgabe ist den Text zu kürzen.', 'es + فاصلة.', 'wortstellung', 'Aufgabe'],
      ['das Verbot', 'die Verbote', 'المنع', 'Es ist verboten, hier zu parken.', 'Es ist verboten hier parken.', 'zu + مصدر.', 'wortstellung', 'parken'],
      ['die Erlaubnis', 'die Erlaubnisse', 'الإذن', 'Ohne Erlaubnis darfst du nicht fahren.', 'Ohne die Erlaubnis darfst du nicht fahren.', 'بعد ohne بلا أداة.', 'kasus', 'Erlaubnis'],
      ['die Übung', 'die Übungen', 'التمرين', 'Die Übung dient dazu, sicher zu sprechen.', 'Die Übung dient dazu sicher sprechen.', 'zu + مصدر.', 'wortstellung', 'sprechen'],
      ['die Geduld', '—', 'الصبر', 'Um das zu schaffen, brauchst du Geduld.', 'Um das zu schaffen, du brauchst Geduld.', 'بعد الجملة الثانوية: الفعل ثانٍ.', 'wortstellung', 'Geduld'],
      ['die Zeit', 'die Zeiten', 'الوقت', 'Ich habe keine Zeit, um zu warten.', 'Ich habe keine Zeit zu warten.', 'الفاصلة قبل um … zu.', 'orthographie', 'Zeit'],
      ['das Geld', '—', 'المال', 'Er arbeitet, um Geld zu verdienen.', 'Er arbeitet um Geld zu verdienen.', 'الفاصلة قبل um.', 'orthographie', 'Geld'],
      ['der Kontakt', 'die Kontakte', 'التواصل', 'Um Kontakte zu knüpfen, geht sie zum Kurs.', 'Um Kontakte knüpfen, geht sie zum Kurs.', 'zu قبل المصدر.', 'wortstellung', 'knüpfen'],
      ['das Ergebnis', 'die Ergebnisse', 'النتيجة', 'Um bessere Ergebnisse zu bekommen, üben wir mehr.', 'Um bessere Ergebnisse bekommen, üben wir mehr.', 'zu + مصدر.', 'wortstellung', 'bekommen'],
      ['die Gesundheit', '—', 'الصحة', 'Um gesund zu bleiben, bewegt er sich täglich.', 'Um gesund bleiben, bewegt er sich täglich.', 'zu + مصدر.', 'wortstellung', 'bleiben'],
      ['die Umwelt', '—', 'البيئة', 'Wir trennen den Müll, um die Umwelt zu schützen.', 'Wir trennen den Müll, um die Umwelt schützen.', 'zu + مصدر.', 'wortstellung', 'schützen'],
      ['die Prüfung', 'die Prüfungen', 'الامتحان', 'Damit ich die Prüfung bestehe, lerne ich täglich.', 'Damit ich bestehe die Prüfung, lerne ich täglich.', 'الفعل في نهاية damit.', 'wortstellung', 'bestehe']
    ],
    tricks: [
      { trick: 'نفس الفاعل: um … zu · فاعل مختلف: damit', wie: 'Ich lerne, um zu bestehen. · Ich lerne, damit mein Bruder auch besteht.', warum: 'العربية تستعمل «كي» للحالتين، والألمانية تشترط وحدة الفاعل في um … zu.', anchor: 'damit' },
      { trick: 'zu يلتصق بالمصدر في النهاية ويفصل مع الأفعال المنفصلة', wie: 'Ich versuche zu kommen. · Ich habe vor, morgen anzukommen.', warum: 'an + zu يندمجان: anzukommen، والعربية لا تعرف هذا الاتصال.', anchor: 'um' },
      { trick: 'الفاصلة قبل um … zu وdamit إلزامية', wie: 'Ich übe, um sicher zu sprechen. · Ich übe, damit ich sicher spreche.', warum: 'الفاصلة في الألمانية علامة إعرابية، والعربية تصل بلا فاصلة.', anchor: 'die Gelegenheit' }
    ]
  },

  'b1-u1-l6': {
    items: [
      ['anfangen', 'fängt an · fing an · hat angefangen', 'يبدأ', 'Ich fange an, Deutsch zu lernen.', 'Ich fange an Deutsch zu lernen.', 'الفاصلة قبل zu.', 'orthographie', 'an'],
      ['aufhören', 'hört auf · hörte auf · hat aufgehört', 'يتوقّف', 'Er hört auf, zu rauchen.', 'Er hört auf zu rauchen.', 'الفاصلة قبل zu.', 'orthographie', 'auf'],
      ['versuchen', 'versucht · versuchte · hat versucht', 'يحاول', 'Ich versuche, früher zu kommen.', 'Ich versuche früher zu kommen.', 'الفاصلة قبل zu.', 'orthographie', 'versuche'],
      ['vergessen', 'vergisst · vergaß · hat vergessen', 'ينسى', 'Vergiss nicht, die Tür zu schließen!', 'Vergiss nicht die Tür zu schließen!', 'الفاصلة قبل zu.', 'orthographie', 'Vergiss'],
      ['vorhaben', 'hat vor · hatte vor · hat vorgehabt', 'ينوي', 'Ich habe vor, umzuziehen.', 'Ich habe vor umzuziehen.', 'الفاصلة قبل zu.', 'orthographie', 'vor'],
      ['planen', 'plant · plante · hat geplant', 'يخطّط', 'Wir planen, im Sommer zu reisen.', 'Wir planen im Sommer reisen.', 'zu + مصدر.', 'wortstellung', 'planen'],
      ['beschließen', 'beschließt · beschloss · hat beschlossen', 'يقرّر', 'Sie hat beschlossen, zu bleiben.', 'Sie hat beschlossen bleiben.', 'zu + مصدر.', 'wortstellung', 'beschlossen'],
      ['hoffen', 'hofft · hoffte · hat gehofft', 'يأمل', 'Ich hoffe, dich bald zu sehen.', 'Ich hoffe dich bald sehen.', 'zu + مصدر.', 'wortstellung', 'hoffe'],
      ['scheinen', 'scheint · schien · hat geschienen', 'يبدو', 'Er scheint müde zu sein.', 'Er scheint müde sein.', 'zu + مصدر.', 'wortstellung', 'scheint'],
      ['pflegen', 'pflegt · pflegte · hat gepflegt', 'يعهد إلى نفسه بـ', 'Sie pflegt früh aufzustehen.', 'Sie pflegt früh aufstehen.', 'zu + مصدر منطمر.', 'wortstellung', 'pflegt'],
      ['beabsichtigen', 'beabsichtigt · beabsichtigte · hat beabsichtigt', 'يعتزم', 'Wir beabsichtigen, zu investieren.', 'Wir beabsichtigen investieren.', 'zu + مصدر.', 'wortstellung', 'beabsichtigen'],
      ['erwarten', 'erwartet · erwartete · hat erwartet', 'يتوقّع', 'Man erwartet von mir, pünktlich zu sein.', 'Man erwartet von mir pünktlich sein.', 'zu + مصدر.', 'wortstellung', 'erwartet'],
      ['bitten', 'bittet · bat · hat gebeten', 'يطلب من', 'Ich bitte dich, mir zu helfen.', 'Ich bitte dich mir helfen.', 'zu + مصدر.', 'wortstellung', 'bitte'],
      ['empfehlen', 'empfiehlt · empfahl · hat empfohlen', 'ينصح', 'Ich empfehle dir, früh zu buchen.', 'Ich empfehle dich früh zu buchen.', 'empfehlen + داتيف: dir.', 'kasus', 'empfehle'],
      ['verbieten', 'verbietet · verbot · hat verboten', 'يمنع', 'Der Arzt verbietet ihm, zu rauchen.', 'Der Arzt verbietet ihn zu rauchen.', 'verbieten + داتيف: ihm.', 'kasus', 'verbietet'],
      ['erlauben', 'erlaubt · erlaubte · hat erlaubt', 'يسمح', 'Sie erlaubt ihrem Sohn, lange zu spielen.', 'Sie erlaubt ihren Sohn lange zu spielen.', 'داتيف: ihrem Sohn.', 'kasus', 'erlaubt'],
      ['die Absicht', 'die Absichten', 'القصد', 'Ich habe nicht die Absicht zu bleiben.', 'Ich habe nicht die Absicht bleiben.', 'zu + مصدر.', 'wortstellung', 'Absicht'],
      ['die Möglichkeit', 'die Möglichkeiten', 'الإمكانية', 'Es besteht die Möglichkeit zu wechseln.', 'Es besteht die Möglichkeit wechseln.', 'zu + مصدر.', 'wortstellung', 'wechseln'],
      ['die Gelegenheit', 'die Gelegenheiten', 'الفرصة', 'Ich hatte keine Gelegenheit zu fragen.', 'Ich hatte keine Gelegenheit fragen.', 'zu + مصدر.', 'wortstellung', 'fragen'],
      ['die Hoffnung', 'die Hoffnungen', 'الأمل', 'Die Hoffnung zu gewinnen ist klein.', 'Die Hoffnung gewinnen ist klein.', 'zu + مصدر.', 'wortstellung', 'gewinnen'],
      ['die Angst', 'die Ängste', 'الخوف', 'Ich habe Angst, zu versagen.', 'Ich habe Angst versagen.', 'zu + مصدر.', 'wortstellung', 'Angst'],
      ['die Lust', '—', 'الرغبة', 'Ich habe Lust, ins Kino zu gehen.', 'Ich habe Lust ins Kino gehen.', 'zu + مصدر.', 'wortstellung', 'Lust'],
      ['die Pflicht', 'die Pflichten', 'الواجب', 'Es ist meine Pflicht, das zu melden.', 'Es ist meine Pflicht das melden.', 'zu + مصدر.', 'wortstellung', 'Pflicht'],
      ['das Recht', 'die Rechte', 'الحق', 'Du hast das Recht, zu widersprechen.', 'Du hast das Recht widersprechen.', 'zu + مصدر.', 'wortstellung', 'Recht'],
      ['der Wunsch', 'die Wünsche', 'الرغبة', 'Der Wunsch zu reisen bleibt.', 'Der Wunsch reisen bleibt.', 'zu + مصدر.', 'wortstellung', 'Wunsch'],
      ['der Plan', 'die Pläne', 'الخطة', 'Der Plan zu bauen liegt vor.', 'Der Plan bauen liegt vor.', 'zu + مصدر.', 'wortstellung', 'Plan'],
      ['die Aufgabe', 'die Aufgaben', 'المهمة', 'Meine Aufgabe ist es, zu prüfen.', 'Meine Aufgabe ist prüfen.', 'es + zu.', 'wortstellung', 'Aufgabe'],
      ['die Schwierigkeit', 'die Schwierigkeiten', 'الصعوبة', 'Die Schwierigkeit zu antworten ist groß.', 'Die Schwierigkeit antworten ist groß.', 'zu + مصدر.', 'wortstellung', 'Schwierigkeit'],
      ['wichtig', '—', 'مهم', 'Es ist wichtig, ehrlich zu sein.', 'Es ist wichtig ehrlich sein.', 'zu + مصدر.', 'wortstellung', 'wichtig'],
      ['nötig', '—', 'ضروري', 'Es ist nötig, das zu wiederholen.', 'Es ist nötig das wiederholen.', 'zu + مصدر.', 'wortstellung', 'nötig'],
      ['möglich', '—', 'ممكن', 'Es ist möglich, später zu kommen.', 'Es ist möglich später kommen.', 'zu + مصدر.', 'wortstellung', 'möglich'],
      ['schwierig', '—', 'صعب', 'Es ist schwierig, das zu verstehen.', 'Es ist schwierig das verstehen.', 'zu + مصدر.', 'wortstellung', 'schwierig'],
      ['leicht', '—', 'سهل', 'Es ist leicht, das zu vergessen.', 'Es ist leicht das vergessen.', 'zu + مصدر.', 'wortstellung', 'leicht'],
      ['sinnvoll', '—', 'منطقي', 'Es ist sinnvoll, früh zu planen.', 'Es ist sinnvoll früh planen.', 'zu + مصدر.', 'wortstellung', 'sinnvoll'],
      ['verboten', '—', 'ممنوع', 'Es ist verboten, hier zu rauchen.', 'Es ist verboten hier rauchen.', 'zu + مصدر.', 'wortstellung', 'verboten'],
      ['erlaubt', '—', 'مسموح', 'Es ist erlaubt, hier zu parken.', 'Es ist erlaubt hier parken.', 'zu + مصدر.', 'wortstellung', 'erlaubt'],
      ['bereit', '—', 'مستعد', 'Ich bin bereit, das zu übernehmen.', 'Ich bin bereit das übernehmen.', 'zu + مصدر.', 'wortstellung', 'bereit'],
      ['froh', '—', 'سعيد', 'Ich bin froh, dich zu sehen.', 'Ich bin froh dich sehen.', 'zu + مصدر.', 'wortstellung', 'froh'],
      ['stolz', '—', 'فخور', 'Sie ist stolz, das geschafft zu haben.', 'Sie ist stolz das geschafft haben.', 'zu + مصدر تام.', 'wortstellung', 'stolz'],
      ['gewohnt', '—', 'معتاد', 'Ich bin gewohnt, früh aufzustehen.', 'Ich bin gewohnt früh aufstehen.', 'zu + مصدر.', 'wortstellung', 'gewohnt']
    ],
    tricks: [
      { trick: 'الأفعال التي تأخذ zu: versuchen · vergessen · hoffen · planen · anfangen · aufhören', wie: 'Ich versuche, früher zu kommen. · Ich hoffe, dich bald zu sehen.', warum: 'العربية تصل الفعلين بلا فاصل، والألمانية تحتاج zu قبل المصدر الثاني.', anchor: 'versuchen' },
      { trick: 'الصفة + zu: es ist wichtig, ehrlich zu sein', wie: 'Es ist wichtig, ehrlich zu sein. · Es ist verboten, hier zu rauchen.', warum: 'التركيب بلا فاعل ظاهر (es)، والعربية تقول «من المهم أن تكون صادقًا».', anchor: 'wichtig' },
      { trick: 'الفعل المنفصل ينفصل حول zu: an|zufangen · auf|zustehen', wie: 'Es ist schwer, früh anzufangen. · Ich bin gewohnt, früh aufzustehen.', warum: 'an + zu + fangen — الوصل الذي لا مقابل له في العربية، ويُنسى كثيرًا.', anchor: 'anfangen' }
    ]
  }

};
