/* Deutschweg — B1 lexical layer, unit 8 (part b): b1-u8-l3 · b1-u8-l4. */

module.exports = {

  'b1-u8-l3': {
    items: [
      ['abhängig', '—', 'معتمد على', 'Jeder ist irgendwann abhängig von Hilfe.', 'Jeder ist irgendwann abhängig auf Hilfe.', 'abhängig + von.', 'präposition', 'abhängig'],
      ['ängstlich', '—', 'خائف', 'Das Kind wirkt ängstlich.', 'Das Kind wirkt ängstlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'ängstlich'],
      ['blass', '—', 'شاحب', 'Nach der Nacht bist du ganz blass.', 'Nach der Nacht bist du ganz blass gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'blass'],
      ['blind', '—', 'أعمى', 'Wenn alles schiefgeht, ist man blind vor Wut.', 'Wenn alles schiefgeht, ist man blind auf Wut.', 'blind vor + داتيف.', 'präposition', 'blind'],
      ['entspannen', '—', 'يسترخي', 'Abends entspanne ich mich im Salon.', 'Abends entspanne ich im Salon.', 'entspannen يستعمل انعكاسيًا: mich.', 'lexik-kollokation', 'entspanne'],
      ['die Erholung', '—', 'الاستجمام', 'Drei Tage Wald sind reine Erholung.', 'Drei Tage Wald ist reine Erholung.', 'الفاعل جمع: sind.', 'konjugation', 'Erholung'],
      ['ernähren', '—', 'يُطعم/يتغذى', 'Sie kümmert sich darum, die Familie zu ernähren.', 'Sie kümmert sich darum, die Familie ernähren.', 'المصدر مع zu: zu ernähren.', 'wortstellung', 'ernähren'],
      ['erschöpft', '—', 'منهَك', 'Nach dem Umzug war ich erschöpft.', 'Nach dem Umzug war ich erschöpft gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'erschöpft'],
      ['die Infektion', 'die Infektionen', 'العدوى', 'Die Infektion ist schnell erkannt worden.', 'Die Infektion ist schnell erkannt geworden.', 'المجهول التام: worden.', 'konjugation', 'Infektion'],
      ['die Medizin', 'die Medizinen', 'الدواء/الطب', 'Die Medizin wirkt erst nach einer Stunde.', 'Die Medizin wirken erst nach einer Stunde.', 'الفعل مفرد: wirkt.', 'konjugation', 'Medizin'],
      ['der Notruf', 'die Notrufe', 'نداء الطوارئ', 'Der Notruf kommt sofort.', 'Der Notruf kommen sofort.', 'الفعل مفرد: kommt.', 'konjugation', 'Notruf'],
      ['operieren', '—', 'يُجري عملية', 'Der Arzt wird morgen operieren.', 'Der Arzt wird morgen operieren auf.', 'operieren بلا حرف جر.', 'präposition', 'operieren'],
      ['das Opfer', 'die Opfer', 'الضحية', 'Das Opfer liegt schon im Spital.', 'Das Opfer liegen schon im Spital.', 'الفعل مفرد: liegt.', 'konjugation', 'Opfer'],
      ['optimistisch', '—', 'متفائل', 'Sie bleibt trotzdem optimistisch.', 'Sie bleibt trotzdem optimistisch gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'optimistisch'],
      ['die Pension', 'die Pensionen', 'التقاعد/الفندق الصغير', 'Mit sechzig geht er in Pension.', 'Mit sechzig geht er in die Pension hinein.', 'in Pension تكفي.', 'präposition', 'Pension'],
      ['pensionieren', '—', 'يُحال على التقاعد', 'Die Firma wird ihn bald pensionieren.', 'Die Firma wird ihn bald pensionieren auf.', 'pensionieren بلا حرف جر.', 'präposition', 'pensionieren'],
      ['die Therapie', 'die Therapien', 'العلاج', 'Die Therapie dauert drei Monate.', 'Die Therapie dauern drei Monate.', 'الفعل مفرد: dauert.', 'konjugation', 'Therapie'],
      ['tödlich', '—', 'قاتل/مميت', 'Der Unfall war tödlich.', 'Der Unfall war tödlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'tödlich'],
      ['der Tropfen', 'die Tropfen', 'القطرة', 'Nehmen Sie dreimal täglich einen Tropfen.', 'Nehmen Sie dreimal täglich auf einen Tropfen.', 'nehmen بلا حرف جر.', 'präposition', 'Tropfen'],
      ['das Virus', 'die Viren', 'الفيروس', 'Das Virus bleibt nicht immer gefährlich.', 'Das Virus bleiben nicht immer gefährlich.', 'الفعل مفرد: bleibt.', 'konjugation', 'Virus'],
      ['süchtig', '—', 'مدمن', 'Nicht jeder wird süchtig danach.', 'Nicht jeder wird süchtig dafür.', 'süchtig nach + داتيف هنا: danach.', 'präposition', 'süchtig'],
      ['das Suchtmittel', 'die Suchtmittel', 'المادة المخدرة', 'Das Suchtmittel steht im Gesetz.', 'Das Suchtmittel stehen im Gesetz.', 'الفعل مفرد: steht.', 'konjugation', 'Suchtmittel'],
      ['verpflegen', '—', 'يُعيل/يموّن', 'Die Küche verpflegt die Gäste.', 'Die Küche verpflegen die Gäste.', 'الفعل مفرد: verpflegt.', 'konjugation', 'verpflegt'],
      ['die Gewalt', 'die Gewalten', 'العنف', 'Gegen Gewalt hilft nur eine Anzeige.', 'Gegen Gewalt hilft nur eine Anzeige auf.', 'لا حرف جر زائد.', 'präposition', 'Gewalt'],
      ['wütend', '—', 'غاضب', 'Ich war wütend auf mich selbst.', 'Ich war wütend für mich selbst.', 'wütend auf (شخص).', 'präposition', 'wütend'],
      ['fröhlich', '—', 'مسرور', 'Die Kinder sind fröhlich wie immer.', 'Die Kinder sind fröhlich gemacht wie immer.', 'الصفة تكفي.', 'lexik-kollokation', 'fröhlich'],
      ['frech', '—', 'وقح/جسور', 'Die Antwort war frech, aber richtig.', 'Die Antwort war frech gemacht, aber richtig.', 'الصفة تكفي.', 'lexik-kollokation', 'frech'],
      ['peinlich', '—', 'محرج', 'So ein Fehler ist mir peinlich.', 'So ein Fehler ist mir peinlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'peinlich'],
      ['lächeln', '—', 'يبتسم', 'Über die Verzeihung kann ich nur lächeln.', 'Über die Verzeihung kann ich nur lächeln an.', 'lächeln بلا حرف جر.', 'präposition', 'lächeln'],
      ['fürchten', '—', 'يخاف', 'Viele fürchten sich vor der Nachspeise beim Doktor.', 'Viele fürchten sich auf der Nachspeise beim Doktor.', 'fürchten + vor.', 'präposition', 'fürchten'],
      ['enttäuschen', '—', 'يخيّب الظن', 'Ich will den Trainer nicht enttäuschen.', 'Ich will den Trainer nicht enttäuschen auf.', 'enttäuschen بلا حرف جر.', 'präposition', 'enttäuschen'],
      ['die Verzeihung', '—', 'العفو', 'Verzeihung, ist hier noch frei?', 'Verzeihung, ist hier noch frei auf?', 'لا حرف جر زائد.', 'präposition', 'Verzeihung'],
      ['das Verständnis', '—', 'التفهم', 'Danke für dein Verständnis.', 'Danke für dein Verständnis auf.', 'لا حرف جر زائد.', 'präposition', 'Verständnis'],
      ['das Vergnügen', 'die Vergnügen', 'المتعة', 'Das Ballett war ein Vergnügen.', 'Das Ballett waren ein Vergnügen.', 'الفاعل مفرد: war.', 'konjugation', 'Vergnügen'],
      ['vergnügt', '—', 'مسرور/مبتهج', 'Die Gäste sind vergnügt.', 'Die Gäste sind vergnügt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'vergnügt'],
      ['das Unglück', 'die Unglücke', 'الحادث/الشقاء', 'Das Unglück war im Fernsehen.', 'Das Unglück waren im Fernsehen.', 'الفعل مفرد: war.', 'konjugation', 'Unglück'],
      ['umarmen', '—', 'يعانق', 'Beim Wiedersehen umarmen sie sich.', 'Beim Wiedersehen umarmen sie.', 'انعكاسي: sich umarmen.', 'lexik-kollokation', 'umarmen'],
      ['der Sinn', 'die Sinne', 'المعنى/الحسّ', 'Diese Regel hat keinen Sinn.', 'Diese Regel hat keinen Sinn auf.', 'لا حرف جر زائد.', 'präposition', 'Sinn'],
      ['die Unterhaltung', 'die Unterhaltungen', 'الحديث/التسلية', 'Die Unterhaltung war lustig.', 'Die Unterhaltung waren lustig.', 'الفعل مفرد: war.', 'konjugation', 'Unterhaltung'],
      ['der Ratschlag', 'die Ratschläge', 'النصيحة', 'Dein Ratschlag hat mir geholfen.', 'Dein Ratschlag haben mir geholfen.', 'الفعل مفرد: hat.', 'konjugation', 'Ratschlag']
    ],
    tricks: [
      { trick: 'المشاعر تُلازم حرف جر ثابتًا: wütend auf · süchtig nach · abhängig von · fürchten sich vor', wie: 'Ich war wütend auf mich selbst. · Jeder ist irgendwann abhängig von Hilfe.', warum: 'الحرف في العربية يُترجم «من/على»، والألمانية تثبّته فيُحفظ مع الصفة.', anchor: 'wütend auf' },
      { trick: 'انعكاسي بلا مفعول ظاهر: sich entspannen · sich umarmen', wie: 'Abends entspanne ich mich im Salon. · Beim Wiedersehen umarmen sie sich.', warum: 'حذف الضمير الانعكاسي خطأ شائع عند العرب لأن الفعل لازم في العربية.', anchor: 'entspanne ich mich' },
      { trick: 'المشاعر ضد الحدث: das Unglück · die Erholung مفرد بفعل مفرد', wie: 'Das Unglück war im Fernsehen. · Drei Tage Wald sind reine Erholung.', warum: 'المعنى جمعي لكن الاسم مفرد، والفعل يتبعه لا يتبع المعنى.', anchor: 'Das Unglück war' }
    ]
  },

  'b1-u8-l4': {
    items: [
      ['die Annonce', 'die Annoncen', 'الإعلان (سويسرا)', 'In der Annonce steht eine Rufnummer.', 'In der Annonce steht eine Rufnummer auf.', 'لا حرف جر زائد.', 'präposition', 'Annonce'],
      ['die Anwältin', 'die Anwältinnen', 'المحامية', 'Die Anwältin prüft den Vertrag.', 'Die Anwältin prüfen den Vertrag.', 'الفعل مفرد: prüft.', 'konjugation', 'Anwältin'],
      ['aufschreiben', '—', 'يدوّن', 'Ich schreibe die Nummer gleich auf.', 'Ich aufschreibe die Nummer gleich.', 'الفعل المنفصل: schreibe … auf.', 'wortstellung', 'schreibe'],
      ['beobachten', '—', 'يراقب', 'Der Chef beobachtet alles genau.', 'Der Chef beobachtet auf alles genau.', 'beobachten بلا حرف جر.', 'präposition', 'beobachtet'],
      ['berechnen', '—', 'يحسب/يحتسب', 'Sie berechnen dafür nichts.', 'Sie berechnen dafür nichts auf.', 'لا حرف جر زائد.', 'präposition', 'berechnen'],
      ['die Beschäftigung', 'die Beschäftigungen', 'العمل/الانشغال', 'Seine Beschäftigung macht ihm Freude.', 'Seine Beschäftigung machen ihm Freude.', 'الفعل مفرد: macht.', 'konjugation', 'Beschäftigung'],
      ['die Empfehlung', 'die Empfehlungen', 'التوصية', 'Die Empfehlung der Kollegin half.', 'Die Empfehlung von der Kollegin half.', 'الإضافة: der Kollegin.', 'kasus', 'Empfehlung'],
      ['der Faktor', 'die Faktoren', 'العامل', 'Zeit ist der wichtigste Faktor.', 'Zeit sind der wichtigste Faktor.', 'الفاعل مفرد: ist.', 'konjugation', 'Faktor'],
      ['die Fachfrau', 'die Fachfrauen', 'الخبيرة', 'Nur eine Fachfrau darf das prüfen.', 'Nur eine Fachfrau darf das prüfen auf.', 'لا حرف جر زائد.', 'präposition', 'Fachfrau'],
      ['Fachleute', '—', 'أهل الاختصاص (جمع)', 'Die Fachleute streiten noch.', 'Die Fachleute streitet noch.', 'الجمع: streiten.', 'konjugation', 'Fachleute'],
      ['finanziell', '—', 'مالي', 'Die Lage ist finanziell schwierig.', 'Die Lage ist finanziell schwierig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'finanziell'],
      ['finanzieren', '—', 'يموّل', 'Die Bank finanziert den Umbau.', 'Die Bank finanzieren den Umbau.', 'الفعل مفرد: finanziert.', 'konjugation', 'finanziert'],
      ['garantieren', '—', 'يضمن', 'Wir garantieren die Lieferung bis Freitag.', 'Wir garantieren für die Lieferung bis Freitag.', 'garantieren بلا حرف جر.', 'präposition', 'garantieren'],
      ['die Industrie', 'die Industrien', 'الصناعة', 'Die Industrie sucht Fachkräfte.', 'Die Industrie suchen Fachkräfte.', 'الفعل مفرد: sucht.', 'konjugation', 'Industrie'],
      ['der Ingenieur', 'die Ingenieure', 'المهندس', 'Der Ingenieur zeichnet den Plan.', 'Der Ingenieur zeichnen den Plan.', 'الفعل مفرد: zeichnet.', 'konjugation', 'Ingenieur'],
      ['das Institut', 'die Institute', 'المعهد', 'Das Institut hat einen neuen Kurs.', 'Das Institut haben einen neuen Kurs.', 'الفعل مفرد: hat.', 'konjugation', 'Institut'],
      ['die Integration', 'die Integrationen', 'الاندماج', 'Integration braucht Zeit und Sprache.', 'Integration brauchen Zeit und Sprache.', 'الفاعل مفرد: braucht.', 'konjugation', 'Integration'],
      ['die Kommunikation', '—', 'التواصل', 'Ohne Kommunikation geht kein Projekt.', 'Ohne Kommunikation geht kein Projekt auf.', 'لا حرف جر زائد.', 'präposition', 'Kommunikation'],
      ['konzentrieren', '—', 'يركّز', 'Ich muss mich auf die Arbeit konzentrieren.', 'Ich muss mich auf die Arbeit konzentrieren an.', 'konzentrieren + auf.', 'präposition', 'konzentrieren'],
      ['kopieren', '—', 'ينسخ', 'Bitte kopieren Sie alle Seiten.', 'Bitte kopieren Sie auf alle Seiten.', 'kopieren بلا حرف جر.', 'präposition', 'kopieren'],
      ['der Kopierer', 'die Kopierer', 'آلة النسخ', 'Der Kopierer steht neben der Tür.', 'Der Kopierer stehen neben der Tür.', 'الفعل مفرد: steht.', 'konjugation', 'Kopierer'],
      ['der Kuli', 'die Kulis', 'القلم الجاف', 'Mit welchem Kuli schreibst du?', 'Mit welchem Kuli schreibst du auf?', 'لا حرف جر زائد.', 'präposition', 'Kuli'],
      ['das Laufwerk', 'die Laufwerke', 'مشغّل الأقراص', 'Das Laufwerk im Rechner ist voll.', 'Das Laufwerk im Rechner sind voll.', 'الفعل مفرد: ist.', 'konjugation', 'Laufwerk'],
      ['löschen', '—', 'يمحو', 'Ich lösche die alten Dateien.', 'Ich lösche auf die alten Dateien.', 'löschen بلا حرف جر.', 'präposition', 'lösche'],
      ['das Magazin', 'die Magazine', 'المجلة', 'Das Magazin erscheint monatlich.', 'Das Magazin erscheinen monatlich.', 'الفعل مفرد: erscheint.', 'konjugation', 'Magazin'],
      ['das Medium', 'die Medien', 'الوسيط الإعلامي', 'Das Medium erreicht viele Leute.', 'Das Medium erreichen viele Leute.', 'الفعل مفرد: erreicht.', 'konjugation', 'Medium'],
      ['die Methode', 'die Methoden', 'الطريقة', 'Die Methode ist neu, aber bewährt.', 'Die Methode sind neu, aber bewährt.', 'الفعل مفرد: ist.', 'konjugation', 'Methode'],
      ['das Modell', 'die Modelle', 'الطراز/الموديل', 'Das Modell von letztem Jahr kostet weniger.', 'Das Modell von letztem Jahr kosten weniger.', 'الفعل مفرد: kostet.', 'konjugation', 'Modell'],
      ['die Organisation', 'die Organisationen', 'التنظيم', 'Die Organisation der Sitzung dauerte lange.', 'Die Organisation von der Sitzung dauerte lange.', 'الإضافة: der Sitzung.', 'kasus', 'Organisation'],
      ['der Prozess', 'die Prozesse', 'المحاكمة/العملية', 'Der Prozess beginnt im Herbst.', 'Der Prozess beginnen im Herbst.', 'الفعل مفرد: beginnt.', 'konjugation', 'Prozess'],
      ['realisieren', '—', 'ينفّذ/يدرك', 'Wir realisieren das Projekt im Team.', 'Wir realisieren auf das Projekt im Team.', 'realisieren بلا حرف جر.', 'präposition', 'realisieren'],
      ['die Reporterin', 'die Reporterinnen', 'المراسلة', 'Die Reporterin fragt den Meister.', 'Die Reporterin fragen den Meister.', 'الفعل مفرد: fragt.', 'konjugation', 'Reporterin'],
      ['die Richterin', 'die Richterinnen', 'القاضية', 'Die Richterin liest das Urteil vor.', 'Die Richterin liest das Urteil vor auf.', 'لا حرف جر زائد.', 'präposition', 'Richterin'],
      ['die Rufnummer', 'die Rufnummern', 'رقم الهاتف', 'Die Rufnummer steht oben im Inserat.', 'Die Rufnummer stehen oben im Inserat.', 'الفعل مفرد: steht.', 'konjugation', 'Rufnummer'],
      ['der Schriftsteller', 'die Schriftsteller', 'الكاتب', 'Der Schriftsteller lebt von seinen Büchern.', 'Der Schriftsteller leben von seinen Büchern.', 'الفعل مفرد: lebt.', 'konjugation', 'Schriftsteller'],
      ['stilistisch', '—', 'أسلوبي', 'Der Text ist stilistisch gut.', 'Der Text ist stilistisch gut gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'stilistisch'],
      ['das Symbol', 'die Symbole', 'الرمز', 'Das Symbol auf dem Deckel erklärt viel.', 'Das Symbol auf dem Deckel erklären viel.', 'الفعل مفرد: erklärt.', 'konjugation', 'Symbol'],
      ['die Übersetzerin', 'die Übersetzerinnen', 'المترجمة', 'Die Übersetzerin arbeitet ohne Pause.', 'Die Übersetzerin arbeiten ohne Pause.', 'الفعل مفرد: arbeitet.', 'konjugation', 'Übersetzerin'],
      ['der Verlag', 'die Verlage', 'دار النشر', 'Der Verlag druckt das Buch neu.', 'Der Verlag drucken das Buch neu.', 'الفعل مفرد: druckt.', 'konjugation', 'Verlag'],
      ['die Visitenkarte', 'die Visitenkarten', 'بطاقة الزيارة', 'Ich gebe Ihnen meine Visitenkarte.', 'Ich gebe Ihnen meine Visitenkarte auf.', 'لا حرف جر زائد.', 'präposition', 'Visitenkarte']
    ],
    tricks: [
      { trick: 'المهن والأدوار في العمل: der Ingenieur · die Anwältin · die Übersetzerin · der Schriftsteller', wie: 'Die Anwältin prüft den Vertrag. · Der Ingenieur zeichnet den Plan.', warum: 'كل هذه الأسماء مفردة بفعل مفرد وإن دلّت على صاحب مهنة عامة.', anchor: 'Die Anwältin prüft' },
      { trick: 'أفعال المكتب بلا حرف جر: kopieren · löschen · garantieren · realisieren', wie: 'Bitte kopieren Sie alle Seiten. · Wir realisieren das Projekt im Team.', warum: 'العربية تقول «ينسخ من» فتُضاف «من»، والألمانية تطلب المفعول مباشرة.', anchor: 'kopieren Sie alle Seiten' },
      { trick: 'التركّز يكون على شيء: sich konzentrieren auf', wie: 'Ich muss mich auf die Arbeit konzentrieren.', warum: 'مع الفعل الانعكاسي يأتي الحرف قبل الضمير العائد في موضعه.', anchor: 'auf die Arbeit konzentrieren' }
    ]
  }

};
