/* Deutschweg — B1 lexical layer, unit 4 (part b): b1-u4-l4 … b1-u4-l6.
   40 items per lesson, the count the B1 rows declare (amendment B1-L1).
   Not wired yet — see the header of vocab-b1-u1a.js for why and how. */

module.exports = {

  'b1-u4-l4': {
    items: [
      ['zusammenfassen', 'fasst zusammen · fasste zusammen · hat zusammengefasst', 'يلخّص', 'Fassen Sie den Text kurz zusammen.', 'Fassen Sie den Text kurz.', 'المنفصل: zusammen.', 'wortstellung', 'zusammen'],
      ['die Zusammenfassung', 'die Zusammenfassungen', 'التلخيص', 'Die Zusammenfassung darf fünf Zeilen haben.', 'Die Zusammenfassung darf fünf Zeile haben.', 'الجمع: Zeilen.', 'plural', 'Zusammenfassung'],
      ['der Inhalt', 'die Inhalte', 'المحتوى', 'Der Inhalt ist leicht zu verstehen.', 'Der Inhalt ist leicht verstehen.', 'zu + مصدر.', 'wortstellung', 'Inhalt'],
      ['das Wesentliche', '—', 'الجوهري', 'Das Wesentliche steht im ersten Absatz.', 'Das Wesentliche steht in ersten Absatz.', 'في: im.', 'präposition', 'Wesentliche'],
      ['der Absatz', 'die Absätze', 'الفقرة', 'Jeder Absatz hat eine Hauptidee.', 'Jeder Absatz hat ein Hauptidee.', 'مؤنث: eine.', 'genus', 'Absatz'],
      ['der Satz', 'die Sätze', 'الجملة', 'Der letzte Satz fasst alles zusammen.', 'Der letzte Satz fasst alles zusammen es.', 'لا ضمير زائد.', 'wortstellung', 'Satz'],
      ['die Hauptidee', 'die Hauptideen', 'الفكرة الرئيسية', 'Die Hauptidee steht am Anfang.', 'Die Hauptidee steht in Anfang.', 'am Anfang.', 'präposition', 'Hauptidee'],
      ['das Thema', 'die Themen', 'الموضوع', 'Das Thema ist aktuell.', 'Das Thema ist aktuell gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Thema'],
      ['der Kern', 'die Kerne', 'اللبّ', 'Der Kern der Aussage ist klar.', 'Der Kern von der Aussage ist klar.', 'Genitiv أفضل.', 'kasus', 'Kern'],
      ['die Kernaussage', 'die Kernaussagen', 'المضمون الجوهري', 'Die Kernaussage ist einfach.', 'Die Kernaussage ist einfach gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Kernaussage'],
      ['hervorheben', 'hebt hervor · hob hervor · hat hervorgehoben', 'يبرز', 'Der Autor hebt zwei Punkte hervor.', 'Der Autor hebt zwei Punkte.', 'المنفصل: hervor.', 'wortstellung', 'hervor'],
      ['betonen', 'betont · betonte · hat betont', 'يشدّد', 'Sie betont die Bedeutung der Übung.', 'Sie betont auf die Bedeutung der Übung.', 'بلا حرف جر.', 'kasus', 'betont'],
      ['erwähnen', 'erwähnt · erwähnte · hat erwähnt', 'يذكر عابرًا', 'Er erwähnt das Problem nur kurz.', 'Er erwähnt über das Problem nur kurz.', 'بلا حرف جر.', 'kasus', 'erwähnt'],
      ['nennen', 'nennt · nannte · hat genannt', 'يسمّي', 'Nennen Sie drei Beispiele.', 'Nennen Sie drei Beispiel.', 'الجمع: Beispiele.', 'plural', 'Nennen'],
      ['beschreiben', 'beschreibt · beschrieb · hat beschrieben', 'يصف', 'Beschreiben Sie den Weg kurz.', 'Beschreiben Sie den Weg kurz es.', 'لا ضمير زائد.', 'wortstellung', 'beschreiben'],
      ['schildern', 'schildert · schilderte · hat geschildert', 'يحكي بالتفصيل', 'Der Zeuge schildert den Vorfall.', 'Der Zeuge schildert über den Vorfall.', 'بلا حرف جر.', 'kasus', 'schildert'],
      ['darstellen', 'stellt dar · stellte dar · hat dargestellt', 'يعرض', 'Die Grafik stellt die Zahlen dar.', 'Die Grafik stellt die Zahlen.', 'المنفصل: dar.', 'wortstellung', 'dar'],
      ['die Darstellung', 'die Darstellungen', 'العرض', 'Die Darstellung ist sachlich.', 'Die Darstellung ist sachlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Darstellung'],
      ['der Überblick', 'die Überblicke', 'النظرة الشاملة', 'Der Text gibt einen guten Überblick.', 'Der Text gibt ein guter Überblick.', 'مذكر نصب: einen guten.', 'kasus', 'Überblick'],
      ['die Gliederung', 'die Gliederungen', 'التقسيم', 'Die Gliederung fehlt noch.', 'Die Gliederung fehlt noch es.', 'لا ضمير زائد.', 'wortstellung', 'Gliederung'],
      ['die Einleitung', 'die Einleitungen', 'المقدمة', 'Die Einleitung ist zu lang.', 'Die Einleitung ist zu lang gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Einleitung'],
      ['der Schluss', 'die Schlüsse', 'الخاتمة', 'Der Schluss fasst alles zusammen.', 'Der Schluss fasst alles zusammen es.', 'لا ضمير زائد.', 'wortstellung', 'Schluss'],
      ['der Hauptteil', 'die Hauptteile', 'المتن', 'Der Hauptteil ist der längste.', 'Der Hauptteil ist der längste gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Hauptteil'],
      ['die Quelle', 'die Quellen', 'المصدر', 'Die Quelle muss man angeben.', 'Die Quelle muss man angeben es.', 'لا ضمير زائد.', 'wortstellung', 'Quelle'],
      ['angeben', 'gibt an · gab an · hat angegeben', 'يذكر', 'Geben Sie die Quelle an.', 'Geben Sie die Quelle.', 'المنفصل: an.', 'wortstellung', 'an'],
      ['zitieren', 'zitiert · zitierte · hat zitiert', 'يقتبس', 'Er zitiert den Autor wörtlich.', 'Er zitiert von dem Autor wörtlich.', 'بلا حرف جر.', 'kasus', 'zitiert'],
      ['das Zitat', 'die Zitate', 'الاقتباس', 'Das Zitat ist zu lang.', 'Das Zitat ist zu lang gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Zitat'],
      ['die Stellungnahme', 'die Stellungnahmen', 'البيان', 'Die Stellungnahme kommt morgen.', 'Die Stellungnahme kommt in morgen.', 'بلا حرف جر.', 'präposition', 'Stellungnahme'],
      ['Stellung nehmen', 'nimmt Stellung · nahm Stellung · hat Stellung genommen', 'يبدي موقفًا', 'Die Firma nimmt zu dem Vorwurf Stellung.', 'Die Firma nimmt den Vorwurf Stellung.', 'zu + داتيف.', 'präposition', 'Stellung'],
      ['die Aussage', 'die Aussagen', 'التصريح', 'Seine Aussage widerspricht den Fakten.', 'Seine Aussage widerspricht die Fakten.', 'widersprechen + داتيف.', 'kasus', 'Aussage'],
      ['die Behauptung', 'die Behauptungen', 'الادّعاء', 'Die Behauptung ist unbewiesen.', 'Die Behauptung ist unbewiesen gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Behauptung'],
      ['das Ergebnis', 'die Ergebnisse', 'النتيجة', 'Das Ergebnis steht am Ende.', 'Das Ergebnis steht in Ende.', 'am Ende.', 'präposition', 'Ergebnis'],
      ['die Schlussfolgerung', 'die Schlussfolgerungen', 'الاستنتاج', 'Diese Schlussfolgerung ist gewagt.', 'Diese Schlussfolgerung ist gewagt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Schlussfolgerung'],
      ['schließen', 'schließt · schloss · hat geschlossen', 'يستنتج', 'Daraus schließe ich, dass es klappt.', 'Daraus schließe ich, dass es klappt es.', 'لا ضمير زائد.', 'wortstellung', 'schließe'],
      ['der Text', 'die Texte', 'النص', 'Der Text hat vier Absätze.', 'Der Text hat vier Absatz.', 'الجمع: Absätze.', 'plural', 'Text'],
      ['die Überschrift', 'die Überschriften', 'العنوان', 'Die Überschrift verrät zu viel.', 'Die Überschrift verrät zu viel es.', 'لا ضمير زائد.', 'wortstellung', 'Überschrift'],
      ['die Sprache', 'die Sprachen', 'اللغة', 'Die Sprache ist einfach und klar.', 'Die Sprache ist einfach und klar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Sprache'],
      ['der Stil', 'die Stile', 'الأسلوب', 'Der Stil ist sachlich.', 'Der Stil ist sachlich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Stil'],
      ['verständlich', '—', 'مفهوم', 'Der Text ist verständlich geschrieben.', 'Der Text ist verständlich schreiben.', 'الصفة + Partizip II.', 'konjugation', 'verständlich'],
      ['kompliziert', '—', 'معقّد', 'Die Erklärung ist zu kompliziert.', 'Die Erklärung ist zu kompliziert gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'kompliziert']
    ],
    tricks: [
      { trick: 'بناء التلخيص: Einleitung · Hauptteil · Schluss — بلا رأي شخصي', wie: 'Die Einleitung nennt das Thema, der Hauptteil bringt die Argumente, der Schluss fasst zusammen.', warum: 'الملخّص الألماني محايد تمامًا، والعربية تحبّ إضافة «وأنا أرى…» فتخرج عن المطلوب.', anchor: 'die Zusammenfassung' },
      { trick: 'Nennen Sie · Beschreiben Sie · Fassen Sie zusammen — صيغ التكليف الرسمي', wie: 'Fassen Sie den Text kurz zusammen. · Nennen Sie drei Beispiele.', warum: 'التكليف في الامتحان صيغة أمر مهذّبة بفعل منفصل في النهاية، وهي التي تُحدّد المطلوب.', anchor: 'zusammenfassen' },
      { trick: 'مصادر النص: angeben · zitieren · die Quelle — إلزامية في B1', wie: 'Geben Sie die Quelle an. · Er zitiert den Autor wörtlich.', warum: 'الاقتباس بلا مصدر يُخصم عليه، والعربية تقول «قال أحدهم» بلا توثيق.', anchor: 'zitieren' }
    ]
  },

  'b1-u4-l5': {
    items: [
      ['das Gespräch', 'die Gespräche', 'المحادثة', 'Das Gespräch war sehr lang.', 'Das Gespräch war sehr lang gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Gespräch'],
      ['das Interview', 'die Interviews', 'المقابلة', 'Das Interview läuft live.', 'Das Interview läuft live es.', 'لا ضمير زائد.', 'wortstellung', 'Interview'],
      ['die Diskussion', 'die Diskussionen', 'المناقشة', 'Die Diskussion war hitzig.', 'Die Diskussion war hitzig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Diskussion'],
      ['die Debatte', 'die Debatten', 'الجدل', 'Die Debatte dauerte bis Mitternacht.', 'Die Debatte dauerte bis zu Mitternacht.', 'bis بلا zu مع الوقت.', 'präposition', 'Debatte'],
      ['die Meinung', 'die Meinungen', 'الرأي', 'Ich habe eine andere Meinung.', 'Ich habe ein andere Meinung.', 'مؤنث: eine.', 'genus', 'Meinung'],
      ['das Wort', 'die Wörter', 'الكلمة', 'Ich habe das Wort vergessen.', 'Ich habe das Wort vergessen gemacht.', 'الماضي المركّب مباشر.', 'konjugation', 'Wort'],
      ['die Antwort', 'die Antworten', 'الجواب', 'Die Antwort war überzeugend.', 'Die Antwort war überzeugend gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Antwort'],
      ['die Frage', 'die Fragen', 'السؤال', 'Die Frage war schwer.', 'Die Frage war schwer gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Frage'],
      ['die Nachfrage', 'die Nachfragen', 'السؤال التتبعي', 'Die Nachfrage kam sofort.', 'Die Nachfrage kam sofort es.', 'لا ضمير زائد.', 'wortstellung', 'Nachfrage'],
      ['das Argument', 'die Argumente', 'الحجة', 'Sein Argument ist stark.', 'Sein Argument ist stark gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Argument'],
      ['unterbrechen', 'unterbricht · unterbrach · hat unterbrochen', 'يقاطع', 'Bitte unterbrich mich nicht.', 'Bitte unterbrich mich nicht du.', 'النفي يكفي بلا ضمير.', 'wortstellung', 'unterbrich'],
      ['das Wort ergreifen', 'ergreift · ergriff · hat ergriffen', 'يأخذ الكلمة', 'Darf ich das Wort ergreifen?', 'Darf ich das Wort ergreifen es?', 'لا ضمير زائد.', 'wortstellung', 'ergreifen'],
      ['schweigen', 'schweigt · schwieg · hat geschwiegen', 'يصمت', 'Er schwieg lange.', 'Er hat lange geschweigt.', 'السرد: schwieg.', 'konjugation', 'schwieg'],
      ['die Stille', '—', 'الصمت', 'Eine kurze Stille folgte.', 'Eine kurze Stille folgte es.', 'لا ضمير زائد.', 'wortstellung', 'Stille'],
      ['zuhören', 'hört zu · hörte zu · hat zugehört', 'ينصت', 'Hör mir bitte zu!', 'Hör mich bitte zu!', 'zuhören + داتيف: mir.', 'kasus', 'zu'],
      ['nachfragen', 'fragt nach · fragte nach · hat nachgefragt', 'يستفسر', 'Ich frage lieber nach.', 'Ich frage lieber nach es.', 'لا ضمير زائد.', 'wortstellung', 'nach'],
      ['zustimmen', 'stimmt zu · stimmte zu · hat zugestimmt', 'يوافق', 'Er stimmt meinem Plan zu.', 'Er stimmt meinen Plan zu.', 'داتيف: meinem Plan.', 'kasus', 'stimmt'],
      ['widersprechen', 'widerspricht · widersprach · hat widersprochen', 'يعترض', 'Sie widerspricht dem Chef.', 'Sie widerspricht den Chef.', 'داتيف: dem Chef.', 'kasus', 'widerspricht'],
      ['sich einigen', 'einigt sich · einigte sich · hat sich geeinigt', 'يتفق', 'Wir haben uns schnell geeinigt.', 'Wir haben uns schnell geeinigt auf.', 'الضمير sich جزء من الفعل.', 'konjugation', 'geeinigt'],
      ['der Kompromiss', 'die Kompromisse', 'الحل الوسط', 'Wir fanden einen Kompromiss.', 'Wir fanden ein Kompromiss.', 'مذكر نصب: einen.', 'genus', 'Kompromiss'],
      ['die Lösung', 'die Lösungen', 'الحل', 'Die Lösung gefällt allen.', 'Die Lösung gefällt alle.', 'gefallen + داتيف: allen.', 'kasus', 'Lösung'],
      ['der Vorschlag', 'die Vorschläge', 'الاقتراح', 'Dein Vorschlag ist gut.', 'Dein Vorschlag ist gut gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Vorschlag'],
      ['vorschlagen', 'schlägt vor · schlug vor · hat vorgeschlagen', 'يقترح', 'Ich schlage vor, dass wir warten.', 'Ich schlage vor, dass wir warten es.', 'لا ضمير زائد.', 'wortstellung', 'vor'],
      ['die Anregung', 'die Anregungen', 'الإشارة البنّاءة', 'Danke für die Anregung.', 'Danke für die Anregung es.', 'لا ضمير زائد.', 'wortstellung', 'Anregung'],
      ['der Einwand', 'die Einwände', 'الاعتراض', 'Sein Einwand ist berechtigt.', 'Sein Einwand ist berechtigt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Einwand'],
      ['einwenden', 'wendet ein · wandte ein · hat eingewandt', 'يعترض قائلًا', 'Er wendet ein, dass es zu spät ist.', 'Er wendet ein, dass es ist zu spät.', 'الفعل في النهاية.', 'wortstellung', 'ein'],
      ['die Rede', 'die Reden', 'الخطاب', 'Seine Rede war kurz.', 'Seine Rede war kurz gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Rede'],
      ['der Redner', 'die Redner', 'الخطيب', 'Der Redner spricht frei.', 'Der Redner spricht frei es.', 'لا ضمير زائد.', 'wortstellung', 'Redner'],
      ['das Publikum', '—', 'الجمهور', 'Das Publikum klatschte lange.', 'Das Publikum hat lange geklatscht gehabt.', 'السرد: klatschte.', 'konjugation', 'Publikum'],
      ['der Zuhörer', 'die Zuhörer', 'المستمع', 'Die Zuhörer waren aufmerksam.', 'Die Zuhörer waren aufmerksam gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Zuhörer'],
      ['die Rückmeldung', 'die Rückmeldungen', 'التغذية الراجعة', 'Danke für die Rückmeldung.', 'Danke für die Rückmeldung es.', 'لا ضمير زائد.', 'wortstellung', 'Rückmeldung'],
      ['die Kritik', '—', 'النقد', 'Kritik muss man aushalten.', 'Kritik muss man aushalten es.', 'لا ضمير زائد.', 'wortstellung', 'Kritik'],
      ['sachlich', '—', 'موضوعي', 'Bleiben wir sachlich!', 'Bleiben wir sachlich du!', 'التعليمة بلا ضمير.', 'wortstellung', 'sachlich'],
      ['höflich', '—', 'مؤدّب', 'Bitte bleiben Sie höflich.', 'Bitte bleiben Sie höflich es.', 'لا ضمير زائد.', 'wortstellung', 'höflich'],
      ['deutlich', '—', 'واضح', 'Sprich bitte deutlich!', 'Sprich bitte deutlich du!', 'التعليمة بلا ضمير.', 'wortstellung', 'deutlich'],
      ['deuten', 'deutet · deutete · hat gedeutet', 'يؤوّل', 'Er deutet die Zahlen anders.', 'Er deutet die Zahlen anders es.', 'لا ضمير زائد.', 'wortstellung', 'deutet'],
      ['die Absicht', 'die Absichten', 'القصد', 'Seine Absicht war klar.', 'Seine Absicht war klar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Absicht'],
      ['das Missverständnis', 'die Missverständnisse', 'سوء الفهم', 'Da liegt ein Missverständnis vor.', 'Da liegt ein Missverständnis vor es.', 'لا ضمير زائد.', 'wortstellung', 'Missverständnis'],
      ['klären', 'klärt · klärte · hat geklärt', 'يجلّي', 'Wir müssen das klären.', 'Wir müssen das klären es.', 'لا ضمير زائد.', 'wortstellung', 'klären'],
      ['die Rücksicht', '—', 'المراعاة', 'Wir nehmen Rücksicht aufeinander.', 'Wir nehmen Rücksicht für einander.', 'auf لا für (لكن الصيغة علىeinander).', 'präposition', 'Rücksicht']
    ],
    tricks: [
      { trick: 'إدارة الحوار: das Wort ergreifen · unterbrechen · nachfragen · zusammenfassen', wie: 'Darf ich das Wort ergreifen? · Ich frage lieber nach.', warum: 'العربية تقول «اسمح لي أن أتكلم»، والألمانية عبارة ثابتة: das Wort ergreifen.', anchor: 'das Wort ergreifen' },
      { trick: 'الخلاف المهذب: zustimmen + داتيف · widersprechen + داتيف · sich einigen auf', wie: 'Da stimme ich dir zu. · Wir haben uns auf einen Termin geeinigt.', warum: 'الفعلان يأخذان داتيف، وsich einigen يحتاج auf + نصب.', anchor: 'sich einigen' },
      { trick: 'زمن الحديث: schweigen · die Stille · die Rückmeldung', wie: 'Er schwieg lange. · Danke für die Rückmeldung.', warum: 'الصمت والتغذية الراجعة جزء من الحوار المُقاس في B1 الشفوي.', anchor: 'schweigen' }
    ]
  },

  'b1-u4-l6': {
    items: [
      ['die Anrede', 'die Anreden', 'النداء', 'Die Anrede muss korrekt sein.', 'Die Anrede muss korrekt gemacht sein.', 'الصفة تكفي.', 'lexik-kollokation', 'Anrede'],
      ['der Betreff', 'die Betreffe', 'الموضوع', 'Der Betreff steht über dem Text.', 'Der Betreff steht in dem Text.', 'الفوقية: über.', 'präposition', 'Betreff'],
      ['die Anlage', 'die Anlagen', 'المرفق', 'Die Anlagen sind im Anhang.', 'Die Anlagen sind in Anhang.', 'im Anhang.', 'präposition', 'Anlagen'],
      ['der Anhang', 'die Anhänge', 'الملحق', 'Im Anhang finden Sie die Zeugnisse.', 'In Anhang finden Sie die Zeugnisse.', 'im.', 'präposition', 'Anhang'],
      ['die Unterschrift', 'die Unterschriften', 'التوقيع', 'Die Unterschrift fehlt noch.', 'Die Unterschrift fehlt noch es.', 'لا ضمير زائد.', 'wortstellung', 'Unterschrift'],
      ['unterschreiben', 'unterschreibt · unterschrieb · hat unterschrieben', 'يوقّع', 'Unterschreiben Sie bitte unten.', 'Unterschreiben Sie bitte unten du.', 'لا ضمير بعد الفعل المهذب.', 'wortstellung', 'unterschreiben'],
      ['der Antrag', 'die Anträge', 'الطلب', 'Der Antrag ist vollständig.', 'Der Antrag ist vollständig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Antrag'],
      ['beantragen', 'beantragt · beantragte · hat beantragt', 'يطلب رسميًا', 'Ich beantrage ein Stipendium.', 'Ich beantrage für ein Stipendium.', 'بلا حرف جر.', 'kasus', 'beantrage'],
      ['der Widerspruch', 'die Widersprüche', 'الاعتراض الرسمي', 'Der Widerspruch muss schriftlich erfolgen.', 'Der Widerspruch muss schriftlich erfolgen es.', 'لا ضمير زائد.', 'wortstellung', 'Widerspruch'],
      ['die Frist', 'die Fristen', 'المهلة', 'Die Frist endet am 15. Mai.', 'Die Frist endet in 15. Mai.', 'التاريخ: am.', 'präposition', 'Frist'],
      ['die Verlängerung', 'die Verlängerungen', 'التمديد', 'Die Verlängerung ist nicht möglich.', 'Die Verlängerung ist nicht möglich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Verlängerung'],
      ['verlängern', 'verlängert · verlängerte · hat verlängert', 'يمدّد', 'Kann ich den Vertrag verlängern?', 'Kann ich den Vertrag verlängern es?', 'لا ضمير زائد.', 'wortstellung', 'verlängern'],
      ['kündigen', 'kündigt · kündigte · hat gekündigt', 'ينهي', 'Ich kündige mein Abo zum Monatsende.', 'Ich kündige mein Abo in Monatsende.', 'zum Monatsende.', 'präposition', 'kündige'],
      ['die Kündigung', 'die Kündigungen', 'الإنهاء', 'Die Kündigung muss schriftlich sein.', 'Die Kündigung muss schriftlich gemacht sein.', 'الصفة تكفي.', 'lexik-kollokation', 'Kündigung'],
      ['die Bestätigung', 'die Bestätigungen', 'التأكيد', 'Die Bestätigung kam per E-Mail.', 'Die Bestätigung kam mit E-Mail.', 'per E-Mail.', 'präposition', 'Bestätigung'],
      ['bestätigen', 'bestätigt · bestätigte · hat bestätigt', 'يؤكّد', 'Bitte bestätigen Sie den Termin.', 'Bitte bestätigen Sie den Termin du.', 'لا ضمير زائد.', 'wortstellung', 'bestätigen'],
      ['die Absage', 'die Absagen', 'الإلغاء', 'Die Absage kam zu spät.', 'Die Absage kam zu spät es.', 'لا ضمير زائد.', 'wortstellung', 'Absage'],
      ['absagen', 'sagt ab · sagte ab · hat abgesagt', 'يلغي', 'Ich muss den Termin leider absagen.', 'Ich muss den Termin leider sagen ab.', 'Partizip II: abgesagt.', 'konjugation', 'absagen'],
      ['die Zusage', 'die Zusagen', 'الموافقة', 'Die Zusage freut mich sehr.', 'Die Zusage freut mich sehr es.', 'لا ضمير زائد.', 'wortstellung', 'Zusage'],
      ['zusagen', 'sagt zu · sagte zu · hat zugesagt', 'يقبل', 'Er hat für Montag zugesagt.', 'Er hat für Montag gesagt zu.', 'Partizip II: zugesagt.', 'konjugation', 'zugesagt'],
      ['die Anfrage', 'die Anfragen', 'الاستفسار', 'Die Anfrage ist berechtigt.', 'Die Anfrage ist berechtigt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Anfrage'],
      ['die Auskunft', 'die Auskünfte', 'المعلومة الرسمية', 'Die Auskunft erhalten Sie telefonisch.', 'Die Auskunft erhalten Sie telefonisch es.', 'لا ضمير زائد.', 'wortstellung', 'Auskunft'],
      ['der Sachbearbeiter', 'die Sachbearbeiter', 'الموظّف المسؤول', 'Der Sachbearbeiter ist im Urlaub.', 'Der Sachbearbeiter ist in Urlaub.', 'im Urlaub.', 'präposition', 'Sachbearbeiter'],
      ['die Behörde', 'die Behörden', 'الدائرة الرسمية', 'Die Behörde öffnet um acht.', 'Die Behörde öffnet in acht.', 'الساعة: um.', 'präposition', 'Behörde'],
      ['das Amt', 'die Ämter', 'المصلحة', 'Auf dem Amt muss man warten.', 'In dem Amt muss man warten.', 'auf dem Amt ثابتة.', 'präposition', 'Amt'],
      ['der Termin', 'die Termine', 'الموعد', 'Der Termin wurde verschoben.', 'Der Termin wurde verschieben.', 'المجهول: verschoben.', 'konjugation', 'Termin'],
      ['vereinbaren', 'vereinbart · vereinbarte · hat vereinbart', 'يتفق على', 'Wir vereinbaren einen neuen Termin.', 'Wir vereinbaren für einen neuen Termin.', 'بلا حرف جر.', 'kasus', 'vereinbaren'],
      ['verschieben', 'verschiebt · verschob · hat verschoben', 'يؤجّل', 'Wir müssen den Termin verschieben.', 'Wir müssen den Termin verschieben es.', 'لا ضمير زائد.', 'wortstellung', 'verschieben'],
      ['die Rückmeldung', 'die Rückmeldungen', 'الردّ', 'Wir bitten um eine kurze Rückmeldung.', 'Wir bitten für eine kurze Rückmeldung.', 'bitten um.', 'präposition', 'Rückmeldung'],
      ['die Erstattung', 'die Erstattungen', 'التعويض', 'Die Erstattung erfolgt in drei Tagen.', 'Die Erstattung erfolgt in drei Tag.', 'الجمع: Tagen.', 'plural', 'Erstattung'],
      ['der Antragsteller', 'die Antragsteller', 'مقدّم الطلب', 'Der Antragsteller muss unterschreiben.', 'Der Antragsteller muss unterschreiben es.', 'لا ضمير زائد.', 'wortstellung', 'Antragsteller'],
      ['die Unterlagen', '—', 'الوثائق', 'Die Unterlagen sind vollständig.', 'Die Unterlagen sind vollständig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Unterlagen'],
      ['die Kopie', 'die Kopien', 'النسخة', 'Bitte senden Sie eine Kopie.', 'Bitte senden Sie ein Kopie.', 'مؤنث: eine.', 'genus', 'Kopie'],
      ['die Original', 'die Originale', 'الأصل', 'Das Original bleibt bei Ihnen.', 'Das Original bleibt mit Ihnen.', 'bei Ihnen.', 'präposition', 'Original'],
      ['die Vollmacht', 'die Vollmachten', 'التوكيل', 'Ohne Vollmacht geht nichts.', 'Ohne eine Vollmacht geht nichts.', 'بعد ohne بلا أداة.', 'kasus', 'Vollmacht'],
      ['die Verpflichtung', 'die Verpflichtungen', 'الالتزام', 'Diese Verpflichtung gilt ein Jahr.', 'Diese Verpflichtung gilt für ein Jahr.', 'بلا حرف جر.', 'präposition', 'Verpflichtung'],
      ['die Zahlungsfrist', 'die Zahlungsfristen', 'مهلة الدفع', 'Die Zahlungsfrist beträgt vierzehn Tage.', 'Die Zahlungsfrist beträgt für vierzehn Tage.', 'بلا حرف جر.', 'präposition', 'Zahlungsfrist'],
      ['der Widerspruch einlegen', 'legt ein · legte ein · hat eingelegt', 'يقدّم اعتراضًا', 'Ich lege Widerspruch gegen den Bescheid ein.', 'Ich lege Widerspruch gegen den Bescheid.', 'المنفصل: ein.', 'wortstellung', 'ein'],
      ['der Bescheid', 'die Bescheide', 'القرار الرسمي', 'Der Bescheid kam gestern per Post.', 'Der Bescheid kam gestern mit Post.', 'per Post.', 'präposition', 'Bescheid'],
      ['mit freundlichen Grüßen', '—', 'مع أطيب التحيات', 'Mit freundlichen Grüßen, Ali Ben Salah', 'Mit freundliche Grüßen, Ali Ben Salah', 'الوصف: freundlichen.', 'deklination', 'Grüßen']
    ],
    tricks: [
      { trick: 'الرسالة الرسمية قالَب: Betreff · Anrede · Text · Grußformel · Unterschrift', wie: 'Betreff: Antrag auf Verlängerung. Sehr geehrte Damen und Herren, … Mit freundlichen Grüßen, Ali Ben Salah', warum: 'الرسالة العربية تبدأ بالتحية ثم الموضوع، والألمانية تبدأ بالموضوع (Betreff) قبله.', anchor: 'der Betreff' },
      { trick: 'طلب رسمي: beantragen · Widerspruch einlegen · verlängern · kündigen', wie: 'Ich beantrage eine Verlängerung. · Ich lege Widerspruch ein.', warum: 'العربية تقول «أطلب تمديدًا» بفعل واحد لكل شيء، والألمانية تفرّق بين الطلب العام والاعتراض الرسمي.', anchor: 'beantragen' },
      { trick: 'الإجراء الرسمي: die Frist · die Unterlagen · die Vollmacht · die Bestätigung', wie: 'Die Frist endet am 15. Mai. · Die Unterlagen sind vollständig.', warum: 'المصطلحات الإدارية الأربعة هي التي تحمل الخبر في الرسالة، وترجمتها الحرفية تُفقدها المعنى القانوني.', anchor: 'die Frist' }
    ]
  }

};
