/* Deutschweg — B1 lexical layer, unit 4 (part a): b1-u4-l1 … b1-u4-l3.
   40 items per lesson, the count the B1 rows declare (amendment B1-L1).
   Not wired yet — see the header of vocab-b1-u1a.js for why and how. */

module.exports = {

  'b1-u4-l1': {
    items: [
      ['das Ehrenamt', 'die Ehrenämter', 'العمل التطوعي', 'Sie hat ein Ehrenamt bei der Feuerwehr.', 'Sie hat ein Ehrenamt in der Feuerwehr.', 'bei (الجهة) لا in.', 'präposition', 'Ehrenamt'],
      ['das Engagement', 'die Engagements', 'الالتزام التطوعي', 'Sein Engagement beeindruckt alle.', 'Sein Engagement beeindruckt alle es.', 'لا ضمير زائد.', 'wortstellung', 'Engagement'],
      ['die Freiwilligenarbeit', '—', 'العمل التطوعي', 'Freiwilligenarbeit ist nicht bezahlt.', 'Freiwilligenarbeit ist nicht bezahlen.', 'الصفة + Partizip II.', 'konjugation', 'Freiwilligenarbeit'],
      ['der Freiwillige', 'die Freiwilligen', 'المتطوّع', 'Die Freiwilligen arbeiten am Wochenende.', 'Die Freiwillige arbeiten am Wochenende.', 'الجمع مع die: Freiwilligen.', 'deklination', 'Freiwilligen'],
      ['die Initiative', 'die Initiativen', 'المبادرة', 'Die Initiative sammelt Geld für Kinder.', 'Die Initiative sammelt Geld zu Kindern.', 'für لا zu.', 'präposition', 'Initiative'],
      ['das Projekt', 'die Projekte', 'المشروع', 'Das Projekt läuft seit zwei Jahren.', 'Das Projekt läuft von zwei Jahren.', 'منذ: seit.', 'präposition', 'Projekt'],
      ['der Verein', 'die Vereine', 'الجمعية', 'Der Verein hat hundert Mitglieder.', 'Der Verein hat hundert Mitglied.', 'الجمع: Mitglieder.', 'plural', 'Verein'],
      ['das Mitglied', 'die Mitglieder', 'العضو', 'Ich bin Mitglied im Sportverein.', 'Ich bin ein Mitglied im Sportverein.', 'بلا أداة في هذه العبارة.', 'lexik-kollokation', 'Mitglied'],
      ['die Gemeinschaft', 'die Gemeinschaften', 'الجماعة', 'Die Gemeinschaft hilft sich gegenseitig.', 'Die Gemeinschaft hilft sich gegenseitig es.', 'لا ضمير زائد.', 'wortstellung', 'Gemeinschaft'],
      ['die Solidarität', '—', 'التضامن', 'Solidarität ist in Krisen wichtig.', 'Solidarität ist in Krisen wichtig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Solidarität'],
      ['die Unterstützung', 'die Unterstützungen', 'الدعم', 'Die Unterstützung kam schnell.', 'Die Unterstützung kam schnell es.', 'لا ضمير زائد.', 'wortstellung', 'Unterstützung'],
      ['die Spende', 'die Spenden', 'التبرّع', 'Die Spende ist steuerlich absetzbar.', 'Die Spende ist steuerlich absetzbar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Spende'],
      ['spenden', 'spendet · spendete · hat gespendet', 'يتبرّع', 'Wir spenden Kleidung für die Flutopfer.', 'Wir spenden Kleidung zu den Flutopfern.', 'für لا zu.', 'präposition', 'spenden'],
      ['sich engagieren', 'engagiert sich · engagierte sich · hat sich engagiert', 'يلتزم/ينخرط', 'Sie engagiert sich für den Tierschutz.', 'Sie engagiert für den Tierschutz.', 'الضمير sich لازم.', 'konjugation', 'engagiert'],
      ['helfen', 'hilft · half · hat geholfen', 'يساعد', 'Wir helfen den Nachbarn beim Umzug.', 'Wir helfen die Nachbarn beim Umzug.', 'helfen + داتيف.', 'kasus', 'helfen'],
      ['unterstützen', 'unterstützt · unterstützte · hat unterstützt', 'يدعم', 'Der Verein unterstützt arme Familien.', 'Der Verein unterstützt für arme Familien.', 'بلا حرف جر.', 'kasus', 'unterstützt'],
      ['teilnehmen', 'nimmt teil · nahm teil · hat teilgenommen', 'يشارك', 'Ich nehme an dem Kurs teil.', 'Ich nehme den Kurs teil.', 'teilnehmen an + داتيف.', 'präposition', 'teil'],
      ['mitmachen', 'macht mit · machte mit · hat mitgemacht', 'يشارك', 'Machst du beim Wettbewerb mit?', 'Machst du beim Wettbewerb?', 'المنفصل: mit.', 'wortstellung', 'mit'],
      ['organisieren', 'organisiert · organisierte · hat organisiert', 'ينظّم', 'Wir organisieren ein Fest für die Kinder.', 'Wir organisieren ein Fest zu den Kindern.', 'für لا zu.', 'präposition', 'organisieren'],
      ['sammeln', 'sammelt · sammelte · hat gesammelt', 'يجمع', 'Sie sammeln Geld für die Schule.', 'Sie sammeln Geld zu der Schule.', 'für.', 'präposition', 'sammeln'],
      ['gewinnen', 'gewinnt · gewann · hat gewonnen', 'يفوز', 'Wir haben den Preis gewonnen.', 'Wir haben den Preis gewinnen.', 'الماضي المركّب: gewonnen.', 'konjugation', 'gewonnen'],
      ['der Gewinn', 'die Gewinne', 'المكسب', 'Der Gewinn geht an die Schule.', 'Der Gewinn geht zu der Schule.', 'an + نصب (الجهة).', 'präposition', 'Gewinn'],
      ['die Aktion', 'die Aktionen', 'الحملة', 'Die Aktion dauert eine Woche.', 'Die Aktion dauert für eine Woche.', 'بلا حرف جر.', 'präposition', 'Aktion'],
      ['das Fest', 'die Feste', 'الحفل', 'Das Fest findet im Hof statt.', 'Das Fest findet im Hof.', 'stattfinden يحتاج statt.', 'wortstellung', 'statt'],
      ['die Nachbarschaftshilfe', '—', 'مساعدة الجيران', 'Nachbarschaftshilfe ist bei uns normal.', 'Nachbarschaftshilfe ist bei uns normal gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Nachbarschaftshilfe'],
      ['der Nachbar', 'die Nachbarn', 'الجار', 'Die Nachbarn gießen die Blumen.', 'Die Nachbarn gießen für die Blumen.', 'بلا حرف جر.', 'kasus', 'Nachbarn'],
      ['die Pflicht', 'die Pflichten', 'الواجب', 'Es ist meine Pflicht zu helfen.', 'Es ist meine Pflicht helfen.', 'zu + مصدر.', 'wortstellung', 'Pflicht'],
      ['die Verantwortung', 'die Verantwortungen', 'المسؤولية', 'Wir übernehmen Verantwortung.', 'Wir übernehmen für Verantwortung.', 'بلا حرف جر.', 'kasus', 'Verantwortung'],
      ['übernehmen', 'übernimmt · übernahm · hat übernommen', 'يتولّى', 'Er übernimmt die Leitung der Gruppe.', 'Er übernimmt für die Leitung der Gruppe.', 'بلا حرف جر.', 'kasus', 'übernimmt'],
      ['die Leitung', 'die Leitungen', 'القيادة', 'Die Leitung liegt bei ihr.', 'Die Leitung liegt in ihr.', 'bei لا in.', 'präposition', 'Leitung'],
      ['der Einsatz', 'die Einsätze', 'المشاركة الميدانية', 'Der Einsatz dauert bis Mitternacht.', 'Der Einsatz dauert bis zu Mitternacht.', 'bis mitternacht بلا zu.', 'präposition', 'Einsatz'],
      ['die Feuerwehr', 'die Feuerwehren', 'الإطفاء', 'Die Feuerwehr kam in fünf Minuten.', 'Die Feuerwehr kam in fünf Minute.', 'الجمع: Minuten.', 'plural', 'Feuerwehr'],
      ['das Rote Kreuz', '—', 'الهلال الأحمر', 'Das Rote Kreuz sucht Helfer.', 'Das Rote Kreuz sucht für Helfer.', 'بلا حرف جر.', 'kasus', 'Kreuz'],
      ['die Umweltgruppe', 'die Umweltgruppen', 'المجموعة البيئية', 'Die Umweltgruppe pflanzt Bäume.', 'Die Umweltgruppe pflanzt Bäume es.', 'لا ضمير زائد.', 'wortstellung', 'Umweltgruppe'],
      ['der Baum', 'die Bäume', 'الشجرة', 'Wir pflanzen jeden Frühling Bäume.', 'Wir pflanzen jeden Frühling Baum.', 'الجمع: Bäume.', 'plural', 'Bäume'],
      ['die Kleidersammlung', 'die Kleidersammlungen', 'جمع الملابس', 'Die Kleidersammlung ist im Mai.', 'Die Kleidersammlung ist in Mai.', 'im.', 'präposition', 'Kleidersammlung'],
      ['die Hilfe', 'die Hilfen', 'المساعدة', 'Ohne Hilfe schaffen wir das nicht.', 'Ohne die Hilfe schaffen wir das nicht.', 'بعد ohne بلا أداة.', 'kasus', 'Hilfe'],
      ['gemeinnützig', '—', 'ذو نفع عام', 'Der Verein ist gemeinnützig.', 'Der Verein ist gemeinnützig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'gemeinnützig'],
      ['freiwillig', '—', 'طوعي', 'Die Arbeit ist freiwillig.', 'Die Arbeit ist freiwillig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'freiwillig'],
      ['ehrenamtlich', '—', 'بصفة تطوعية', 'Er arbeitet ehrenamtlich.', 'Er arbeitet ehrenamtlich es.', 'لا ضمير زائد.', 'wortstellung', 'ehrenamtlich']
    ],
    tricks: [
      { trick: 'sich engagieren für · teilnehmen an · helfen + داتيف', wie: 'Sie engagiert sich für den Tierschutz. · Ich nehme an dem Kurs teil.', warum: 'العربية تصل «يشارك/يتطوّع» بالمفعول مباشرة، والألمانية تربط كل فعل بحرفه.', anchor: 'sich engagieren' },
      { trick: 'Aktivität und Gremium: der Verein · das Mitglied · die Leitung · der Einsatz', wie: 'Der Verein hat hundert Mitglieder. · Die Leitung liegt bei ihr.', warum: 'مفردات العمل الجمعوي نظام مغلق، وترجمته الحرفية من العربية تُنتج «membre de l\'association» لا «Mitglied im Verein».', anchor: 'der Verein' },
      { trick: 'الأفعال المنفصلة في العمل التطوعي: teilnehmen · mitmachen · stattfinden', wie: 'Ich nehme am Kurs teil. · Machst du mit?', warum: 'البادئة المنفصلة تُؤجّل إلى النهاية، والعربية لا تفصل الفعل فتُنسى البادئة.', anchor: 'mitmachen' }
    ]
  },

  'b1-u4-l2': {
    items: [
      ['die Reise', 'die Reisen', 'السفر/الرحلة', 'Die Reise dauerte drei Wochen.', 'Die Reise dauerte für drei Wochen.', 'بلا حرف جر.', 'präposition', 'Reise'],
      ['die Rundreise', 'die Rundreisen', 'رحلة دائرية', 'Die Rundreise beginnt in Tunis.', 'Die Rundreise beginnt in Tunis es.', 'لا ضمير زائد.', 'wortstellung', 'Rundreise'],
      ['die Unterkunft', 'die Unterkünfte', 'المبيت', 'Die Unterkunft war einfach.', 'Die Unterkunft war einfach gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Unterkunft'],
      ['die Jugendherberge', 'die Jugendherbergen', 'بيت الشباب', 'Die Jugendherberge kostet wenig.', 'Die Jugendherberge kostet wenig es.', 'لا ضمير زائد.', 'wortstellung', 'Jugendherberge'],
      ['das Hotel', 'die Hotels', 'الفندق', 'Das Hotel liegt am Strand.', 'Das Hotel liegt in Strand.', 'am Strand.', 'präposition', 'Hotel'],
      ['das Zimmer', 'die Zimmer', 'الغرفة', 'Das Zimmer ist schon gebucht.', 'Das Zimmer ist schon buchen.', 'المجهول: gebucht.', 'konjugation', 'Zimmer'],
      ['die Buchung', 'die Buchungen', 'الحجز', 'Die Buchung ist bestätigt.', 'Die Buchung ist bestätigen.', 'المجهول: bestätigt.', 'konjugation', 'Buchung'],
      ['buchen', 'bucht · buchte · hat gebucht', 'يحجز', 'Ich buche den Flug online.', 'Ich buche den Flug für online.', 'بلا حرف جر.', 'kasus', 'buche'],
      ['der Flug', 'die Flüge', 'الطيران', 'Der Flug wurde gestrichen.', 'Der Flug wurde streichen.', 'المجهول: gestrichen.', 'konjugation', 'Flug'],
      ['die Fahrt', 'die Fahrten', 'السفرة', 'Die Fahrt dauert vier Stunden.', 'Die Fahrt dauert für vier Stunden.', 'بلا حرف جر.', 'präposition', 'Fahrt'],
      ['der Ausflug', 'die Ausflüge', 'الرحلة القصيرة', 'Der Ausflug lohnt sich.', 'Der Ausflug lohnt sich es.', 'لا ضمير زائد.', 'wortstellung', 'Ausflug'],
      ['die Sehenswürdigkeit', 'die Sehenswürdigkeiten', 'المعلم السياحي', 'Die Sehenswürdigkeiten sind berühmt.', 'Die Sehenswürdigkeiten sind berühmt gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Sehenswürdigkeiten'],
      ['der Reiseführer', 'die Reiseführer', 'المرشد/الدليل', 'Der Reiseführer erklärt die Geschichte.', 'Der Reiseführer erklärt für die Geschichte.', 'بلا حرف جر.', 'kasus', 'Reiseführer'],
      ['die Führung', 'die Führungen', 'الجولة المرشدة', 'Die Führung beginnt um zehn.', 'Die Führung beginnt in zehn.', 'الساعة: um.', 'präposition', 'Führung'],
      ['das Gepäck', '—', 'الأمتعة', 'Mein Gepäck ist nicht angekommen.', 'Mein Gepäck ist nicht ankommen.', 'الماضي المركّب: angekommen.', 'konjugation', 'Gepäck'],
      ['der Koffer', 'die Koffer', 'الحقيبة', 'Der Koffer ist zu schwer.', 'Der Koffer ist zu schwer gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Koffer'],
      ['der Rucksack', 'die Rucksäcke', 'حقيبة الظهر', 'Mein Rucksack ist leicht.', 'Mein Rucksack ist leicht gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Rucksack'],
      ['der Pass', 'die Pässe', 'الجواز', 'Der Pass läuft nächstes Jahr ab.', 'Der Pass läuft nächstes Jahr.', 'المنفصل: ab.', 'wortstellung', 'ab'],
      ['das Visum', 'die Visa', 'التأشيرة', 'Das Visum ist drei Monate gültig.', 'Das Visum ist drei Monate gültig gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Visum'],
      ['die Grenze', 'die Grenzen', 'الحدود', 'An der Grenze gab es Kontrollen.', 'In der Grenze gab es Kontrollen.', 'an لا in.', 'präposition', 'Grenze'],
      ['der Zoll', 'die Zölle', 'الجمارك', 'Der Zoll prüft die Waren.', 'Der Zoll prüft für die Waren.', 'بلا حرف جر.', 'kasus', 'Zoll'],
      ['die Verspätung', 'die Verspätungen', 'التأخير', 'Die Verspätung betrug zwei Stunden.', 'Die Verspätung betrug für zwei Stunden.', 'بلا حرف جر.', 'präposition', 'Verspätung'],
      ['der Anschluss', 'die Anschlüsse', 'الرحلة التالية', 'Der Anschluss ist weg.', 'Der Anschluss ist weg gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Anschluss'],
      ['umsteigen', 'steigt um · stieg um · ist umgestiegen', 'يغيّر الوسيلة', 'Wir sind in Frankfurt umgestiegen.', 'Wir haben in Frankfurt umgestiegen.', 'umsteigen مع sein.', 'konjugation', 'umgestiegen'],
      ['einsteigen', 'steigt ein · stieg ein · ist eingestiegen', 'يركب', 'Bitte einsteigen!', 'Bitte einsteigen du!', 'التعليمة بلا ضمير.', 'wortstellung', 'einsteigen'],
      ['aussteigen', 'steigt aus · stieg aus · ist ausgestiegen', 'ينزل', 'Wir steigen am Marktplatz aus.', 'Wir steigen in Marktplatz aus.', 'am لا in.', 'präposition', 'aus'],
      ['abfahren', 'fährt ab · fuhr ab · ist abgefahren', 'يقلع', 'Der Zug fährt um sieben ab.', 'Der Zug fährt in sieben ab.', 'الساعة: um.', 'präposition', 'ab'],
      ['ankommen', 'kommt an · kam an · ist angekommen', 'يصل', 'Wir kommen um acht an.', 'Wir kommen in acht an.', 'الساعة: um.', 'präposition', 'an'],
      ['die Ankunft', 'die Ankünfte', 'الوصول', 'Die Ankunft ist um zwanzig Uhr.', 'Die Ankunft ist in zwanzig Uhr.', 'الساعة: um.', 'präposition', 'Ankunft'],
      ['die Abfahrt', 'die Abfahrten', 'المغادرة', 'Die Abfahrt wurde verschoben.', 'Die Abfahrt wurde verschieben.', 'المجهول: verschoben.', 'konjugation', 'Abfahrt'],
      ['der Aufenthalt', 'die Aufenthalte', 'الإقامة', 'Der Aufenthalt war zu kurz.', 'Der Aufenthalt war zu kurz gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Aufenthalt'],
      ['die Verpflegung', '—', 'التغذية', 'Die Verpflegung ist im Preis enthalten.', 'Die Verpflegung ist in Preis enthalten.', 'في: im.', 'präposition', 'Verpflegung'],
      ['die Reisekasse', 'die Reisekassen', 'ميزانية السفر', 'Die Reisekasse ist leer.', 'Die Reisekasse ist leer gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Reisekasse'],
      ['die Währung', 'die Währungen', 'العملة', 'Man muss die Währung wechseln.', 'Man muss die Währung wechseln es.', 'لا ضمير زائد.', 'wortstellung', 'Währung'],
      ['wechseln', 'wechselt · wechselte · hat gewechselt', 'يبدّل', 'Ich wechsle Geld am Flughafen.', 'Ich wechsle Geld in Flughafen.', 'am Flughafen.', 'präposition', 'wechsle'],
      ['die Sehenswürdigkeit besichtigen', 'besichtigt · besichtigte · hat besichtigt', 'يزور معلمًا', 'Wir besichtigen morgen das Museum.', 'Wir besichtigen morgen in das Museum.', 'بلا حرف جر.', 'kasus', 'besichtigen'],
      ['besuchen', 'besucht · besuchte · hat besucht', 'يزور', 'Ich besuche jedes Jahr meine Familie.', 'Ich besuche jedes Jahr zu meiner Familie.', 'بلا حرف جر.', 'kasus', 'besuche'],
      ['die Aussicht', 'die Aussichten', 'المنظر', 'Die Aussicht vom Berg ist schön.', 'Die Aussicht von dem Berg ist schön.', 'von + داتيف صحيح لكن الأجمل: vom Berg.', 'präposition', 'Aussicht'],
      ['das Erlebnis', 'die Erlebnisse', 'التجربة', 'Das Erlebnis war unvergesslich.', 'Das Erlebnis war unvergesslich gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Erlebnis'],
      ['die Erinnerung', 'die Erinnerungen', 'الذكرى', 'Die Erinnerungen bleiben.', 'Die Erinnerungen bleiben es.', 'لا ضمير زائد.', 'wortstellung', 'Erinnerungen']
    ],
    tricks: [
      { trick: 'الرحلة بحروفها: ankommen um · abfahren um · umsteigen in', wie: 'Der Zug fährt um sieben ab. · Wir sind in Frankfurt umgestiegen.', warum: 'العربية تقول «وصل في السابعة»، والألمانية تفرّق بين um للساعة وin للمدينة.', anchor: 'umsteigen' },
      { trick: 'steigen-Familie: einsteigen · aussteigen · umsteigen — كلها مع sein', wie: 'Wir sind in Frankfurt umgestiegen. · Wir steigen am Marktplatz aus.', warum: 'العربية لا فرق عندها، والناطق يستعمل haben فورًا.', anchor: 'aussteigen' },
      { trick: 'الحجز: buchen · die Buchung · bestätigt · gestrichen', wie: 'Ich buche den Flug online. Die Buchung ist bestätigt.', warum: 'المجهول في أخبار السفر (bestätigt/gestrichen) لا يقابله فعل مبني للمجهول في العربية.', anchor: 'buchen' }
    ]
  },

  'b1-u4-l3': {
    items: [
      ['die Meinung', 'die Meinungen', 'الرأي', 'Meiner Meinung nach ist das falsch.', 'In meiner Meinung ist das falsch.', 'الصيغة الثابتة: meiner Meinung nach.', 'register', 'Meinung'],
      ['die Begründung', 'die Begründungen', 'التعليل', 'Ohne Begründung wirkt das schwach.', 'Ohne eine Begründung wirkt das schwach.', 'بعد ohne بلا أداة.', 'kasus', 'Begründung'],
      ['begründen', 'begründet · begründete · hat begründet', 'يعلّل', 'Wie begründest du das?', 'Wie begründest du für das?', 'بلا حرف جر.', 'kasus', 'begründest'],
      ['das Argument', 'die Argumente', 'الحجة', 'Das Argument überzeugt mich.', 'Das Argument überzeugt mich es.', 'لا ضمير زائد.', 'wortstellung', 'Argument'],
      ['argumentieren', 'argumentiert · argumentierte · hat argumentiert', 'يحتجّ', 'Sie argumentiert ruhig und sachlich.', 'Sie argumentiert ruhig und sachlich es.', 'لا ضمير زائد.', 'wortstellung', 'argumentiert'],
      ['der Grund', 'die Gründe', 'السبب', 'Es gibt mehrere Gründe dafür.', 'Es gibt mehrere Grund dafür.', 'الجمع: Gründe.', 'plural', 'Gründe'],
      ['der Beweis', 'die Beweise', 'الدليل', 'Wo ist der Beweis?', 'Wo ist die Beweis?', 'مذكر: der.', 'genus', 'Beweis'],
      ['beweisen', 'beweist · bewies · hat bewiesen', 'يبرهن', 'Das lässt sich leicht beweisen.', 'Das lässt sich leicht beweisen es.', 'لا ضمير زائد.', 'wortstellung', 'beweisen'],
      ['das Beispiel', 'die Beispiele', 'المثال', 'Ein Beispiel macht es klar.', 'Ein Beispiel macht es klar es.', 'لا ضمير زائد.', 'wortstellung', 'Beispiel'],
      ['der Beleg', 'die Belege', 'الإثبات', 'Für diese Zahl fehlt der Beleg.', 'Für diese Zahl fehlt die Beleg.', 'مذكر: der.', 'genus', 'Beleg'],
      ['der Standpunkt', 'die Standpunkte', 'الموقف', 'Ich verstehe deinen Standpunkt.', 'Ich verstehe dein Standpunkt.', 'مذكر نصب: deinen.', 'kasus', 'Standpunkt'],
      ['die Ansicht', 'die Ansichten', 'الرؤية', 'Meiner Ansicht nach stimmt das.', 'In meiner Ansicht stimmt das.', 'meiner Ansicht nach.', 'register', 'Ansicht'],
      ['die Position', 'die Positionen', 'الموقف', 'Seine Position ist klar.', 'Seine Position ist klar gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Position'],
      ['einerseits', '—', 'من جهة', 'Einerseits ist es teuer.', 'Einerseits es ist teuer.', 'الفعل ثانٍ.', 'wortstellung', 'einerseits'],
      ['andererseits', '—', 'من جهة أخرى', 'Andererseits spart es Zeit.', 'Andererseits es spart Zeit.', 'الفعل ثانٍ.', 'wortstellung', 'andererseits'],
      ['zwar', '—', 'نعم ولكن', 'Zwar ist es weit, aber schön.', 'Zwar es ist weit, aber schön.', 'الفعل ثانٍ بعد zwar.', 'wortstellung', 'Zwar'],
      ['allerdings', '—', 'لكن', 'Es ist billig, allerdings weit weg.', 'Es ist billig, allerdings es ist weit weg.', 'الفعل ثانٍ.', 'wortstellung', 'allerdings'],
      ['dennoch', '—', 'ومع ذلك', 'Es war teuer, dennoch hat es sich gelohnt.', 'Es war teuer, dennoch es hat sich gelohnt.', 'الفعل ثانٍ.', 'wortstellung', 'dennoch'],
      ['folglich', '—', 'وبالتالي', 'Die Kosten steigen, folglich sparen wir.', 'Die Kosten steigen, folglich wir sparen.', 'الفعل ثانٍ.', 'wortstellung', 'folglich'],
      ['daher', '—', 'من هنا', 'Es fehlt Geld, daher wird gekürzt.', 'Es fehlt Geld, daher wird kürzen.', 'المجهول: gekürzt.', 'konjugation', 'daher'],
      ['im Gegenteil', '—', 'على العكس', 'Im Gegenteil, es ist billiger.', 'Im Gegenteil, es ist billiger es.', 'لا ضمير زائد.', 'wortstellung', 'Gegenteil'],
      ['im Vergleich zu', '—', 'بالمقارنة مع', 'Im Vergleich zu letztem Jahr ist es besser.', 'Im Vergleich mit letztem Jahr ist es besser.', 'zu لا mit.', 'präposition', 'Vergleich'],
      ['zum einen', '—', 'من ناحية', 'Zum einen ist es schnell, zum anderen günstig.', 'Zum einen es ist schnell, zum anderen günstig.', 'الفعل ثانٍ.', 'wortstellung', 'einen'],
      ['zum anderen', '—', 'ومن ناحية أخرى', 'Zum anderen spart es Geld.', 'Zum anderen es spart Geld.', 'الفعل ثانٍ.', 'wortstellung', 'anderen'],
      ['obwohl', '—', 'رغم أنّ', 'Obwohl es teuer ist, kaufe ich es.', 'Obwohl es ist teuer, kaufe ich es.', 'الفعل في النهاية.', 'wortstellung', 'obwohl'],
      ['trotzdem', '—', 'رغم ذلك', 'Es ist teuer, trotzdem kaufe ich es.', 'Es ist teuer, trotzdem ich kaufe es.', 'الفعل ثانٍ.', 'wortstellung', 'trotzdem'],
      ['deshalb', '—', 'لذلك', 'Ich mag es, deshalb kaufe ich es.', 'Ich mag es, deshalb ich kaufe es.', 'الفعل ثانٍ.', 'wortstellung', 'deshalb'],
      ['die Schlussfolgerung', 'die Schlussfolgerungen', 'الاستنتاج', 'Deine Schlussfolgerung ist falsch.', 'Deine Schlussfolgerung ist falsch gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Schlussfolgerung'],
      ['das Fazit', 'die Fazits', 'الخلاصة', 'Das Fazit lautet: Qualität siegt.', 'Das Fazit lautet: Qualität siegt es.', 'لا ضمير زائد.', 'wortstellung', 'Fazit'],
      ['die Zusammenfassung', 'die Zusammenfassungen', 'التلخيص', 'Die Zusammenfassung ist kurz.', 'Die Zusammenfassung ist kurz gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Zusammenfassung'],
      ['die Behauptung', 'die Behauptungen', 'الادّعاء', 'Diese Behauptung stimmt nicht.', 'Diese Behauptung stimmt nicht es.', 'لا ضمير زائد.', 'wortstellung', 'Behauptung'],
      ['behaupten', 'behauptet · behauptete · hat behauptet', 'يدّعي', 'Er behauptet, dass alles in Ordnung ist.', 'Er behauptet, dass alles ist in Ordnung.', 'الفعل في النهاية.', 'wortstellung', 'behauptet'],
      ['widersprechen', 'widerspricht · widersprach · hat widersprochen', 'يعترض', 'Ich muss dir widersprechen.', 'Ich muss dich widersprechen.', 'داتيف: dir.', 'kasus', 'widersprechen'],
      ['zustimmen', 'stimmt zu · stimmte zu · hat zugestimmt', 'يوافق', 'Da stimme ich dir zu.', 'Da stimme ich dich zu.', 'داتيف: dir.', 'kasus', 'stimme'],
      ['zustimmen können', 'kann zu · konnte zu · hat zugestimmt', 'يمكن الموافقة', 'Dem kann ich zustimmen.', 'Das kann ich zustimmen.', 'داتيف: dem.', 'kasus', 'zustimmen'],
      ['die Ablehnung', 'die Ablehnungen', 'الرفض', 'Die Ablehnung kam per Brief.', 'Die Ablehnung kam mit Brief.', 'per Brief.', 'präposition', 'Ablehnung'],
      ['ablehnen', 'lehnt ab · lehnte ab · hat abgelehnt', 'يرفض', 'Sie lehnt den Vorschlag ab.', 'Sie lehnt den Vorschlag.', 'المنفصل: ab.', 'wortstellung', 'ab'],
      ['befürworten', 'befürwortet · befürwortete · hat befürwortet', 'يؤيّد', 'Die Mehrheit befürwortet den Plan.', 'Die Mehrheit befürwortet für den Plan.', 'بلا حرف جر.', 'kasus', 'befürwortet'],
      ['abwägen', 'wägt ab · wog ab · hat abgewogen', 'يوازن', 'Wir müssen die Vor- und Nachteile abwägen.', 'Wir müssen die Vor- und Nachteile wägen.', 'المنفصل: ab.', 'wortstellung', 'abwägen'],
      ['die Konsequenz', 'die Konsequenzen', 'التبعة', 'Diese Konsequenz ist ernst.', 'Diese Konsequenz ist ernst gemacht.', 'الصفة تكفي.', 'lexik-kollokation', 'Konsequenz']
    ],
    tricks: [
      { trick: 'الرأي ثم السبب ثم الشاهد: Ich bin der Meinung, weil … / Zum Beispiel …', wie: 'Ich bin der Meinung, dass das falsch ist. Der Grund dafür ist einfach. Zum Beispiel …', warum: 'المقال الألماني يُبنى على هذا التدرّج، والعربية تبدأ بالحكم ثم تسرد بلا ربط صريح.', anchor: 'die Begründung' },
      { trick: 'ربط المتناقضات: zwar … aber · einerseits … andererseits · einerseits … dennoch', wie: 'Zwar ist es teuer, aber es lohnt sich. · Einerseits …, andererseits …', warum: 'الكتابة B1 تُقيَّم على الربط المزدوج، والعربية تكتفي بـ«لكن».', anchor: 'zwar' },
      { trick: 'الاعتراض والموافقة بداتيف: Ich stimme dir zu · Ich widerspreche dir', wie: 'Da stimme ich dir zu. · Ich muss dir leider widersprechen.', warum: 'الفعلان يطلبان داتيف، والعربية تصل الفعل بالشخص بلا حالة.', anchor: 'zustimmen' }
    ]
  }

};
